### ISSUE TITLE
Provide a convenience method to determine Culture from the Accept-Language header

### ISSUE THREAD

**Issue by pranavkm** [aspnet/HttpAbstractions#10]
Ported from https://github.com/aspnet/Helios/issues/2

**Comment by Tratcher** [comment]
Half solved with the new strongly typed headers:
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Extensions/RequestHeaders.cs#L55
You just need to provide the mapping to an actual culture.

**Comment by muratg** [comment]
@pranavkm Do you guys still need this?  Or is this a "nice to have"?

**Comment by Eilon** [comment]
We should look at what ASP.NET 4.x had and see if we want to do something similar. It's not that MVC would necessarily need this, but rather more likely it'd be in app code.

**Comment by pranavkm** [comment]
@muratg sorry didn't see the comment earlier. For Mvc's use in model binding, this is a nice to have feature - to be able to get a Culture back for a specific request. However there's an alternate aspect of `Thread.CurrentCulture` being set according to the request culture which results in formatted strings producing the right value. Perhaps something in hosting needs to set this?

**Comment by Tratcher** [comment]
@pranavkm I assume this is now taken care of by https://github.com/aspnet/localization ?

**Comment by pranavkm** [comment]
Yup.
