### ISSUE TITLE
GetSetCookieLength method is not parsing correctly when cookie has invalid keyvalue pair

### ISSUE THREAD

**Issue by dhmuralikrishna** [aspnet/HttpAbstractions#1049]
Lets say set-cookie value is 
cookiename=cookievalue; Version=1; Domain=.contoso.com; Path=/; Secure; HttpOnly";

Then it's not parsing to SetcookieHeaderValue in  SetcookieHeaderValue.TryParse is returning null.

Version =1 might not be valid as per the spec. But other non-windows servers are sending the cookie like that. 

Expected Ignore Version =1 and fill remaining values in SetCookieHeaderValue.

**Comment by Tratcher** [comment]
Where are you getting cookies like this from?

**Comment by dhmuralikrishna** [comment]
From one of the dependent systems.

**Comment by dhmuralikrishna** [comment]
I think its java app don't know much details. we are consuming https endpoint int he response set-cookie it has version=1
