### ISSUE TITLE
HttpRequest should have a RawUrl property

### ISSUE THREAD

**Issue by pranavkm** [aspnet/HttpAbstractions#110]

**Comment by Halofreak1990** [comment]
@Tratcher I know this is an old issue, but...
> Why do you want the raw path and query?

To formulate a login link with a return URL, for example.
The GetDisplayUrl() and GetEncodedUrl() extensions provided by UriHelper don't work in this scenario, which also means that the suggested replacement at https://docs.microsoft.com/en-us/aspnet/core/migration/http-modules for Request.Url and Request.RawUrl is incorrect.

However, it's not unreasonable to argue that the naming of the RawUrl property is at least slightly misleading, as it only returns the URL's path and query. Would it be possible to add a property called PathAndQuery to HttpRequest, or a GetPathAndQuery() extension method to do the same?
