### ISSUE TITLE
Support owin.RequestId

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#117]
https://github.com/owin/owin/issues/8
https://katanaproject.codeplex.com/workitem/297

**Comment by Tratcher** [comment]
1. http.sys already has something we can use.
2. We need to find a feature interface to put this on internally.
3. this will be useful in logging.

**Comment by Praburaj** [comment]
The closest one that I can find where we can add to the existing interface is `IHttpConnectionFeature`. or we can add an interface `IHttpRequestIdentifierFeature`.

**Comment by Praburaj** [comment]
Fixed : https://github.com/aspnet/HttpAbstractions/commit/ae23f7c7bc956d40040c7a7a45aa2dedd293ebc4

We now have a feature `IRequestIdentifierFeature` to give this information.
