### ISSUE TITLE
Logging around middleware pipeline

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/HttpAbstractions#144]
As per the discussion for @lodejard, we would like to add logging around when middleware is registered and when the pipeline is executed. The intent is to be able to present a list of the middleware that is registered and then show the what middleware was executed to serve a given request.

**Comment by davidfowl** [comment]
We're opening up services in Hosting to make decorating the IApplicationBuilder much easier. Glimpse can plugin in here and provide an IAppBuilder that does something the tracking of middlewares etc.

The PR is here https://github.com/aspnet/Hosting/pull/192. But the relevant interface is https://github.com/aspnet/Hosting/blob/haok/3-14armageddon/src/Microsoft.AspNet.Hosting/Startup/IStartupFilter.cs

**Comment by avanderhoorn** [comment]
+1
