### ISSUE TITLE
Supported way of getting RemoteIpAddress

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/HttpAbstractions#149]
In OWIN, `RemoteIpAddress` via the `HttpRequest`. In vNext world, I can see that `IHttpConnectionFeature` has the IpAddress, and I can see that `DefaultHttpRequest` has the `HttpConnectionFeature` has a private property, but that property is never used and `IHttpRequest` doesn't have a `RemoteIpAddress` property.

**Comment by sandorfr** [comment]
It is frequent to use client ip adresss to approximate geolocation (analytics or choose an appropriate default culture). 

An example : server side call to mixpanel analytics, if we do not provide client IP, mixpanel takes our server IP to compute some attributes.

I definitely need this :). Thanks for the workaround  @tugberkugurlu .

**Comment by avanderhoorn** [comment]
Just wondering if there is any progress on this one?

**Comment by davidfowl** [comment]
We should add this to HttpContext /cc @lodejard @glennc @muratg
