### ISSUE TITLE
renaming Microsoft.AspNet.HttpFeature to Microsoft.AspNet.HttpFeature.Interfaces

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/HttpAbstractions#150]
I assume that **Microsoft.AspNet.HttpFeature** library only holds `AssemblyNeutral` interfaces. In order to align with other similar libraries (like **Microsoft.Framework.Logging.Interfaces**, **Microsoft.Framework.Runtime.Interfaces**, etc.), I think it would be better to rename this to **Microsoft.AspNet.HttpFeature.Interfaces** or something similar.

**Comment by davidfowl** [comment]
Done
