### ISSUE TITLE
SignOutContext needs AuthenticationProperties

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#152]
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.PipelineCore/Security/SignOutContext.cs
Compare:
http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin/Security/AuthenticationResponseRevoke.cs

This was a late addition to Katana. WsFed & OIDC have need for sign-out properties in order to customize single-signout redirects.

Also update HttpResponse.SignOut(...).

**Comment by Praburaj** [comment]
https://github.com/aspnet/HttpAbstractions/commit/58c45cd379774cf1fd683a12465cb52094b7193d
