### ISSUE TITLE
Logging: Tracking state changes for http context

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/HttpAbstractions#153]
Moved from aspnet/MVC#1630.

The general design idea is to add logging to HttpContext when certain things happen.
#### HttpContext

Authenticate
Abort
Dispose
SetFeature
AcceptWebSocket ?
#### HttpResponse

Status code changed
Header replaced (which is also added)
OnSendingHeaders firing - Should probably be in the server.
OnSendingHeaders registrations
Body replaced
SignIn
SignOut
Challenge

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2732
