### ISSUE TITLE
HttpAbstractions - QueryString - the leading "?" does not conform to OWIN spec

### ISSUE THREAD

**Issue by fengari** [aspnet/HttpAbstractions#155]
http://owin.org/
Both 1.0.0 and the 1.1.0 draft say the owin.RequestQueryString must NOT include the leading "?" and the value may be an empty string.

This one:
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/QueryString.cs

throws in the constructor if the leading "?" is not there.

Which way do we go?

**Comment by darrelmiller** [comment]
[RFC 3986](https://tools.ietf.org/html/rfc3986#section-3) doesn't consider the question mark to be part of the query string.  Is it included for consistency with previous versions of ASP.NET?

**Comment by Tratcher** [comment]
It's primarily for convenience. This value us often used to generate new Uris via a simple concatenation with PathString:
`pathBase + path + query`, so having the `?` built in prevents you from having to do this:
`pathBase + path + (query.HasValue : "?" + query.Value : "")`

**Comment by MisinformedDNA** [comment]
We should move away from that kind of logic. There's a reason we have `Path` class and UriBuilder. 
```
var uriBuilder = new UriBuilder(path);
uriBuilder.Query = query;
uriBuilder.Uri.ToString();
```
Or if that is too verbose, something new like

    UrlPath.AddPath(pathBase).AddQuery(query)

Anything is better than string concatenation.

Even, adding a secondary property `PrefixedQueryString` or something would be better.

Sticking to specs is preferable so we can keep things consistent. I hate it when I have to think, "Wait, does this property start with the question mark or not?". Consistency means I can just assume the standard.

**Comment by MisinformedDNA** [comment]
Or using [this code](https://github.com/aspnet/HttpAbstractions/blob/7be9cefc4c7671caba7d8fe538ba6a0ad308fdad/src/Microsoft.AspNet.Owin/Utilities.cs#L23-L30)
```
path + Utilities.AddQuestionMark(query)
```
