### ISSUE TITLE
Need to document which OWIN keys are supported in the translation layer

### ISSUE THREAD

**Issue by Eilon** [aspnet/HttpAbstractions#156]
Something like this table:

http://katanaproject.codeplex.com/wikipage?title=OWIN%20Keys&referringTitle=Documentation

@Tratcher FYI from our discussion.

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Owin/OwinEnvironment.cs#L50

**Comment by glennc** [comment]
@Tratcher is that all of them?

**Comment by Tratcher** [comment]
Yes. You can compare to https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Owin/OwinFeatureCollection.cs but the two lists should be the same.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2731
