### ISSUE TITLE
ISession ArraySegment  API question

### ISSUE THREAD

**Issue by epignosisx** [aspnet/HttpAbstractions#159]
Hi. I was going over the ISession API and I was surprised about the usage of ArraySegment<byte> instead of just using Object. I'm curious to know why this API changed so much from the vCurrent API. Is there any design notes or other documentation about it? 

I find the current implementation too raw for most use cases. Is the team planning to create some extension methods to make it easier to set and get data from Session? Something like:

void Set(string key, object value);
object Get(string key);

**Comment by Tratcher** [comment]
The primary reason is that session is something that needs to be shared between multiple server instances. This requires that all the data be serialized and synced back and forth. We used to try to serialize 'object' automatically but that was precarious at the best of times. We've moved to an explicit serialization model instead.

There are already a variety of serialization extensions here: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Extensions/SessionCollectionExtensions.cs

Yes we plan to add more, but we don't expect 'object' to be one of them.

**Comment by epignosisx** [comment]
Thanks @Tratcher. I see your point, but most ASP.NET apps that I've worked on store complex object graphs in Session. We probably shouldn't do it, but that's the reality of most codebases I've seen.

Using the explicit serialization model a la SerializationInfo is painful for complex object graphs, maybe the team wants app devs to feel this pain and think harder if what they are doing is the right thing or not. But I suspect that app devs will just end up writing their own version of Set(string key, object value) and I much better use one provided by the framework than one created by me. Hopefully the team gives it a bit more thought.

It looks like the ISessionCollection is actually the abstraction that devs most likely will consume. Is this correct?

**Comment by Tratcher** [comment]
Yes, this is one place where developers should feel the pain of decisions that would otherwise negatively impact their application. Note I'm not endorsing SerializationInfo either, that's also quite painful. We'll continue to work with the community to develop the functionality and guidelines here.

Correct, ISessionCollection is the primary developer API.

**Comment by epignosisx** [comment]
Cool thanks!
