### ISSUE TITLE
Rename Microsoft.AspNet.PipelineCore

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#162]

**Comment by davidfowl** [comment]
Yes, please. Can we do this before in beta3? /cc @Eilon @Tratcher @muratg ?

**Comment by Eilon** [comment]
Fine with me. What's the new name?

**Comment by Eilon** [comment]
We should get as many renames as possible done for beta3.

**Comment by Tratcher** [comment]
Ms.AspNet....
Http.Impl
Http.Core

**Comment by Eilon** [comment]
`Microsoft.AspNet.Http.Core` doesn't seem terrible to me. That's kind of what's in there... the core types. Or `...Intrinsics`, but I hate that word.

**Comment by Tratcher** [comment]
That's the funny thing, Http contains the abstract intrinsics, PipelineCore contains the actual implementation of said intrinsics.

While we're at it are there alternatives to calling all of the implementation types Default*?

**Comment by Eilon** [comment]
Instead of `Default*` just call them `*`..?

**Comment by Tratcher** [comment]
E.g. DefaultHttpContext implements the abstract HttpContext.

**Comment by Eilon** [comment]
O I C. I guess in this case the `Default*` is kind of fine because no one aside from us ever sees those types. Everyone programs against the friendly-named types, which is most of what we care about...

**Comment by Tratcher** [comment]
DefaultHttpContext is often used in unit tests, but again, mostly in our own tests and less in other people's.

**Comment by davidfowl** [comment]
We shouldn't call it something obscure though.

**Comment by Eilon** [comment]
Default isn't very obscure so I think it's fine...

Now, back to the assembly/project name... Http.Core?
