### ISSUE TITLE
Remove WebUtilities dependency on Http

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#163]
Microsoft.AspNet.WebUtilities currently depends on Microsoft.AspNet.Http for the following classes:
QueryBuilder - Has a ToQueryString() method returning QueryString
UriHelper - Uses HostString, PathString, QueryString, FragmentString, HttpRequest, etc..

This library is only supposed to contain stand-alone parsers and utility methods. Consider moving the dependent classes to Microsoft.AspNet.Http.Extensions.

**Comment by davidfowl** [comment]
Feels like we should do this sooner rather than later. Would we keep those types in the Microsoft.AspNet.Http namespace? Feels weird to have those types on the default abstractions in another namespace.

**Comment by Tratcher** [comment]
I fixed this by moving QueryBuilder and UriHelper as part of my typed headers work. PR incoming.
