### ISSUE TITLE
Strongly typed Request/ResponseHeader properties should return readonly collections

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#169]
Users may write the following code:
`httpRequest.GetTypedHeaders().SetCookie.Add(myCookie);`

However, this will fail silently because SetCookie.get returns a collection of parsed values that is disconnected from the underlying response headers collection.

The correct code is:
`httpRequest.Headers.Append(HeaderNames.SetCookie, myCookie);`
or
`httpRequest.GetTypedHeaders().SetCookie = myCookies;`

To make sure users do not experience hard to debug silent failures have the IList returned by these properties be read only. We could also switch to IEnumerable.

Alternative: It might be possible to return an IList implementation that was actually bound to the underlying header collection and did live modifications, but that would be significantly more complicated. We can make that work later if there is a strong desire for it.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2730
