### ISSUE TITLE
Define common status code constants

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#174]
Enum was always a poor type for Http status codes (e.g. System.Net.HttpStatusCode). Static/const ints may be more appropriate. We recently added the following for common header names: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/HeaderNames.cs. Something similar for status codes would be reasonable.

**Comment by shawnwildermuth** [comment]
Doesn't matter to me whether it is Enum or static/const, just don't want dev's having to use specific numbers (especial sub-numbers like 403.1)
