### ISSUE TITLE
IsSecure is badly named

### ISSUE THREAD

**Issue by blowdart** [aspnet/HttpAbstractions#179]
Request.IsSecure returns true if the scheme is HTTPS. 

HTTS is not a guarantee of security, but merely that the request cannot be eavesdropped (and even then, given null ciphers, this is not actually true)

The the property name is disingenuous and should be removed, or changed to IsHttpsConnection.

**Comment by bitcrazed** [comment]
I agree. The statement IsSecure has a whole lot of connotations [some of which may not be true](http://www.zdnet.com/article/gogo-in-flight-wi-fi-serving-spoofed-ssl-certificates/), even when HTTPS is used.

**Comment by GrabYourPitchforks** [comment]
Related commits:
https://github.com/aspnet/Security/commit/a15cb4ffe559d2c7bb2f0e748e4a10446bd530a6
https://github.com/aspnet/Mvc/commit/cf36a601c61d5aa3b21d3f784b7198b5b4bdfa37

**Comment by bitcrazed** [comment]
Nice! Thanks for taking our concerns into consideration.
