### ISSUE TITLE
Incorrect remote IP address in IIS 8

### ISSUE THREAD

**Issue by stephenjwatkins** [aspnet/HttpAbstractions#181]
When retrieving a client's IP address in a .NET 5 application running on IIS 8, an incorrect IP address is returned. We're using Tugberk's implementation, which seems to be the generally accepted method.

Code to retrieve IP address:

    string clientIpAddress;
    var connection = context.HttpContext.GetFeature<IHttpConnectionFeature>();
    if (connection != null) {
        clientIpAddress = connection.RemoteIpAddress.ToString();
    }
    // Do something with clientIpAddress

It is unclear where the returned IP address is coming from, but we log the IP address and can clearly see they are incorrect.

When IIS request logging is enabled (to log client IPs), the IIS logs do show the correct client IP address.

We have run a .NET 4.5 application in the same IIS server retrieving the IP address using `Request.UserHostAddress`, and it does return the correct IP address (the same IP that is shown in the IIS logs).

We have also run the `k web` command on the same server box, with the same application that was packed for IIS. When running with `k web` it does also return the correct IP address (like the .NET 4.5 application and what shows up in the IIS logs).

So it seems to be the combination of .NET 5 and IIS that produces the incorrect IP address.

We're running on KRE 1.0.0-beta2, IIS 8, and Windows Server 2012 r2. No reverse proxy is being used.

**Comment by GrabYourPitchforks** [comment]
@stephenjwatkins is the IP address reversed (should read a.b.c.d but returns d.c.b.a), or is it just completely mangled to the point where it doesn't come close to resembling the correct value?

**Comment by stephenjwatkins** [comment]
@GrabYourPitchforks Actually, yes, they are coming in reversed. I'm surprised I didn't catch that before. But yes, a.b.c.d is coming in as d.c.b.a.

**Comment by GrabYourPitchforks** [comment]
Probably an endianness issue then - we'll look into it. Thanks for the report!

**Comment by GrabYourPitchforks** [comment]
Fixed.

**Comment by stephenjwatkins** [comment]
@GrabYourPitchforks thanks for the quick fix.

I just wanted to get a quick clarification on if the fix was on this HttpAbstractions package, and updating to the latest package would resolve the issue? Or if the fix was elsewhere/there's something else we need to do besides updating to a newer version of the HttpAbstractions package?

**Comment by GrabYourPitchforks** [comment]
The bug was actually in the `Microsoft.AspNet.Loader.IIS` package, not in HttpAbstractions, so that's where the fix was checked in.

**Comment by girishnuli** [comment]
@GrabYourPitchforks I am facing the same issue as the OP. Application is deployed on IIS/Windows Server 2012 R2 x64. We are using Cloudflare and need to verify that the incoming ip address range matches the cloudflare ip address range. IIS logs the correct ip address (108.162.229.98), where as the application gets the ip address reversed (98.229.162.108) using the same code as OP posted above. 

We are using Visual Studio 2015 CTP 6 to build the app (kre-clr-win-x64.1.0.0-beta3). The project.json has the following dependencies:

        "Microsoft.AspNet.Server.IIS": "1.0.0-beta3",
        "Microsoft.AspNet.Loader.IIS": "1.0.0-beta3",
        "Microsoft.AspNet.Mvc": "6.0.0-beta3",
        "Microsoft.AspNet.StaticFiles": "1.0.0-beta3",
        "Microsoft.Framework.ConfigurationModel.Json": "1.0.0-beta3",
        "Microsoft.Framework.DependencyInjection": "1.0.0-beta3",
        "Microsoft.AspNet.Security": "1.0.0-beta3",
        "Microsoft.AspNet.Hosting": "1.0.0-beta3",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-beta3",
        "Microsoft.AspNet.Diagnostics": "1.0.0-beta3",
        "Microsoft.AspNet.Security.Cookies": "1.0.0-beta3",
        "Npgsql": "2.2.4.3",
        "Dapper": "1.9.0",
        "NodaTime": "1.3.1",
        "Microsoft.AspNet.HttpFeature": "1.0.0.0-beta2"

Could you please point to the correct version of Microsoft.AspNet.Loader.IIS that we should be using to get a fix for this issue?

Thanks.

**Comment by GrabYourPitchforks** [comment]
The fix is available starting with Microsoft.AspNet.Server.IIS version 1.0.0-beta4-10983. You may need to update other core project references (such as the KRE host) to a corresponding beta4 release due to runtime interface changes between beta3 and beta4. @muratg should be able to assist you in finding a workable combination.

**Comment by girishnuli** [comment]
@GrabYourPitchforks Thank you! If we update references to beta4+, then I believe we will require dnx instead of kre? 

@muratg Any pointers on how we can upgrade to dnx and the latest beta packages without breaking VS CTP6? The name change is causing some confusion, so please dont mind I am getting this wrong.  Thanks.

**Comment by theonlylawislove** [comment]
I am experiencing this issue on Windows 7 with rc1-final. It works on Windows 10.

**Comment by Tratcher** [comment]
@theonlylawislove This bug was for a component that was obsoleted and replaced in beta8 (Microsoft.AspNet.Server.IIS). For issues with RC1 please open a new bug here: https://github.com/aspnet/iisintegration
