### ISSUE TITLE
Move StatusCodes to a more visible namespace

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpAbstractions#182]
Right now it's in `Microsoft.AspNet.WebUtilities` namespace. Suggest moving it to `Microsoft.AspNet.Http` so that it's more easily discoverable.

Example: https://github.com/aspnet/Mvc/pull/1924/files

We're using this in plenty of places in MVC but it's pretty much the only from that namespace we're interested in.

**Comment by Tratcher** [comment]
I wouldn't want to change the namespace without also changing the package.  Maybe we could put it in the Microsoft.AspNet.Http.Abstractions package and the Http namespace?

I noticed that very few of the linked samples referenced the Microsoft.AspNet.Http namespace either, so moving there doesn't really save you anything.

I'd like to put it into Microsoft.Net.Http, but I don't think they'd go for that.

**Comment by Tratcher** [comment]
Or should we rename this package to Http.Utilities?

**Comment by Tratcher** [comment]
Put it in Http.Abstractions package and Http namespace.

**Comment by Tratcher** [comment]
@rynowak Can you handle your own cleanup for this?

**Comment by khellang** [comment]
I still think the smurf naming is a bit too much though... `StausCodes.Status200OK`? It wouldn't hurt to leave out the some StatusStatus? :wink:
