### ISSUE TITLE
More unit-testable DefaultHttpRequest.Cookies??

### ISSUE THREAD

**Issue by ianhong** [aspnet/HttpAbstractions#183]
Can we make DefaultHttpRequest.Cookies more unit-testable just like the Form property? 

        public override IFormCollection Form
        {
            get { return FormFeature.ReadForm(); }
            set { FormFeature.Form = value; }
        }

Thanks

**Comment by Tratcher** [comment]
Done as part of https://github.com/aspnet/HttpAbstractions/issues/272
