### ISSUE TITLE
FormCollection does not seem to work

### ISSUE THREAD

**Issue by vncastanheira** [aspnet/HttpAbstractions#186]
Trying to use `FormCollection` on Post actions throws a `KeyNotFoundException`.
I made a [sample](https://onedrive.live.com/redir?resid=4893074DE3888A1B!67191&authkey=!ABhL2NrpCjG2B18&ithint=file%2czip) showing the error.

**Comment by davidfowl** [comment]
@vncastanheira could you push the sample to a github repository? That's more convenient than downloading the zip.

**Comment by vncastanheira** [comment]
There it is, the [repository](https://github.com/vncastanheira/FormCollection-Sample).

**Comment by Tratcher** [comment]
@ajaybhargavb

**Comment by PinpointTownes** [comment]
Taking `FormCollection` as a parameter is not supported (yet) by MVC 6: https://github.com/aspnet/Mvc/issues/979 :dancers: 
That said, it would be really trivial to add your own binder for `FormCollection`.

**Comment by vncastanheira** [comment]
Sure!
