### ISSUE TITLE
Contract for defining middleware class is too loose? (discussion)

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#188]
Coming from Katana, we decided to move away from the middleware base class for various reasons. The biggest problem with having a base class now is the inability to inject services on the middleware. Today this is the minimum needed to write a middleware class:

```C#
public class MyMiddleware
{
    public MyMiddleware(RequestDelegate next)
    {

    }

    public async Task Invoke(HttpContext context)
    {

    }
}
```

A few notes:
- Dependency Injection is supported (request services an app services)
- Invoke is a weird name but it was chosen because it mapped to the delegate calling pattern (RequestDelegate.Invoke). This middleware registration is basically `next => new MyMiddleware(next).Invoke`

```C#
public class MyMiddleware
{
    private readonly ILogger<MyMiddleware> _logger;

    public MyMiddleware(RequestDelegate next, ILogger<MyMiddleware> logger)
    {
        _logger = logger;
    }

    public async Task Invoke(HttpContext context, IRequestScopedThing thing)
    {
        _logger.WriteInformation(context.Request.Method + " " + context.Request.Path);
    }
}
```

Open questions:
- A base class? Probably not as DI wouldn't work well unless we did something like MVC with the `[Activate]` approach.
- Rename Invoke to `HandleRequest/ProcessRequest` something that doesn't look like a delegate innovation?

/cc @Praburaj @lodejard @Tratcher @Eilon @DamianEdwards

**Comment by Tratcher** [comment]
Mostly fixed by @mikaelm12, and we're fine with Invoke.
