### ISSUE TITLE
Rename Http.Core/Http packages

### ISSUE THREAD

**Issue by danroth27** [aspnet/HttpAbstractions#190]
Currently Microsoft.AspNet.Http.Core depends on Microsoft.AspNet.Http, which seems backwards.

**Comment by Tratcher** [comment]
Http contains the abstract HttpContext that most apps will reference directly, where Http.Core contains an actual implementation primarily referenced by Hosting. The naming of Http.Core could be better, but I think swapping it with Http would be detrimental to HttpContext.

**Comment by danroth27** [comment]
OK - I think we just need to come up with a better name for Http.Core. How about Http.Abstractions?

**Comment by danroth27** [comment]
How about Http -> Http.Abstractions?

**Comment by Tratcher** [comment]
I don't recommend it. Just about everything in the pipeline references HttpContext, so it should stay in the top level Http namespace and package for ease of discovery and usage.

**Comment by danroth27** [comment]
We can argue about the new names, (I'm fine with just renaming Http.Core to something else), but the current names have to change somehow. Everywhere else that I know of in Core is the thing that other stuff depends on, not the other way around. Think .NET Core vs .NET Framework.

**Comment by davidfowl** [comment]
Http.Impl yay java

**Comment by davidfowl** [comment]
@danroth27 Did you have any more thoughts on this?

**Comment by davidfowl** [comment]
We decided to swap the names:

- Http.Core - Abstractions
- Http - Implementations

/cc @glennc @muratg @lodejard

**Comment by Tratcher** [comment]
Put everything in the Http namespace.
- Http.Core - Abstract base classes, used to implement middleware
- Http - Implementations, only referenced by Hosting & tests
