### ISSUE TITLE
Need support for registering and disposing IDisposable types

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/HttpAbstractions#195]
Webapi had `RegisterForDispose()` as a `HttpRequestMessage` extension. We need something similar to that.

**Comment by Praburaj** [comment]
why not use scoped service in DI?

**Comment by Tratcher** [comment]
Related: https://github.com/aspnet/HttpAbstractions/issues/160

**Comment by rynowak** [comment]
> why not use scoped service in DI?

Where we have a need for this it's user-provided data. Ex: WebApiCompatShim with HttpResponseMessage. Defining services for this kind of thing doesn't scale is harder than what users are used to.

**Comment by davidfowl** [comment]
We were going to do this as well /cc @GrabYourPitchforks @loudej

**Comment by Tratcher** [comment]
I think this was handled by #160.
