### ISSUE TITLE
Need to expose ClientDisconnectedToken on HttpContext

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/HttpAbstractions#197]
Spoke with @davidfowl and @GrabYourPitchforks today about the fact the we only have an indication of `RequestAborted` and cannot separate it from a disconnection from the client.

In system.web world client disconnection does not necessarily mean request should stop processing, where abort does mean that.

When are are done with this features requiring cancellation token in web scenarios can automatically pick up the right cancellation token based on their scenario (example formatters will cancel for both tokens, but user code can make an explicit choice)

CC @HaoK

**Comment by Tratcher** [comment]
In what scenarios would you want a request to keep processing after the client has already disconnected?

**Comment by yishaigalatzer** [comment]
Apparently this was a common request in System.Web. Here is a scenario I can think of

The user uploaded an image/video to the server, the server (hmm unwittingly) is processing multiple resolution versions of the image in the request, and that might take some time. The client disconnects, but the image/video processing should still continue.

**Comment by Tratcher** [comment]
That scenario sounds like a long-running background task. It's not clear why you would hook that up to request events at all.

**Comment by davidfowl** [comment]
RequestAborted also now fires for client disconnects

**Comment by RehanSaeed** [comment]
@davidfowl What version of ASP.NET Core is that in?

**Comment by davidfowl** [comment]
It'll be in 2.0.0
