### ISSUE TITLE
How to get current context?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/HttpAbstractions#200]
What's the best way to get the current `HttpContext` from within an arbitrary class? I tried `serviceProvider.GetRequiredService<IContextAccessor<HttpContext>>().Value` which works when I call it from within an ASP.NET MVC request but doesn't seem to work from within a middleware's `Invoke` method (I just get `null`). I know middleware `Invoke` methods get passed the `HttpContext` as a parameter but I need to access it from separate standalone classes, so I can't just pass that down.

Context: I'm trying to update an existing library so it works on ASP.NET 5. Currently it uses TinyIoC which stores per-request objects in ASP.NET 4 `System.Web.HttpContext.Current.Items`. I thought the easiest way to get TinyIoC to deal with ASP.NET 5 would be to do something similar and store its components in a dictionary that's scoped so I can get it via `HttpContext.RequestServices.GetRequiredService`, but I need to figure out how to get to `HttpContext` from the TinyIoC code. I can't just update the code to use ASP.NET 5's dependency injection all the way down since it still needs to be backwards compatible.

**Comment by davidfowl** [comment]
I assume you're talking about this?:

https://github.com/grumpydev/TinyIoC/blob/8f57aca79f91d354772af30c53f18394c9a5c325/src/TinyIoC/TinyIoCAspNetExtensions.cs#L11

How do you wire up the tiny IOC integration. From what I know, TinyIOC is an embeddable (as source) IOC container that you can use in your application. Is that right? 

Maybe you pass an argument to `AsPerRequestSingleton()` flowing the service provider or even the IHttpContextAccessor (available in >= beta3) to that method.

**Comment by davidfowl** [comment]
I'm also assuming you're not trying to plug into the existing IOC support

**Comment by Daniel15** [comment]
For this particular project I'm trying to continue using the existing IoC container and just have some way of registering "per request" stuff similar to how the existing ASP.NET `HttpContext.Items` is used by TinyIoC.

I'm attempting to rewrite that `TinyIocAspNetExtensions` in a way that would work with ASP.NET 5: https://github.com/reactjs/React.NET/blob/asp5/src/React.AspNet5/HttpContextLifetimeProvider.cs. Basically I'm storing using a dictionary and using it in the same way the old code uses `HttpContext.Items`. The issue I'm having is that my `_appServiceProvider.GetRequiredService<IContextAccessor<HttpContext>>().Value` call is returning `null` in some cases (`IContextAccessor<HttpContext>` seems to be what's used in the latest released beta2, rather than `IHttpContextAccessor`).

I haven't seen a lot of documentation on ASP.NET 5 so I've been guessing my way through things so far :)

**Comment by Daniel15** [comment]
So it looks like `_appServiceProvider.GetRequiredService<IContextAccessor<HttpContext>>().Value` does work if I add `app.UseRequestServices()` (which registers `ContainerMiddleware`) before my middleware. Is that expected, or am I doing something wrong and is something going to break? 

I'm on beta2 which appears to be the latest version on NuGet.

**Comment by davidfowl** [comment]
Thats how it works with beta2. It's changed in beta3 which isn't public yet but will be soon.

I see a few interesting things:

- Are you trying to get web server files or application files? (https://github.com/reactjs/React.NET/blob/asp5/src/React.AspNet5/AspNet5FileSystem.cs). They are in separate locations in ASP.NET 5.
- It seems like you're bootstrapping TinyIOC from the existing DI system. Is that just the easiest way to port this application?

**Comment by davidfowl** [comment]
Also, tabs instead of spaces omg :smile:

**Comment by Daniel15** [comment]
> It seems like you're bootstrapping TinyIOC from the existing DI system.

TinyIoC is the only DI system in use in this case. This is a library so all the DI stuff is self-contained and only contains stuff used within the library itself. I find it's the best way to use dependency injection in a library without pulling in external dependencies or relying on the user to configure their own DI container.

I'm really glad ASP.NET 5 will have DI built-in since it means I can  just rely on that to be available, and stop bundling versions of TinyIoC in my libraries :)

> Also, tabs instead of spaces omg :smile:

I want to say "tabs are the only valid option" but I'll avoid it for now :p

**Comment by Daniel15** [comment]
For what it's worth, the existing IoC registrations are here:

https://github.com/reactjs/React.NET/blob/master/src/React/AssemblyRegistration.cs (core)
https://github.com/reactjs/React.NET/blob/master/src/React.Web/AssemblyRegistration.cs (ASP.NET-specific stuff)

**Comment by davidfowl** [comment]
This also looks suspect:

https://github.com/reactjs/React.NET/blob/asp5/src/React.AspNet5/ReactServiceCollectionExtensions.cs#L39
