### ISSUE TITLE
Rename AddEncoders to AddWebEncoders

### ISSUE THREAD

**Issue by Eilon** [aspnet/HttpAbstractions#204]
Came up in an API review - we were all confused as to what this method did until we saw the implementation. The name AddEncoders is just a bit too generic, and given that all these extension methods are in the same namespace, having more specific names seems like a good idea.

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Framework.WebEncoders/EncoderServiceCollectionExtensions.cs#L13

Also need to add doc comments to it.

**Comment by GrabYourPitchforks** [comment]
Included in PR https://github.com/aspnet/HttpAbstractions/pull/205.
