### ISSUE TITLE
HeaderDictionaryTypeExtensions typing issue

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/HttpAbstractions#209]
Just wondering, why does `HeaderDictionaryTypeExtensions.GetTypedHeaders(...)` force `HttpRequest` and `HttpResponse` when `RequestHeaders` (which `GetTypedHeaders` creates) only requires a `IHeaderDictionary`? This is proving to be a pain point since `HttpRequest.Headers`/`HttpResponse.Headers` are of type `IHeaderDictionary`, this means that I have I have to explicitly cast the result from `HttpRequest.Headers` to `RequestHeaders`, which makes using the extension method a real pain. 

The only reason why I can see why this might have been done is to avoid someone passing in Request headers where they should have passed in Response headers, but since the user has to cast, it doesn't really avoid that issue - maybe it could be argued you get an exception rather than the wrong results, but if this really is a worry, casting doesn't seem like the answer either.

**Comment by Tratcher** [comment]
I don't follow. httpRequest.GetTypedHeaders() and httpRequest.Headers provide different views into the headers. There shouldn't be any casting between the two types.

Can you provide some sample code showing your issue with the current APIs and another showing how you'd like to use it?

**Comment by avanderhoorn** [comment]
Sorry for not being 100% clear. But the following should show it:
```
// This would be my expectation, but it can't work because `Header` is of type `IHeaderDictionary` and `GetTypedHeaders` is needs it to be of type `RequestHeaders `
var request = ...;
var typedHeaders = request.Header.GetTypedHeaders();
```
So to work, one would need to do:
```
// This is what is needed to make it work and is really annoying to work with
var request = ...;
var typedHeaders = ((RequestHeaders)request.Header).GetTypedHeaders();
```

**Comment by Tratcher** [comment]
Why not just `request.GetTypedHeaders()`?
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Extensions/HeaderDictionaryTypeExtensions.cs#L15

I don't see an overload that will even make your second example compile.

**Comment by avanderhoorn** [comment]
Sorry my fault. For some reason when I was looking at that I kept thinking that the type that extension method wanted was `RequestHeaders` hence needing to cast. Sorry for the mistake!
