### ISSUE TITLE
Remove .Interfaces from the namespace in Microsoft.AspNet.Http.Interfaces

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#211]

**Comment by davidfowl** [comment]
We should do this as part of the API cleanup. Should we leave it as Http (that's actually cleaner) or add .Features back?

/cc @glennc @muratg @Tratcher

**Comment by Tratcher** [comment]
How is Http.Features any better than Http.Interfaces? By the convention it would be Http.Features in a package called Http.Features.Interfaces.

**Comment by Praburaj** [comment]
https://github.com/aspnet/HttpAbstractions/commit/d5e1b198dcbc2a6a5097f2ad28ceb1ab536208d5
