### ISSUE TITLE
Microsoft.AspNet.Http.Security introduces a class name clashing with an existing ADAL class

### ISSUE THREAD

**Issue by vibronet** [aspnet/HttpAbstractions#213]
Microsoft.AspNet.Http.Security contains a class named "AuthenticationResult", which happens to be a homonym of one of the two key classes in the ADAL library programming model(https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory). The class has been part of the ADAL model for the last 3 versions of the library.
It would be ideal if we could avoid this collision, as it forces the developer to use full names - diminishing the simplicity and ease of use of the model. For an example see https://github.com/tushargupta51/AspNet-Owin-Samples/blob/master/OAuthBearerClient/src/OAuthBearerClient/Controllers/TodoListController.cs

**Comment by davidfowl** [comment]
Do you have a suggestion for the name?

**Comment by HaoK** [comment]
AuthenticationResult is nuked now
