### ISSUE TITLE
Transition AllowedCharsBitMap back to a struct.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/HttpAbstractions#222]
Roslyn removed support for parameter-less constructors and this ended up causing issues so we transitioned the struct into a class to unblock the build. It should be moved back to be a struct when time permits.

**Comment by GrabYourPitchforks** [comment]
For reference, the Roslyn work item where the feature was cut: https://github.com/dotnet/roslyn/issues/1029
