### ISSUE TITLE
Remove dependency on DependencyInjection and instead use DependencyInjection.Interfaces on Http.Extensions

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#228]
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Extensions/project.json#L7

**Comment by Praburaj** [comment]
@davidfowl `Http.Extensions` seems to have dependency over `DependencyInjection` as it requires `ActivatorUtilities` to instantiate the middleware object in the `UseMiddleware` extension. Not sure if there is an alternate for this.

**Comment by Praburaj** [comment]
Merged https://github.com/aspnet/HttpAbstractions/commit/93deb0b440ad2a1b6ff40cd747d6c3de704e458e
