### ISSUE TITLE
ReadFormAsync throws exception if called on a request whose content type is not appropriate

### ISSUE THREAD

**Issue by Praburaj** [aspnet/HttpAbstractions#237]
I can't seem to trace the history as the project on when this behavior changed. I see Elm middleware broken due to this. 

https://github.com/aspnet/HttpAbstractions/blob/b77e9d2d9ccdf78e4cd0941af53aff08931b8374/src/Microsoft.AspNet.Http.Core/FormFeature.cs#L81

Instead of throwing an exception on requests whose content type is not FormContent type can we return an empty collection? Otherwise user code has to look something like this 

```
if (Request.HasFormContentType)
{
await Request.ReadFormAsync().. 
}
```

**Comment by Praburaj** [comment]
@glennc @GrabYourPitchforks @Tratcher

**Comment by Tratcher** [comment]
This was the intended design and it has been this way since at least my last round of feature work. Returning an empty form would be misleading.

**Comment by Praburaj** [comment]
I see. Returning null also will not make much difference to the user code. Probably I can fix the Elm middleware.
