### ISSUE TITLE
QueryHelpers.AddQueryString should support # in the URL

### ISSUE THREAD

**Issue by sornaks** [aspnet/HttpAbstractions#238]
Currently, if you try to add a query string like `foo=bar` to `http://someurl.com/hello#world` it returns `http://someurl.com/hello#world?foo=bar` which should actually be `http://someurl.com/hello?foo=bar#world`

**Comment by Eilon** [comment]
Feel free to assign to @sornaks when triaging.

**Comment by muratg** [comment]
@sornaks are you working on this for Beta 6?

**Comment by sornaks** [comment]
@muratg - yes. sent a PR.

**Comment by sornaks** [comment]
Checked in. https://github.com/aspnet/HttpAbstractions/commit/25ea93de9e03f1b0be8922bf727163f8ac3be499

**Comment by brockallen** [comment]
Would it make more sense to have a separate API called AddHashFragment?

**Comment by Tratcher** [comment]
@brockallen We're not trying to add a hash, we're trying to append query params to a url that may already have a hash.

**Comment by brockallen** [comment]
Ah, got ya.
