### ISSUE TITLE
Test failure on mono: Microsoft.AspNet.Http.Core.FormFeatureTests.ReadFormAsync_MultipartWithFieldAndFile_ReturnsParsedFormCollection [FAIL]

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#246]
https://travis-ci.org/aspnet/HttpAbstractions/builds/57113537

Looks like a functional issue

/cc @Tratcher @Praburaj

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/blob/dev/test/Microsoft.AspNet.Http.Core.Tests/FormFeatureTests.cs#L100

I assume Git is setup to download files using OS specific line endings? I think that's changing the new lines in these multi-line C# strings. Multipart requires CRLF, Windows uses CRLF, but Linux uses LF (or CR?).

Recommended fix: Don't use multi-line C# strings when the new line characters actually matter.
