### ISSUE TITLE
Move IServerInformation out of HttpAbstractions

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#255]
Server implementations should have to depend on Microsoft.AspNet.Http https://github.com/aspnet/Hosting/blob/f337f8cd04459e541431df04d859b705f3d2f6f7/src/Microsoft.AspNet.Hosting.Server.Interfaces/project.json#L5. Today they do because of this single type.

Let's decide where to put this type. Maybe Http.Interfaces?

/cc @Tratcher @lodejard @Praburaj

**Comment by Tratcher** [comment]
Putting it in Http.Interfaces would introduce a dependency from Http to Http.Interfaces. Unless we removed it from IApplicationBuilder and put it back in the Properties collection with extension methods like before.

Or just drop the interface from IApplicationBuilder and go back to `object`. You have to downcast it to do anything useful anyways.

**Comment by davidfowl** [comment]
I was thinking the object route was probably best as well.

**Comment by Tratcher** [comment]
Lets draw it out on the whiteboard.
