### ISSUE TITLE
SessionCollectionExtensions.SetInt and GetInt don't follow the design guidelines

### ISSUE THREAD

**Issue by justinvp** [aspnet/HttpAbstractions#256]
[`SessionCollectionExtensions` has the following two methods](https://github.com/aspnet/HttpAbstractions/blob/114d834876d91fffb42ea643044b434e85363411/src/Microsoft.AspNet.Http.Extensions/SessionCollectionExtensions.cs#L11-L31):

```c#
public static class SessionCollectionExtensions
{
    public static void SetInt(this ISessionCollection session, string key, int value);
    public static int? GetInt(this ISessionCollection session, string key);

    ...
}
```

These method names do not follow the [Framework Design Guidelines](https://msdn.microsoft.com/en-us/library/vstudio/ms229045(v=vs.110).aspx):

> √ **DO** use a generic CLR type name, rather than a language-specific name, in the rare cases when an identifier has no semantic meaning beyond its type.
> 
> For example, a method converting to `Int64` should be named `ToInt64`, not `ToLong` (because `Int64` is a CLR name for the C#-specific alias `long`).

These methods should be named `SetInt32` and `GetInt32`.

/cc @terrajobst

**Comment by Eilon** [comment]
Agreed.

**Comment by davidfowl** [comment]
@justinvp you gonna send a PR ?

**Comment by justinvp** [comment]
Sure. I'll get to it later this week.
