### ISSUE TITLE
Explicit versioning for KoreBuild in build.sh?

### ISSUE THREAD

**Issue by ryan1234** [aspnet/HttpAbstractions#259]
I'm stuck on beta3 for now and wanted to debug something around Http.Core. I tried to build the master branch on Linux (build.sh), and this line https://github.com/aspnet/HttpAbstractions/blob/master/build.sh#L26 got me stuck.

Without explicit versioning it pulls beta5 and the new names (dnx, dnu, etc.) while the rest of the build script wants kvm.sh.

I changed the line to:

```
mono .nuget/nuget.exe install KoreBuild -ExcludeVersion -o packages -nocache -pre -version 0.2.1-beta3
```

and everything built great. Is there some other/better way to do this?

**Comment by davidfowl** [comment]
That's a good suggestion. Can you file this on https://github.com/aspnet/Universe. We should do this when we make release branches.
