### ISSUE TITLE
Move FormCollection to WebUtilities

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#261]
MVC currently takes a dependency on Http.Core because of it and it shouldn't have to.

**Comment by Tratcher** [comment]
You need to consider the full object graph. You would have to move FormCollection, IFormCollection, FormFileCollection IFormFileCollection, ReadableStringCollection, and IReadableStringCollection.

**Comment by davidfowl** [comment]
Sure, let's find a suitable place for those types then.

**Comment by Tratcher** [comment]
The interfaces are in Http and the collections are in Http.Core. Moving the interfaces will require adding dependencies to Http.

**Comment by davidfowl** [comment]
Maybe we need to move them into a lower package. What does the dependency graph look like today.

**Comment by Tratcher** [comment]
I noticed that several Authentication packages had a similar dependency.

**Comment by davidfowl** [comment]
@muratg beta6?

**Comment by muratg** [comment]
Any ideas where this should go?  We probably should not complicate rest of the dependency chain too much in order to remove Http.Core dependency from MVC.  Putting this in Beta 6 for now.

**Comment by muratg** [comment]
@Tratcher @davidfowl Let's discuss this in today's design meeting and reach a decision.

**Comment by Tratcher** [comment]
@rynowak, @davidfowl & co say we need to refactor MVC instead.

**Comment by rynowak** [comment]
Cool, let's catch up around this soon. The thing that we're using this for is to create an empty `FormCollection` in model binding when there's no form data, but the user declares an `IFormCollection` parameter.

**Comment by davidfowl** [comment]
@rynowak I have a PR ready for this change and I actually think that's bad behavior but lets discuss on the PR

**Comment by muratg** [comment]
Fowler, please feel free to close as the decision in the design meeting was wontfix'ing this. Since you are still discussing with Ryan, keeping it open.

**Comment by muratg** [comment]
@davidfowl If this is to be changed, please remove wontfix label. Otherwise I'll close this one soon.

**Comment by muratg** [comment]
Closing.
