### ISSUE TITLE
Can't access temporary directory in Linux when running an Asp.Net 5 Application

### ISSUE THREAD

**Issue by felipepaixao** [aspnet/HttpAbstractions#262]
Having trouble when i asp.net 5 try to access temp folder.
running under Linux  .beta3

> An unhandled exception occurred while processing the request.

> DirectoryNotFoundException: Exception of type 'System.IO.DirectoryNotFoundException' was thrown.
> Microsoft.AspNet.Http.Core.BufferingHelper.get_TempDirectory () [0x00000] in <filename unknown>, line 0

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/issues/168

**Comment by davidfowl** [comment]
This was fixed
