### ISSUE TITLE
ApiReview: IApplicationBuilder & extensions

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#265]
Remove IApplicationBuilder Properties & Server setters.
Remove Run extensions that take services.
Remove Map string overload (and add implicit conversion between PathString & String).
Remove Map PredicateAsync support.

**Comment by Tratcher** [comment]
@muratg @davidfowl @lodejard What about the Use extensions that take services? Those are still there.
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Abstractions/Extensions/UseExtensions.cs#L37

**Comment by brockallen** [comment]
Were these removed just to reduce the API surface area and/or for simplicity, or was there some larger reason?

**Comment by davidfowl** [comment]
Simplicity and usability.
