### ISSUE TITLE
ApiReview: Move WebSocket APIs to HttpContext.WebSockets

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#267]
```
WebSocketRequestedProtocols { get; }
AcceptWebSocketAsync()
AcceptWebSocketAsync(string subProtocol)
```

But not `IsWebSocketRequest { get; }`

**Comment by Tratcher** [comment]
I think it makes sense to also move IsWebSocketRequest in with everything else. Just accessing HttContext.WebSockets doesn't imply any operations. Compare to HttpContext.Authentication.

**Comment by davidfowl** [comment]
context.WebSockets.IsWebSocketRequest? /cc @lodejard

**Comment by Tratcher** [comment]
Also do with #273 for IWebSocketAcceptContext.
