### ISSUE TITLE
ApiReview: How can we efficiently represent items that may be either singular or plural

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#268]
Multiple data structures use pairs of `<string, string[]>`, however it is very common for the array to only contain one element. Is there a more efficient way to represent this?

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/HttpAbstractions/issues/240 ?

**Comment by davidfowl** [comment]
Yes this be a dupe :smile:
