### ISSUE TITLE
Use X509Certificate2 instead of X509Certificate

### ISSUE THREAD

**Issue by blowdart** [aspnet/HttpAbstractions#279]
X509Certificate2 is preferably as it adds properties, rather than methods to get common fields (like valid from, valid to, subject etc.) In addition it provides Authority Key ID and Key usage, (key usage being especially important).

X509Certifcate2 subclasses X509Certificate should it should be an easy enough upgrade,.

**Comment by davidfowl** [comment]
@Tratcher wasn't this done?
