### ISSUE TITLE
Setting Encoding on MediaTypeHeaderValue loses all configuration when getting.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/HttpAbstractions#284]
```C#
var encoding = = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true);
var header = new MediaTypeHeader("application/json") { Encoding = encoding; }

var returnedEncoding = header.Encoding; // This will have emit UTF8 identifier to true and will print out the BOM
```

**Comment by Tratcher** [comment]
By design, none of that information is encoded in the header, just the charset.

**Comment by kichalla** [comment]
I too came across this issue now. As part of fixing the issue https://github.com/aspnet/Mvc/issues/2411, we would like to expose MediaTypeHeaderValue, but any setting related to encoding is lost as we do not preserve the supplied encoding.

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/MediaTypeHeaderValue.cs#L76

/cc: @Eilon @rynowak

**Comment by Tratcher** [comment]
These header value types are strict representations of the HTTP headers. The Encoding property is just a convenient way to get or set the charset parameter.  If this is misleading then I will remove the property.

**Comment by pranavkm** [comment]
@kichalla see https://github.com/aspnet/Mvc/issues/2408#issuecomment-94517130. We might have to solve this in Mvc \ create a writer in some common code base that can be used in lieu of using `StreamWriter`. That said, I think formatters are unaffected by this today (might have to check)

**Comment by kichalla** [comment]
@pranavkm : I am a bit unclear about your comment. Are you referring to the part after an encoding is selected?

**Comment by pranavkm** [comment]
The preamble behavior for UTF8 was a problematic property - we use a `StreamWriter` to write out Razor views which renders the preamble if the `Encoding` specifies one. Round-tripping `Encoding` using `MediaTypeHeaderValue` resets the preamble behavior. 

Are there other properties on `Encoding` that need to be preserved between round trips? If not, we probably shouldn't care about preserving the actual `Encoding` instances.
