### ISSUE TITLE
app.UseBrowserLink can't be used after Http and Http.Core swap

### ISSUE THREAD

**Issue by matthewDDennis** [aspnet/HttpAbstractions#287]
Since this refactoring, I have to comment out app.UseBrowserLink() in order to compile.  I get the following error
    Severity	Code	Description	Project	File	Line
    Error	CS7069	Reference to type 'IApplicationBuilder' claims it is defined in 'Microsoft.AspNet.Http',  but it could not be found	Web.DNX 4.5.1	C:\Users\matthew.OFFICE\Documents\Visual Studio 2015\Projects\CpRefactorArticles\Web\Startup.cs	80

**Comment by davidfowl** [comment]
That's expected. We're making big API changes in beta5 (after API reviews). So beta4 and beta5 packages cannot be mixed.

**Comment by matthewDDennis** [comment]
I am using beta 5 with vs15 rc.
On Apr 19, 2015 3:34 PM, David Fowler <notifications@github.com> wrote:That's expected. We're making big API changes in beta5 (after API reviews). So beta4 and beta5 packages cannot be mixed.

**Comment by Tratcher** [comment]
This change just went in last week (Tuesday?) so I don't know if the browserlink folks have even picked it up yet.  Even if they have, you'll need the absolute latest version of all the beta5 packages.

**Comment by davidfowl** [comment]
Right, plus there's no ci builds of browser link.
