### ISSUE TITLE
How to work with Uri and QueryString in ASP.NET 5

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/HttpAbstractions#288]
Previously in old MVC and WebApi Request types (`HttpRequestBase` and `HttpRequestMessage`) had property `QueryString` of type `NameValueCollection`. It represented key-value pairs in request's query string. Now in AspNet5 `HttpRequest` has `QueryString` property which type is `QueryString` struct. But it's just a wrapper around a string value. It doesn't have values, indexer, IEnumerable. Nothing.

How is it supposed to work with values in QS?

Also similar question about working with URI. Previously we had `HttpRequestBase.Url` and `HttpRequestMessage.RequestUri` of type `System.Uri`. Now just strings (PathBase, Path, QueryString props in HttpRequest). What's wrong with System.Uri? Why is it abandoned?

Another type I'm missing is HttpUtility. Especially UrlEncode/UrlDecode methods.

**Comment by Tratcher** [comment]
Look at HttpRequest.Query for the parsed query.

We've found that System.Uri is better adapted to client scenarios where you are addressing a server. On the server you usually work with the individual components, not the combine string.

UrlEncode is available here:
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Framework.WebEncoders.Core/UrlEncoder.cs

**Comment by evil-shrike** [comment]
What package should I install for WebEncoders?

**Comment by evil-shrike** [comment]
@Tratcher thanks for the answer
Also let me ask a related question (to QS handling). 
In old WebApi I had logic for combining key-value pairs from QS and body (it's for working around url length limit in browsers).
So I had something like this:
```
		public static NameValueCollection ParseQuery(this HttpRequestMessage request)
		{
			NameValueCollection collection = request.RequestUri.ParseQueryString();
			if (request.Properties.ContainsKey(HttpPropertyKey.IncludePostDataInQuery))
			{
				Task<NameValueCollection> task = request.Content.ReadAsFormDataAsync();
				task.Wait();
				collection.Add(task.Result);
			}
			return collection;
		}
```
NOTE: `IncludePostDataInQuery` flag in Properties collection I put in some action filter where I checked for the current HttpRequest's  method and current contoller's supported methods (if the controller support POST and currently we're processing POST then put this flag into the request).

So actually in this extension method I get params from QS and then add params from request body.

In AspNet5 for the first part I should use `Query` - ok: 
`IReadableStringCollection collection = request.Query;`

What for the other part? How to read QS-like params from request body? `request.Body` is just a `Stream`.

**Comment by Tratcher** [comment]
See HttpRequest.ReadFormAsync.

**Comment by evil-shrike** [comment]
Ok, thanks.
UrlEncoder isn't in beta3 yet, right?
