### ISSUE TITLE
ApiReview: Rename Microsoft.AspNet.Builder namespace

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#289]
@davidfowl Please don't just put it all into the Http namespace.

**Comment by HaoK** [comment]
Are the only two things that live in this namespace IApplicationBuilder and ApplicationBuilder?

**Comment by Tratcher** [comment]
And all of the IApplicationBuilder extension methods. Those are what I'd like to keep separate from Http.

**Comment by HaoK** [comment]
Microsoft.AspNet.Application?
