### ISSUE TITLE
DefaultHttpResponse.Challenge has parameters in different order than SignIn or SignOut

### ISSUE THREAD

**Issue by brentschmaltz** [aspnet/HttpAbstractions#291]
public override void Challenge(AuthenticationProperties properties, string authenticationScheme)
public override void SignIn(string authenticationScheme, [NotNull] ClaimsPrincipal principal, AuthenticationProperties properties)
public override void SignOut(string authenticationScheme, AuthenticationProperties properties)

placement of authenticationScheme should be consistent.

**Comment by Tratcher** [comment]
Yes
