### ISSUE TITLE
Add net45 targets for HttpAbstractions

### ISSUE THREAD

**Issue by mkosieradzki** [aspnet/HttpAbstractions#301]
I have been asked by @Eilon to post requests for adding .NET 4.5 support for useful packages in proper repos (https://github.com/aspnet/Home/issues/532). 

http://blogs.msdn.com/b/webdev/archive/2014/11/14/katana-asp-net-5-and-bridging-the-gap.aspx, http://katanaproject.codeplex.com/wikipage?title=roadmap - from this articles I understand all or almost all HTTP abstractions packages should be made available to .NET 4.5, but for example here in the framework sections there is only dnx451 and dnxcore50: (https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Abstractions/project.json).

**Comment by Tratcher** [comment]
Sorry, that's not what I meant when I wrote those.  When discussing the full framework I was referring to dnx451, not net45.  As @davidfowl said, dnx adds important runtime capabilities on top of the .NET 4.5 API set. We have already added net45 support to the packages we planned on (e.g. https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/project.json, https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Framework.WebEncoders/project.json).

That said, feel free to request net45 support in other packages that you think are useful. Like @davidfowl said, we don't want to try supporting the whole stack on net45. I think the current criteria is that a package needs to be reusable as an independent library outside of the normal stack, like the two linked above.  Some of the packages in HttpAbstractions might qualify, however I wouldn't expect any of he middleware packages to qualify (e.g. StaticFiles).

**Comment by mkosieradzki** [comment]
@Tratcher 
Thanks a lot for clarification. I am migrating large project to ASP.NET 5 and Service Fabric and it's quite difficult to find out what will and what will not be supported at final realease.

The most difficult part of migration is trying to temporary retain some compatibility with System.Web and ASP.NET web forms and to be able to use some new features like MVC6, ServiceFabric, and sub-hosting ASP.NET5 applications inside.

I am trying to put all the puzzles together basing on some blog posts, like yours.

Scott Guthrie has written:
"If you don't want to have to update your app you can instead run ASP.NET 5 applications on the full .NET Framework (version 4.5.2 and above).  When doing this you have access to the complete set of .NET Framework APIs. Your existing applications and libraries will work without modification on this runtime."

That all sounds beautiful, but at the moment there are many troubles in:
1. MVC6 run only in DNX451/DNXCORE and depends on HttpAbstractions mentioned here.
2. HttpAbstractions run only in DNX451/DNXCORE
3. ServiceFabric preview1 is .NET 4.5 based and cannot run in an obvious way "MVC6", but also cannot run MVC5 which is not self-host compatible and ServiceFabric is obiously non-IIS compatible.

I see two solutions:
1. Provide ability to host ASP.NET 5 application inside .NET 4.5 application with possiblity to provide at least in-process/hopefully in-appdomain communication between host and application. AFAIK it should be possible.
2. Expose all kinds of interfaces, to .NET4.5.

Misunderstanding on specifics of your blog post suggested something more towards 1. But after clarification and all statements made by @davidfowl  I understand that there is a Managed Host under development that will allow to address multiple scenarios without: tainting .NET4.5 with ASP.NET5 and vice versa.

In that situation it definitely makes no sense to expose those abstractions interfaces and I will open issue to expose https://github.com/aspnet/dnx/tree/dev/src/Microsoft.Framework.Runtime.Hosting to .NET 4.5 ;).
