### ISSUE TITLE
What is the equivalent of HttpResponse.ClearContent() and HttpResponse.SuppressContent in HttpAbstractions?

### ISSUE THREAD

**Issue by rajajhansi** [aspnet/HttpAbstractions#307]

**Comment by Tratcher** [comment]
There isn't any yet. Both of these members deal with response buffering which has not been implemented yet in ASP.NET 5.  Here's the related work item:
https://github.com/aspnet/Hosting/issues/49

**Comment by rajajhansi** [comment]
@Tratcher Thank you for the quick reply. I'm porting an ASP.NET MVC5 application into MVC6 and it uses VirtualPathUtility to get the absolute path for paths starting with "~". Are there any equivalents to Request.Url.AbsolutePath and Request.Url.AbsoluteUri  ?

**Comment by davidfowl** [comment]
@rajajhansi Please don't ask unrelated questions on bugs that you filed. Treat each new question as a separate issue. If you don't know where to file it, open it on aspnet/Home.

**Comment by rajajhansi** [comment]
@davidfowl, ??? It was a question and not a follow up to any bug. Please understand that I didn't file any bug related to my question. Since HttpResponse belongs to HttpAbstractions, I asked the question in this project.

**Comment by rajajhansi** [comment]
@davidfowl, I got it.  I can open another issue for the 2nd question.
