### ISSUE TITLE
Are there any equivalents to Request.Url.AbsolutePath and Request.Url.AbsoluteUri ?

### ISSUE THREAD

**Issue by rajajhansi** [aspnet/HttpAbstractions#308]

**Comment by Tratcher** [comment]
We found that AbsoluteUri was not usually the correct value or format for what people needed. Most of the time you need just some parts of the Uri.

From your prior post: `I'm porting an ASP.NET MVC5 application into MVC6 and it uses VirtualPathUtility to get the absolute path for paths starting with "~".`

@pranavkm, How did you decide to handle "~" in MVC?

**Comment by pranavkm** [comment]
At this point, we simply trim the `~` and interpret it as `ApplicationBasePath`.

**Comment by rajajhansi** [comment]
@Tratcher @pranavkm , thanks guys. I'm currently injecting IApplicationEnvironment using [Activate] to access the ApplicationBasePath. :) This is ugly. In some places, I construct the IOptions<MyFeatureService> and add properties for anything tat depends on IApplicationEnvironment, Configuration etc. Is this the correct way?

**Comment by davidfowl** [comment]
@rajajhansi What are you actually doing?
