### ISSUE TITLE
Rename IHttpConnectionFeature to ITcpConnectionFeature

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#309]
It's not an http connection, it's a TCP connection. Similarly we have an ITlsConnectionFeature.

**Comment by Tratcher** [comment]
Also rename LocalIpAddress to LocalIPAddress to match naming guidelines. Same for RemoteIpAddress.

**Comment by davidfowl** [comment]
Ugh I'm not so sure about this naming...

**Comment by JamesNK** [comment]
IPAddress is the standard in .NET land https://msdn.microsoft.com/en-us/library/system.net.ipaddress%28v=vs.110%29.aspx

**Comment by davidfowl** [comment]
I mean TCP vs Http

**Comment by davidfowl** [comment]
I actually thing we shouldn't do this. HttpConnection sounds fine even though it's not 100% accurate.
