### ISSUE TITLE
Remove first class IServiceProvider properties

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#313]
We should remove: 
- IApplicationBuilder.ApplicationServices
- HttpContext.ApplicationServices
- HttpContext.RequestServices

We should make the providers available via HttpContext.Items with specific keys. Reason being that only framework pieces need access to the service provider so that we can pick composition roots for user code to plug into. This will encourage us to make those points more obvious and help clean up some of our own code.

**Comment by rynowak** [comment]
This is going to **wreck** action results

**Comment by Tratcher** [comment]
This shouldn't go in Items, it should remain a Feature. You can drop the HttpContext properties and access it via GetFeature instead.

**Comment by davidfowl** [comment]
@Tratcher sure

**Comment by Tratcher** [comment]
IApplicationBuilder.ApplicationServices is used frequently.

HttpContext.ApplicationServices is only referenced once outside of tests:
https://github.com/aspnet/Diagnostics/blob/3fa5dee2d7f377d57e75fbb0d328cd26b6ff093a/src/Microsoft.AspNet.Diagnostics/Views/BaseView.cs#L56

HttpContext.RequestServices is used very frequently, especially in MVC.

**Comment by Tratcher** [comment]
`httpContext.GetFeature<IServiceProvidersFeature>().RequestServices`
