### ISSUE TITLE
Non-english characters are encoded

### ISSUE THREAD

**Issue by danroth27** [aspnet/HttpAbstractions#315]
Reported as https://github.com/aspnet/Razor/issues/409 by @anfomin

Every non-english character is encoded. For example:
```razor
@{
	string s = "Добрый день"; // this is Russian text
}
@s
```

The result is something like:
![2015-05-27 9 55 55](https://cloud.githubusercontent.com/assets/1905503/7829109/e6386e18-0456-11e5-8b52-408c3a15dc31.png)

----

Characters displayed correct, but page size increased significantly :-1: Also MVC 5 rendered unicode symbol correctly in HTML source.

**Comment by blowdart** [comment]
Actually MVC 5 would have done the same if you'd switched to AntiXSS as the encoder. 

By design.

**Comment by Tratcher** [comment]
What API are you complaining about?

**Comment by Tratcher** [comment]
Ah,  IHtmlEncoder

**Comment by dougbu** [comment]
@blowdart however in MVC 5 it was a _choice_ and the default HTML encoder provided readable source or a reasonable size.

**Comment by blowdart** [comment]
The standard Russian characters should have been safe listed with the new encoder.
You'll need to examine the whitelist generation to see why they're not.

**Comment by dougbu** [comment]
@blowdart from the `HtmlEncoder` source, the default escaped range is `UnicodeRanges.BasicLatin` which has this convenient comment:
``` c#
/// A <see cref="UnicodeRange"/> corresponding to the 'Basic Latin' Unicode block (U+0000..U+007F).
```

Are you suggesting a different default?

**Comment by blowdart** [comment]
I though it was changed, but ok. And no, let's be honest, I'd encode *everything* by default to avoid certain utf7 badness. Customer can use the Default property to widen their safe list as needed.

**Comment by anfomin** [comment]
Every character encoding brings another problems. Sometimes we use `<script>` generation in razor pages like:

```javascript
<script>
	$(function() {
		var someVariable = "@thisIsDotNetVariable";
		// other code goes here
	});
</script>
```

So JavaScript will not decode this value and will display unicode numbers.

**Comment by blowdart** [comment]
Don't do that for javascript. It's simply wrong.

@ encoding is HTML encoding. It's not JavaScript encoding. Using HTML encoding inside javascript means some of the characters that can cause javascript injection are not encoded.

The most full proof way to inject variable values into javascript is to have a div or span or other tag, and use a data attribute - using @ encoding there is correct, and you're protected. Then you'd retrieve it within the javascript.

**Comment by anfomin** [comment]
@blowdart OK, this it good explanation not to use `@` with JS. But encoded-text increase page size 7 times (each character converted into 7). I do not think this is good behavior by default.

Also there is no attack can be done using Russian or any other language characters so they do not require HTML encoding. This characters do not have any "special" behavior compared to english ones.

**Comment by blowdart** [comment]
Actually you can attack via some characters depending on the underlying page encoding and other badness. Utf7 is a great example of this - http://openmya.hacker.jp/hasegawa/public/20071107/s6/h6.html?file=datae.txt has some details.

We're discussing internally what we want to do - but the encoders are used by things other than razor, and defaulting to encoding everything over and above ASCII is what makes it 100% safe for the other things to consume, so I'm not minded to change the default encoder configuration. With gzip compression which most servers support these days the actually transport size increase shouldn't be that painful, but I realise if you're not in a default English speaking country it's probably not a cost you want to take (being a Brit, it annoys me when we end up assuming everything speaks US english).

You could just whitelist everything yourself, either by

    HtmlEncoder.Default = new HtmlEncoder(UnicodeRanges.All);

before the encoder gets registered in DI, or via

    serviceColl.AddWebEncoders(o => { 
        o.CodePointFilter = new CodePointFilter(UnicodeRanges.All);
    });

If you wanted to narrow it down, the you can create ranges and pass them into the encoder which match the Unicode code charts which contain the characters you need (Unicode doesn't do languages, so you will need to mix and match - you can find the code charts at http://www.unicode.org/charts/)

**Comment by dougbu** [comment]
Note setting `HtmlEncoder.Default` is likely not what you want. That changes only the HTML encoder, leaving the JavaScript and URL encoders with their (ASCII) defaults.

Recommend
``` c#
  services.Configure<WebEncoderOptions>(options => new CodePointFilter(UnicodeRanges.All));
```
because (today) nothing configures `WebEncoderOptions` but much of the system adds the web encoders.

**Comment by Tratcher** [comment]
@blowdart Is there any action required here? This sounds all by design.

**Comment by blowdart** [comment]
By design. The MVC team wanted to change it somewhat, but never came up with a suitable suggestion,

**Comment by penihel** [comment]
I have the same problem with accents (pt-BR). In previous versions this was not a problem.

I think to a final version, native, pure and simple MVC should accept this kind of character without that develop change any settings.

More than a technical issue, for me it is a matter of attention to non-English developers

**Comment by kerryjiang** [comment]
The api was changed, the issue can be walked abound by the code:

```
services.Configure<WebEncoderOptions>(options => 
{
      options.TextEncoderSettings = new TextEncoderSettings(UnicodeRanges.All);
});
```

**Comment by miloush** [comment]
I agree that `BasicLatin` is a horrible default. Not only it increases the file size and overhead (don't we expect the core to run on small devices too?) but also makes the page illegible to humans.

**Comment by Cuiqs76** [comment]
where is the WebEncoderOptions? @kerryjiang

**Comment by Eirenarch** [comment]
This default is absurd. In addition it is not even clear to me if using UnicodeRanges.All is safe or I'd better list a couple of more popular Unicode ranges like Cyrillic, GreekandCoptic, Hebrew and Arabic and leave the rest encoded
