### ISSUE TITLE
Misleading error information on middleware

### ISSUE THREAD

**Issue by Bartmax** [aspnet/HttpAbstractions#321]
when having a custom middleware before (for example) mvc, when there's a mvc error, the error message is misleading because it point to your await next(context) line on your middleware.

error example
```
System.ArgumentNullException
Value cannot be null.
Parameter name: source

c:\Repos\Community\Bartmax\HtmlMinifier\src\HtmlMinifier.MiddleWare\HtmlMinifierMiddleware.cs

Line 24:                  await _next(context);
```

and down the stack I can see an error in a cshtml file.

```
at Asp.ASPV__Views_Test_Index_cshtml.<ExecuteAsync>d__17.MoveNext() in /Views/Test/Index.cshtml:line 7
```

Is there anyway to improve this?
I understand why this is happening but I think it's confusing to point a mvc error to a middleware that has nothing to do with the error.

**Comment by Tratcher** [comment]
Is it just showing the sources for the first stack frame where it can find symbols/sources? I.e. if you pull down the MVC symbols/sources does it start showing the location of the error more accurately?

**Comment by Bartmax** [comment]
@Tratcher yes, you are right. I'm not using MVC sources, I'm using custom middleware authored by myself. I don't think there's something one can do about it.

**Comment by davidfowl** [comment]
Can you provide a repro project?

**Comment by Bartmax** [comment]
No, I tried, but I cannot repro using beta4.

This was happening to me on beta3 (unfortunately I don't have the exactly state where this was happening), maybe this is handled differently now ?
