### ISSUE TITLE
Uri.UriSchemeHttps missing on coreclr

### ISSUE THREAD

**Issue by Bartmax** [aspnet/HttpAbstractions#322]
The const "https" is no longer on `Uri.UriSchemeHttps`.
Looking at the code I see there's a "https" const but it's internal.

Is this defined for consumers to use anywhere? Will be?

**Comment by muratg** [comment]
This bug be filed on https://github.com/dotnet/corefx/ instead?

**Comment by Tratcher** [comment]
Uri.UriSchemeHttps is not coming back. I don't know if we'd expose our own constant for it.

**Comment by davidfowl** [comment]
Personally I think it's pointless. The string literal `"https"` is fine.

**Comment by Bartmax** [comment]
perfect! thanks.
