### ISSUE TITLE
Revisit Abstractions -> Features layering

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#325]

**Comment by Tratcher** [comment]
Any specific concerns?

**Comment by davidfowl** [comment]
Unnecessary coupling in order to reuse types. We just need to validate that the people using HttpAbstractions, always want the features. I'm not sure about that yet.

**Comment by Tratcher** [comment]
In theory you can't implement Abstractions without Features, even if there is not a direct dependency. See `GetFeature<T>()`

**Comment by davidfowl** [comment]
It's not about implementing Abstractions, it's about the consumers of Abstractions getting features by default.

**Comment by darrelmiller** [comment]
Do you mean like this?
public abstract IReadableStringCollection Cookies { get; set; }

Why must an implementer implement Cookies? Why is Cookies special?  Why not Authorization? Or UserAgent?
As an implementer am I required to duplicate Cookies in Headers? Do they need to be kept in sync?  There are many questions introduced by this overlap.

In a similar vein, why is it required for an HttpAbstraction to implement application/x-www-form-urlencoded handling?  

public abstract bool HasFormContentType { get; }
public abstract IFormCollection Form { get; set; }
public abstract Task<IFormCollection> ReadFormAsync(CancellationToken cancellationToken = new CancellationToken());

Doesn't this smell of an architectural layering issue if it is necessary for these properties to be in the core HTTP abstraction?

Also, in HttpResponse, how are the redirect methods supposed to be supported?  How do we know whether a temporary redirect is a 302 or a 307?   Or whether the permanent redirect is a 301 or 308?  And why is location a string and not a URI?

**Comment by davidfowl** [comment]
Nope, not like that. That sounds like you have a problem with the general shape of the abstractions (whic I don't :smile:). I'm talking about the feature interfaces being coupled to the abstractions themselves.

This abstractions are a mix of things we used to have on the OwinContext and System.Web http context. Sure it's not pure but that's not the point of it. It's about convenience. Also, if you look around at other frameworks, there are usually a set of core things that are elevated to be first class.
