### ISSUE TITLE
Add support for fragment in HttpRequest

### ISSUE THREAD

**Issue by javiercn** [aspnet/HttpAbstractions#33]
Currently there's no way to get to the fragment in an HttpRequest

**Comment by smbecker** [comment]
@Eilon, my particular usage is to redirect the client to a known fragment. This has to be more common as more and more people are using SPA. Currently, when I try to create a `PathString` with a fragment in the URI, it gets encoded, which is not really what I want.

**Comment by Tratcher** [comment]
When generating redirects do not put the fragment into the PathString, append the fragment after the path like this: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/UriHelper.cs#L24

**Comment by smbecker** [comment]
Ah, missed that little gem. Thanks
