### ISSUE TITLE
Allow Null params to middleware constructor?

### ISSUE THREAD

**Issue by kspearrin** [aspnet/HttpAbstractions#331]
I want to do this from `Startup.cs`:

```
app.UseMiddleware<MyMiddleware>( foo );
```

`MyMiddleware` looks like this:

```
public class MyMiddleware
{
    private readonly RequestDelegate m_next;

    public MyMiddleware( RequestDelegate next, Foo foo )
    {
        m_next = next;
        // use foo
    }

    public async Task Invoke( HttpContext httpContext )
    {
        await m_next( httpContext );
    }
}
```

Yet I keep getting:

> System.InvalidOperationException
> Unable to locate suitable constructor for type 'MyMiddleware'. Ensure the type is concrete and all parameters are accepted by a constructor.

How do I pass additional parameters in my middleware constructor?

**Comment by Tratcher** [comment]
Hmm, that should work. What package and dnx versions are you using?

**Comment by kspearrin** [comment]
beta4 and DNX 4.5.1

**Comment by Tratcher** [comment]
Can you try it with beta5 or beta6?

**Comment by kspearrin** [comment]
Got it working in beta4. Turns out `foo` can't be `null`.

**Comment by Tratcher** [comment]
@davidfowl This still seems like a bug, parameters won't always have values, especailly since we don't support multiple constructors yet do we?

**Comment by davidfowl** [comment]
Hmmm, we want to support passing in null ctors args?

**Comment by Tratcher** [comment]
It's a valid scenario, especially for testing. I only wonder how hard it is to support.

**Comment by davidfowl** [comment]
I'm not convinced as we don't do this anywhere that we ctor inject but I'll leave it open for now

**Comment by HaoK** [comment]
I've run into this issue before specifically with named options and auth middleware, I had to do ugly passing in string.empty since it wouldn't allow passing in null strings...

**Comment by davidfowl** [comment]
We're not supporting this. Closing.
