### ISSUE TITLE
Rename OnCompletedDispose to RegisterForDispose

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#336]
It maps to what we had before in both WebAPI and System.Web https://msdn.microsoft.com/en-us/library/system.web.webpages.httpcontextextensions.registerfordispose(v=vs.111).aspx. It sounds better and OnCompletedDispose just sounds wrong :smile: 

We may also want to consider making it an extension method.

/cc @HaoK @Tratcher

**Comment by davidfowl** [comment]
lets move this into beta6 and assign to @HaoK

**Comment by HaoK** [comment]
bf1b188e9f48a412be435f8a5baeb0f28106ba95

**Comment by HaoK** [comment]
d142160f470178e1044dd6e94a4043117479c195
