### ISSUE TITLE
NotImplementedExceptions in FeatureCollection

### ISSUE THREAD

**Issue by ardalis** [aspnet/HttpAbstractions#339]
Why does FeatureCollection have NotImplementedExceptions when it is implementing IFeatureCollection, for which one would expect perfect parity? If there are parts of that interface that FeatureCollection doesn't use, why are they on the interface?

**Comment by davidfowl** [comment]
NotImplementedException is most likely wrong and should be not supported exception.

**Comment by ardalis** [comment]
I'm not sure that's an improvement. Why not adjust IFeatureCollection, which is literally in the same project and folder, to match FeatureCollection's capabilities (or vice versa). Yes, IFeatureCollection inherits from a collection interface, but if that collection interface has too many features, choose a different collection interface to inherit from. Otherwise this is violating Liskov Substitution Principle and resulting in extra bloat in FeatureCollection.

**Comment by Tratcher** [comment]
Those methods are all inherited from IDictionary. They weren't implemented because nobody needed them yet. We never attempt to consume the collection as an IDictionary and I don't think we need anything beyond TryGetValue and Set/indexer.

Recommendation: Remove IDictionary from IFeatureCollection and just add the methods we need.

**Comment by ardalis** [comment]
@Tratcher +1 to your recommendation.

**Comment by muratg** [comment]
Makes sense to me too.

**Comment by davidfowl** [comment]
@Tratcher We want to preserve enumeration also.

**Comment by lodejard** [comment]
Yep, it started as a get/set interface and dictionary was added when enumeration was needed. Out of curiosity, would it make sense to implement the idictionary interface instead of declaring a get/set/enumerable subset?

**Comment by Tratcher** [comment]
IDictionary has 10x more functionality/complexity than we need. This collection is also never exposed directly to the application, it only exists between the server and Hosting/DefaultHttpContext. I'm drafting a subset API list now, but so far the only APIs we actually use are Get and Set. Enumeration is a nice to have, but it's not actually used anywhere or available to the app.

Keeping the surface area to a minimum also makes implementing https://github.com/aspnet/HttpAbstractions/issues/353 so much easier and more efficient.

**Comment by lodejard** [comment]
I agree, but lets keep enumeration (of Type) available to support diagnostic scenarios of displaying all features and writing out all reflected properties.

Sent from mobile device
________________________________
