### ISSUE TITLE
New method: HttpRequest.GetFullUrl 

### ISSUE THREAD

**Issue by muratg** [aspnet/HttpAbstractions#341]
Add a new extension method HttpRequest (GetFullUrl) that returns a string. 

- GetEncodedUrl
- GetDecodedUrl

**Comment by Tratcher** [comment]
We've won't-fixed this request a few times already. What's different now?
#110, #308

**Comment by davidfowl** [comment]
1. It's commonly asked for
2. It's a string so we avoid all of the Uri problems with round tripping

**Comment by Tratcher** [comment]
No, we still have many of the round tripping problems.  What format should all of the components be in? Human readable or encoded for use in headers? I suspect you need at least two methods.

**Comment by davidfowl** [comment]
Not sure why we'd have roundtripping problems. It's just a concat of the parts of the URL that we already have

**Comment by Tratcher** [comment]
The values have already been processed by multiple layers and are in different formats. e.g. Paths are unescaped, query is still escaped, who knows what state the Host is in, etc.. Just concatenating them back together gives you a Frankenstein url. You have to consider both the current format of the data and the desired format/usage of the result.

This is one of the reasons we haven't done this. The only reasonable request I've heard so far for the full url was for logging.  What other usages have been requested? Almost everybody that has asked for this ends up just wanting the pieces, not the full url.

**Comment by borgdylan** [comment]
Would this include the query string as well? While developing I print each request path to the console to make sure stuff gets called by JS. Having the query string as well would be nice.

**Comment by TomGroeneboer** [comment]
I think you can get the querystring with `HttpContext.GetFeature<IHttpRequestFeature>() ` https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Features/IHttpRequestFeature.cs

**Comment by Tratcher** [comment]
@TomGroeneboer You can get it from `HttpContext.Request.QueryString`.

**Comment by Eilon** [comment]
We should re-discuss the names of these. Those the current names are technically correct, I don't believe they will lead to correct usage. The doc comments explain what's what, but I'm sure they'll be often ignored. I recommend perhaps changing `GetDecodedUrl()` to be something more like `GetDisplayUrl()`, or perhaps even getting rid of it entirely.
