### ISSUE TITLE
Adding a querystring to a pathstring can end up with a pathstring.

### ISSUE THREAD

**Issue by blowdart** [aspnet/HttpAbstractions#342]
Consider the following

```
PathString example = new PathString("/Home/").Add(new QueryString("?yousuck=true"));
```

This works because of the implicit string conversions, but you end up with something that is no longer a true PathString, but a path with a querystring embedded in it.

**Comment by Tratcher** [comment]
It's not the `Add` that breaks here, it's the `=`. `PathString.Add(QueryString)` returns a plain `string` (encoded), which is then implicitly converted back to a PathString for the `=` operator.

**Comment by Tratcher** [comment]
Simplified example:
```
PathString example = "/Home/?yousuck=true";
```

**Comment by blowdart** [comment]
Yea, that should probably get rejected, unless you're going to escape the ?, which is probably not what people expect.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2728
