### ISSUE TITLE
Reading the Form data goes to disk every time

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpAbstractions#343]
Found while profiling simple model binding scenarios in MVC

`BufferingHelper.EnableRewind` will do a check for the existence of the temp directly on each request, even when there isn't enough data to force a write to disk. 
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/BufferingHelper.cs#L40

Discussed with @Tratcher - we can have this wait until a write is actually needed to do the write, or even ask forgiveness instead of asking permission.

**Comment by rynowak** [comment]
![image](https://cloud.githubusercontent.com/assets/1430011/8578381/5fbbeb52-2563-11e5-8293-8702f15af08f.png)

In the context of this profile - 100% means the time inside Middleware (includes Files, Routing, MVC). Fully 20% of the app's time is spent enabling buffering for about 50 char of text.

**Comment by davidfowl** [comment]
The CreateTempFile() in FileBufferingReadStream should do this work.

**Comment by Tratcher** [comment]
Or change BufferingHelper.TempDirectory to cache. It's not like this is going to change much. It's the Directory.Exists check that's showing up in the profiles.

**Comment by davidfowl** [comment]
I still think it should be lazy. Do both things. I'm not sure why it would even throw unless you actually needed to write to that directory.
