### ISSUE TITLE
Replacements for HttpResponse.End() and .Flush()

### ISSUE THREAD

**Issue by TomGroeneboer** [aspnet/HttpAbstractions#346]
Hi guys,

Is there going to be a replacement for HttpResponse.End()? And .Flush()? I can't find them anymore, did they move anywhere?

Thanks!

**Comment by davidfowl** [comment]
There is no replacement for Response.End() (We don't thread abort anymore) and Response.Body.Flush() might not do what you expect. Some servers don't buffer anything by default, so Write actually is writing to the underlying network without a call to flush. There's still an open workitem on our plate to revisit how response buffering will work in ASP.NET 5.

**Comment by TomGroeneboer** [comment]
Alright thanks! So the 'flushing'  is going automatically?

**Comment by Tratcher** [comment]
Flushing is only guaranteed at the end of a response. HttpResponse.Body.Write(...) will usually cause the response to be sent, but HttpResponse.Body.Flush() should force it.

**Comment by TomGroeneboer** [comment]
Thanks! I'll replace the HttpResponse.Flush() with HttpResponse.Body.Flush() :)

**Comment by davidfowl** [comment]
@TomGroeneboer it would be good to see how you are using it.

**Comment by TomGroeneboer** [comment]
When I export some big files I want to give the users a response. I know it can be done by using SignalR and AJAX, but that's to complicated for my situation. During the exporting, I Flush() some messages to the client.
