### ISSUE TITLE
HtmlDecode

### ISSUE THREAD

**Issue by TomGroeneboer** [aspnet/HttpAbstractions#347]
Hi guys,

I'm missing the HtmlDecode() function :( I can find the HtmlEncode, but where is the HtmlDecode? 

Thanks!

**Comment by muratg** [comment]
@Tratcher

**Comment by Tratcher** [comment]
They're right, we didn't do any decoders, only encoders.

@TomGroeneboer where do you need to decode HTML?

**Comment by Tratcher** [comment]
Also, have you tried WebUtility.HtmlDecode (System.Runtime.Extensions CoreCLR package)?

**Comment by muratg** [comment]
Yeah, I wasn't sure about the scenario either... WebUtility (and HttpUtility too I believe) have this method but not sure where it's needed.

**Comment by muratg** [comment]
@TomGroeneboer closing this one for now. If `WebUtility.HtmlDecode` doesn't work for you, please feel free to bring the discussion back.
