### ISSUE TITLE
HttpResponse.Charset

### ISSUE THREAD

**Issue by TomGroeneboer** [aspnet/HttpAbstractions#348]
Hi guys,

I'm missing the HttpResponse.Charset value in ASP.NET 5. Is it going to be there? Or is there another method to set the Charset?

Thanks!

**Comment by Tratcher** [comment]
Charset (e.g. `utf-8`) is a sub-field of the content-type header (e.g. `text/plain; charset=utf-8`) and can be set using the ContentType property. If you want a little more structure you can use `httpResponse.GetTypedHeaders().ContentType = new MediaTypeHeaderValue("text/plain") { Charset = "utf-8" }` (see Http.Extensions).

**Comment by TomGroeneboer** [comment]
Hmm I understand. Alright thanks!
