### ISSUE TITLE
HttpRequest.Cookies is not RequestCookiesCollection?

### ISSUE THREAD

**Issue by TomGroeneboer** [aspnet/HttpAbstractions#349]
Hi guys,

I have a question, why is HttpRequest.Cookies an IReadableStringCollection and not a RequestCookiesCollection. It would be very convenient if it was, accessing properties of cookies is way easier. 

Or am I missing the way to convert the IReadableStringCollection to RequestCookiesCollection?

Thanks!

**Comment by Tratcher** [comment]
Properties of cookies? Request cookies don't have properties, only a key and value.

**Comment by TomGroeneboer** [comment]
In previous versions we could retrieve the `Expires` value

**Comment by Tratcher** [comment]
There is no such field for a request cookie, it only exists on a response cookie.

Are these the old APIs you're referencing?
https://msdn.microsoft.com/en-us/library/system.web.httprequest.cookies(v=vs.110).aspx
"After you add a cookie by using the HttpResponse.Cookies collection, the cookie is immediately available in the HttpRequest.Cookies collection, even if the response has not been sent to the client."
https://msdn.microsoft.com/en-us/library/38yh3s7x(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.web.httpcookie(v=vs.110).aspx

Asp.Net 5 does not mix request and response cookies.

**Comment by TomGroeneboer** [comment]
Oh sorry, you're right. I had a wrong ref in there! Thanks man!
