### ISSUE TITLE
MapMiddleware should support rejoining the parent pipeline

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#351]
Right now the MapMiddleware either takes the branch or calls next. There should be an option to fallback to the parent pipeline (or maybe that should just be the default), instead of getting a child appbuilder with a 404 by default.

/cc @Tratcher @DamianEdwards

**Comment by muratg** [comment]
Sounds like a good idea. 1.0.0 backlog for now.

**Comment by Tratcher** [comment]
We've theorized about this since the first days of Katana, but nobody has ever actually asked for it.

I think you'd want it to be a distinct keyword rather than just an option because of how much it changes the semantics.

**Comment by avanderhoorn** [comment]
I have a use case for this. We want to have `app.Map("/Glimpse", ...)` which dynamically loads various "child" middleware. If none of these deal with the request, I want it to continue on with the users pipeline, we shouldn't steal everything that is under Glimpse.

**Comment by avanderhoorn** [comment]
With help from @davidfowl, I've done up the following based on the current `app.Map()` implementation - https://gist.github.com/avanderhoorn/00de3272901797060812

**Comment by Bartmax** [comment]
:+1:

In my case, I have an Authorization Server and Resource Server on same project.
I want all my api calls to be excluded from Identity middleware while other routes uses Identity. something like:

```
  public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();

            app.UseOAuthBearerAuthentication(opt =>
            {
                opt.AutomaticAuthentication = true;
            });

            app.MapWhen(ctx => !ctx.Request.Path.StartsWithSegments(new PathString("/api")), (subApp) =>
            {
                subApp.UseIdentity();
            });

            // right now, the following lines won't get called if the request doesn't start with the /api path.
            // I would expect to have some kind of (if something do this and continue with the other stuff outside the condition. Like an if flow.
            app.UseMvc();
            ...
        }
```

**Comment by darrelmiller** [comment]
Seems to me that something like that should be called app.UseWhen(...)  It is just a piece of regular middleware that only applies to a subset of the URI space.

**Comment by tuespetre** [comment]
:+1:

Another use case would be to only call 'error-handling' middleware like `app.UseDeveloperExceptionPage()` and `app.UseStatusCodePagesWithReExecute("/Error/{0}")` if the request is not an AJAX request.

**Comment by PinpointTownes** [comment]
FWIW, here's the `UseWhen` version I'm using for a year now: https://gist.github.com/PinpointTownes/6d0492cd3d1b3a64a670
