### ISSUE TITLE
Make a wrapper IFeatureCollection implementation of IDictionary<Type,Object> that switches on well-known interface types

### ISSUE THREAD

**Issue by halter73** [aspnet/HttpAbstractions#353]
We could do something similar to what @loudej did for the [Kestrel header dictionaries](https://github.com/aspnet/KestrelHttpServer/commit/dfd412bab513e40dd634871fbcf689304e5938cd) for FeatureCollection.

![profile](https://cloud.githubusercontent.com/assets/54385/8839740/87c41374-308d-11e5-90db-7147a4cdf56f.jpg)

**Comment by Tratcher** [comment]
Yes. Note that https://github.com/aspnet/HttpAbstractions/issues/339 proposes restricting the surface area down from a full IDictionary, so this shouldn't be nearly as complicated as the header collections.

**Comment by Tratcher** [comment]
Oh, and this shouldn't be a wrapper around IFeatureCollection, it should be done in the default FeatureCollection implementation.

**Comment by glennc** [comment]
Backlog unless this becomes more important for overall perf work.

**Comment by davidfowl** [comment]
We do this in each server already
