### ISSUE TITLE
Fix travis CI

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#357]
https://travis-ci.org/aspnet/HttpAbstractions/builds/73077060#L1558

Any project that has `"allowUnsafe": true` in a test project fails on Travis. This happens due to a json parser bug on Mono: https://bugzilla.xamarin.com/show_bug.cgi?id=31136

We could modify Sake to use a different json parser.

**Comment by glennc** [comment]
@sornaks can you talk to @Tratcher and maybe @pranavkm to work out what we should do here?

**Comment by sornaks** [comment]
Sure. I'll do that.

**Comment by sornaks** [comment]
@pranavkm  is working on the issue tracked here - https://github.com/aspnet/Universe/issues/141
