### ISSUE TITLE
Add Response.CanClear and Response.Clear()

### ISSUE THREAD

**Issue by lodejard** [aspnet/HttpAbstractions#360]
```
bool HttpResponse.CanClear { get{
  true if Response.Body.CanSeek && !ResponseHeadersSent
}}
void HttpResponse.Clear() {
  reset body and headers.
}
```

**Comment by Tratcher** [comment]
I think they'd go into Microsoft.AspNet.Http.Extensions.

**Comment by Tratcher** [comment]
```
                context.Response.StatusCode = 200;
                context.Response.Headers.Clear();
                context.Response.Body.SetLength(0);
```

**Comment by JonTheMon** [comment]
When using Clear(), should we be expected to do a separate check to ensure the body has been emptied/disposed?   Namely, when getting an exception, the DeveloperExceptionPage calls Clear() but returns Html already in the stream, then the exception page.

**Comment by Tratcher** [comment]
@JonTheMon what component is buffering the body? The servers don't do that by default. What kind of buffer stream is in use? Clear calls SetLength(0), which may only work for MemoryStream.

**Comment by JonTheMon** [comment]
The stream is the HttpContext.Response.Body, or apparently a System.IO.Stream of type VisualStudio.Web.BrowserLink.Runtime.ScriptInjectionFilterStream.  Instead of the SetLength(0) that was mentioned, I've taken to calling Body.Dispose().

**Comment by Tratcher** [comment]
Sounds like a browserlink bug. UseBrowserLink is after UseDeveloperExceptionPage in your Startup, correct? It should have a try/finally in their middleware that removes their stream if exceptions are thrown. Something like this: https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.ResponseCompression/ResponseCompressionMiddleware.cs#L89-L91
Dispose is not recommended.
I'll followup with Browerlink.

**Comment by JonTheMon** [comment]
UseBrowserLink is actually before UseDeveloperExceptionPage.  However, removing UseBrowserLink seems to not show the Developer Exception page anymore.

**Comment by Tratcher** [comment]
Ah, move UseBrowserLink after UseDeveloperExceptionPage to see if that makes a difference.
Note you don't see the exception page when browserlink is removed because no other components are buffering, so exceptions part way through the response cannot be rendered.
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Startup.cs#L42-L43

**Comment by JonTheMon** [comment]
It looks like Clear() works as expected if you use a buffer like ResponseBufferingMiddleware.
