### ISSUE TITLE
Add StringValues struct for collections

### ISSUE THREAD

**Issue by lodejard** [aspnet/HttpAbstractions#361]
Streamlines all of the cases where string,string[] collections cause friction

Also has side-effect of reducing number of allocations per request

**Comment by Tratcher** [comment]
What did the CLR team have to say about this?

Also, layering. Ideally this type would be in a BCL package, not one of ours.

**Comment by Eilon** [comment]
As with many types, we should start out with our own and see where it goes.

**Comment by davidfowl** [comment]
+1

**Comment by lodejard** [comment]
I'm not sure this is *necessarily* a BCL/CLR asset, we certainly don't need to be gated by that for packaged code. Nothing else in HttpAbstractions and web server feature interfaces was punched down that far.

**Comment by davidfowl** [comment]
@Tratcher is concerned because of the layering of WebListener. The lower layer doesn't depend on anything except bcl types today

**Comment by Eilon** [comment]
WebListener is a DNX-only component in practice, but either way, having it depend on another package is really not so bad.

**Comment by Tratcher** [comment]
@lodejard Do you have your prototype code in a branch? Or paste it here?

**Comment by lodejard** [comment]
yep, https://github.com/aspnet/HttpAbstractions/tree/lodejard/stringvalues
