### ISSUE TITLE
[Doc comments] How do I get one parameter from a QueryString?

### ISSUE THREAD

**Issue by Daniel15** [aspnet/HttpAbstractions#363]
The QueryString class doesn't seem very useful for handling existing querystrings. You can append new parameters, but how do I get the value of an existing parameter out of it? Why does it not have an indexed accessor?

**Comment by Tratcher** [comment]
I think you're looking for HttpContext.Request.Query (parsed collection), not QueryString (raw value).

**Comment by Daniel15** [comment]
Ahhh. Yep, that sounds right. I guess I should have inferred that "Query**String**" is the raw string, but `Request.QueryString` was the parsed value in older versions.

The xmldoc for Request.QueryString just says  "Gets or set the query string from owin.RequestQueryString." which is not very descriptive ("owin.RequestQueryString" adds no value to the description). Maybe you should add something like "Use <c>Query</c> to get the parsed values" or something like that to the xmldoc.

**Comment by davidfowl** [comment]
doc comments need fixing

**Comment by Eilon** [comment]
@Tratcher can you update the doc comments for better clarity?

**Comment by glennc** [comment]
Changing to task to get the doc comments updated.
