### ISSUE TITLE
Response.ContentType doesn't work in MVC controller

### ISSUE THREAD

**Issue by Daniel15** [aspnet/HttpAbstractions#364]
I'm using Razor to generate some XML (an RSS feed). I have this in one of my ASP.NET MVC controllers:
```
Response.ContentType = "application/rss+xml";
return View("Foo")
```
However IIS Express is still serving the response as text/html.

This doesn't work either:
```
Response.Headers.Set("Content-Type", "application/rss+xml");
```

However, setting a custom header (eg. `X-Test`) *does* work.

(I wasn't sure whether to report this here or in the ASP.NET MVC repo)

**Comment by Tratcher** [comment]
@rynowak sounds like an MVC issue.

**Comment by Eilon** [comment]
I'm guessing the Razor view engine is overwriting the header (which makes sense - otherwise Razor pages won't work).

@Daniel15 can you try setting the content type header *within* the Razor page?

**Comment by Daniel15** [comment]
That does indeed seem to work. I wasn't sure if there's a "proper" way of setting the Content-Type within a Razor page, but `ViewContext.HttpContext.Response.ContentType = "application/rss+xml"` did the trick.

In any case, this seems to be a regression (or an expected change in behaviour?) compared to previous versions. In ASP.NET MVC 5, setting `Response.ContentType` in a controller *does* work, whereas now the setter doesn't appear to do anything when called from a controller (which is really confusing).

**Comment by rynowak** [comment]
You can set this now on the `ViewResult`.

```
var view = View("Foo");
view.ContentType = MediaTypeHeaderValue.Parse("application/rss+xml");
return view;
```

**Comment by Eilon** [comment]
My feeling is that this is by design. I would expect a view engine to set the appropriate content type as part of its normal behavior. This may very well be different from previous versions of ASP.NET (and MVC), but this is presumably the more correct behavior.

Thoughts?

**Comment by Daniel15** [comment]
That makes sense, but in that case don't forget to add it to the release notes :)

The problem I have with it is that it doesn't throw an error or build warning, it just silently fails. Perhaps the `Response

**Comment by Daniel15** [comment]
That makes sense, but in that case don't forget to add it to the release notes :)

The problem I have with it is that it doesn't throw an error or build warning, it just silently fails. Someone upgrading a site may not even notice their responses don't have the right content type any more. Perhaps the `Response` property of the controller could be a wrapper around the real response object, with an `[Obsolete]` attribute on the stuff you shouldn't touch directly any more (including `ContentType`). The obsolete message could say that you need to set it on the `View` instead (as per @rynowak's comment).

**Comment by Eilon** [comment]
I wouldn't say it's silently failing. It's succeeding, but perhaps not succeeding at what you want :smile: 

The content is being set to whatever you want in the controller.

And then the view engine comes along and sets it to whatever *it* wants (because it's rendering HTML).

I'm not sure there's anything to warn about because all these APIs are doing what they're supposed to do, but they happen to be overwriting each other.

**Comment by Daniel15** [comment]
That's true, but it's still a change in behaviour compared to prior versions :smile: While it's a change that does make sense, some people might see it as a regression (and it certainly looks that way the first time you see it happen). Most of the API changes between ASP.NET MVC 5 and 6 completely break the build, which makes it easy to upgrade. This one is moer subtle.

If you search Google for "ASP.NET MVC set content type, most of the top results set `Response.ContentType` in the controller (eg. http://stackoverflow.com/questions/4439355/how-to-change-returned-contenttype-in-asp-net-mvc-controller-actionresult and http://stackoverflow.com/questions/4411841/how-to-set-contenttype-in-razor-cshtml). I guess this will fix itself when people post new answers explaining how to do it in ASP.NET MVC 6, but it's still worth keeping in mind the fact that a lot of people may be doing it the "old way" right now.

**Comment by rynowak** [comment]
> And then the view engine comes along and sets it to whatever it wants (because it's rendering HTML).

We could also make a change in MVC to set the `Content-Type` to only set the default value if it's unset on the response.

**Comment by Eilon** [comment]
@rynowak if it's possible to do that reliably then that might be reasonable. But if you recall the discussion around status codes and filters (or whatever that was), it's not necessarily possible.

**Comment by rynowak** [comment]
It's not possible with StatusCode because we didn't want to make it nullable.

**Comment by Eilon** [comment]
Yeah I chatted with @Tratcher we should make MVC be not so pushy about the content type.

**Comment by Eilon** [comment]
Moved the bug to MVC: https://github.com/aspnet/Mvc/issues/2947
