### ISSUE TITLE
Consider making IFormFileCollection read-only

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpAbstractions#365]
`IFormCollection` is readonly, `IFormFileCollection` is not.

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Abstractions/IFormCollection.cs
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Abstractions/IFormFileCollection.cs

This is a bit of a speedbump for fixing aspnet/Mvc#2527 and would otherwise require us to duplicate the code in `FormFileCollection`.

**Comment by Tratcher** [comment]
The problem is just that `IFormFileCollection` implements `IList<IFormFile>`, right? You just want something more like IReadableStringCollection?

**Comment by rynowak** [comment]
preferably `IReadOnlyList<IFormFile`
