### ISSUE TITLE
Should HttpContext implement IFeatureCollection?

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#367]
Why doesn't it? It would allow users to enumerate features as well. Although Revision would be kinda weird to expose. Some of the properties could be implicit implementation

**Comment by Tratcher** [comment]
I think a direct implementation would be awkward, like the indexer that takes a type and returns an object.  Features are an advanced topic that most users won't ever deal with. Why not just add a `IFeatureCollection Features { get; }` property? And move Get/SetFeature<T> to extensions on IFeatureCollection.

**Comment by davidfowl** [comment]
Sounds better.

**Comment by Tratcher** [comment]
Dropping out of backlog because it involves breaking changes on the abstract base class.

**Comment by Tratcher** [comment]
This keeps coming up as a useful way to create the structures for calling TestServer.Invoke directly.

**Comment by davidfowl** [comment]
Ah to avoid going through the HttpClient?

**Comment by Tratcher** [comment]
Yes. HttpClient is convenient but it can only handle simple scenarios. Katana had a separate API that let you set up the server data structures directly.
