### ISSUE TITLE
KeyValueAccumulator performance improvements

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#368]
- It allocates 2 dictionaries
- It should probably be a struct

**Comment by davidfowl** [comment]
Even better would be to make the KeyValueAccumulator a call back model so there was 0 allocation (besides the delegate :smile: )

**Comment by muratg** [comment]
If you have any proof of large perf issues with this, bring it back

**Comment by benaadams** [comment]
@muratg this was completed in https://github.com/aspnet/HttpAbstractions/pull/411#issuecomment-153189423
