### ISSUE TITLE
Make a wrapper IFeatureCollection implementation that switches on well-known interface types

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/HttpAbstractions#370]
Similar to what was done for request headers.

![ifeaturecollection](https://cloud.githubusercontent.com/assets/249088/9283205/b5cf91ca-4286-11e5-897b-ad96ed823044.jpg)

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/issues/353
