### ISSUE TITLE
Whats happening with `OnCompleted` & `OnStarting` on IHttpResponseFeature

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/HttpAbstractions#373]
Just wondering what is happening with `OnCompleted` & `OnStarting` on [IHttpResponseFeature](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Features/IHttpResponseFeature.cs#L18-L19). The [default implementation](https://github.com/aspnet/HttpAbstractions/blob/5fe8037281bb826e0708abdcdafbc76571dc21f5/src/Microsoft.AspNet.Http/Features/HttpResponseFeature.cs#L33-L41) currently has it throwing a `NotImplemented` executed exception. Additionally, I'm wondering how it is intended to be use? Looking at the commits I know its for non middleware components to be able to clean up, but how would those components get a handle on the context... maybe `IHttpContextAccessor`?

**Comment by davidfowl** [comment]
They are implemented on the servers. The `HttpContext` is just an abstraction, the features are implemented in the servers themselves (since they are the only ones that actually know when the response starts and completes). 

> Additionally, I'm wondering how it is intended to be use? Looking at the commits I know its for non middleware components to be able to clean up, but how would those components get a handle on the context... maybe IHttpContextAccessor?

`IHttpContextAccessor` is the only way to get the HttpContext outside of a component that is handing you the `HttpContext` in general.

**Comment by Tratcher** [comment]
You register a state object with your callbacks so you can pass the HttpContext in as/with state. You could also use a closure. IHttpContextAccessor is not required. See:
https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNet.Diagnostics/ErrorHandlerMiddleware.cs#L61
