### ISSUE TITLE
The placement of ISession and SessionExtensions

### ISSUE THREAD

**Issue by tuespetre** [aspnet/HttpAbstractions#375]
I was just wondering about the placement of these extensions, and for that matter, the `ISession` interface itself... I found them by examining some test source code, but it seems a little unintuitive, as I would expect to be able to add a `using` statement for the `Microsoft.AspNet.Session` namespace to:

1. Inject an `ISession` into a service's constructor
2. Be able to use `SetString`, etc.

Interested in technical/nitpicky details and reasoning if you don't mind, I find it all interesting. :smiley_cat:

**Comment by Tratcher** [comment]
The extensions are in the Http namespace because they will primarily be used directly from HttpContext.Session.
ISession is not a service, it's a per-request resource accessible from HttpContext. The interface is used to abstract over different implementations and storage.
