### ISSUE TITLE
PathString StartingSegment method

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/HttpAbstractions#381]
I've been doing some work with `PathString` and for various use cases I have found it useful to have a `StrartingSegment` method. The implementation is fairly simple and I was just wondering if there was any interest in this within on of the HttpAbstraction packages? I've done it as an extension method, but it could also be done as a first class method too.

Here is the basic implementation, happy to do it as a PR if there is wider interest in it.

``` csharp
public static class PathStringExtension
{
    public static string StartingSegment(this PathString path, out PathString remaining)
    {
        var startingSegment = "";

        var spath = path.ToString();
        for (var i = 1; i < spath.Length; i++)
        {
            if (spath[i] == '/')
            {
                remaining = spath.Substring(i, spath.Length - i);
                return startingSegment;
            }

            startingSegment += spath[i];
        }

        remaining = PathString.Empty;
        return startingSegment;
    }
}
```

**Comment by davidfowl** [comment]
Where have you been using it?

**Comment by avanderhoorn** [comment]
Basically we allow users to register Resources that Glimpse manages. These
resources are "hosted" by the Glimpse server middleware. Additionally,
because Glimpse is managing the endpoint, we can send down the metadata
about resources to the client so that it can discover the correct location
(which can be configured by the user and will be different in different
platforms). Additionally, we leverage Uri Templates on both the client and
server to manage the way parameters are passed and managed.

Given all of this, we have our own mini/light routing process which after a
'Map("/Glimpse", ...)' kicks in, looks at the first segment to target the
registered resource that is going to handle the request. More details here
- https://github.com/Glimpse/Glimpse.Prototype/pull/23 and here
https://github.com/Glimpse/Glimpse.Prototype/blob/dev/src/Glimpse.Server.Web/Framework/ResourceManager.cs#L22
.

So that is the usecase we have and how we use it.

**Comment by NickCraver** [comment]
It *looks* like this made it in as `StartsWithSegments` ([link](https://github.com/aspnet/HttpAbstractions/blob/87cd79d6fc54bb4abf07c1e380cd7a9498a78612/src/Microsoft.AspNetCore.Http.Abstractions/PathString.cs#L212)).  If so, I think this just needs a closing to cleanup.

**Comment by davidfowl** [comment]
Yes this got added
