### ISSUE TITLE
Interfaces instead abstract classes for HttpContext

### ISSUE THREAD

**Issue by fabiomaulo** [aspnet/HttpAbstractions#385]
In addition to HttpContext, HttpRequest, HttpResponse would be useful, and more easy to mock using custom impl. instead a mock fw, to have some interfaces.
An example of little difficult is that you can implement something like this
    public override HttpRequest Request { get; set; }
just because the base class does not expose the setter.
Something I have done in the past for a self hosted API (HttpListener working a desktop app)
    public interface IApiRequestContext
    {
    IApiRequest Request { get; }
    IApiResponse Response { get; }
    IDictionary<string, string> RouteData { get; }
   }
    public interface IApiRequest
    {
    string HttpMethod { get; }
    Uri Url { get; }
    Stream InputStream { get; }
    bool HasEntityBody { get; }
    string[] AcceptTypes { get; }
    Encoding ContentEncoding { get; }
    long ContentLength64 { get; }
    string ContentType { get; }
    }
    public interface IApiResponse: IDisposable
    {
    NameValueCollection Headers { get; }
    string ContentType { get; set; }
    Stream OutputStream { get; }
    long ContentLength64 { get; set; }
    int StatusCode { get; set; }
    string StatusDescription { get; set; }
    void Close();
   }

The TDD for the whole API was a piece of cake.

**Comment by Tratcher** [comment]
.NET Framework design guidelines:
https://msdn.microsoft.com/en-us/library/vstudio/ms229013(v=vs.100).aspx
"Do favor defining classes over interfaces.
In later versions of your library, you can safely add new members to classes; you cannot add members to interfaces without breaking existing code."

**Comment by davidfowl** [comment]
Thats not exactly why we didn't do it (we use interfaces other places in the stack). We have 2 layers the feature layer which are all individual feature interfaces and the HttpContext is just a facade over those features. For testing, you should be using the DefaultHttpContext, you can new it up and set all of the properties and makes testing http stuff super easy.

**Comment by fabiomaulo** [comment]
Understood @davidfowl . I have surfed the code and features (Microsoft.AspNet.Http.Features), is the way to go.
Thanks.

A sms to @Tratcher : "Program to an 'interface', not an 'implementation'." (Gang of Four).
I know... I'm a little old man ;)
