### ISSUE TITLE
WebEncoders should support Unicode 8.0

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/HttpAbstractions#387]
The Unicode 8.0 standard (http://blog.unicode.org/2015/06/announcing-unicode-standard-version-80.html) was released not too long ago. We should update WebEncoders with the new block information. Currently it uses the Unicode 7.0 block information.

**Comment by muratg** [comment]
https://github.com/aspnet/HttpAbstractions/issues/391
