### ISSUE TITLE
Add ReasonPhrase to HttpResponse

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#395]
Because this code
`response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase = null;` is ridiculous

**Comment by Tratcher** [comment]
No, it's useless &/ obsolete.

The servers will set the reason phrase based on the status code. The application should only ever consider setting it if they are defining custom status codes, and even then it's optional. Most users just set it to the default values anyways.

HTTP/2 has removed this field.

**Comment by muratg** [comment]
@davidfowl Why do we need this?

**Comment by davidfowl** [comment]
If we think nobody needs to use it I'm ok punting. As I said:

```
response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase = null
```

Is ridiculous. We pretty much expose everything else on the IHttpResponseFeature.

**Comment by Tratcher** [comment]
The features are complete / raw protocol, where HttpContext is about convenience. It is part of the protocol, but we have reasons for not making it convenient.

**Comment by davidfowl** [comment]
Cool. Closing this out until somebody asks for it.
