### ISSUE TITLE
UseBuilder should take optional Action<IServiceCollection> 

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#398]
To make it easier to configure services in the ASP.NET 5 pipeline when exposed via Owin

**Comment by muratg** [comment]
Won't the overload with `Action<IApplicationBuilder>` be enough for that? It has a `ServiceProvider` property.

**Comment by Tratcher** [comment]
Except ServiceProvider is null: https://github.com/aspnet/HttpAbstractions/blob/f475e53ad235478b5ac35bab31a72e6cafb52156/src/Microsoft.AspNet.Owin/OwinExtensions.cs#L72

**Comment by JunTaoLuo** [comment]
merged to dev
