### ISSUE TITLE
[Perf] High Allocator DefaultHttpContext

### ISSUE THREAD

**Issue by benaadams** [aspnet/HttpAbstractions#402]
For 2000 plaintext requests DefaultHttpContext allocates 12,078 objects:

![image](http://aoa.blob.core.windows.net/aspnet/dhttp_alloc_objects.png)

Clocking in at 927,624 bytes:

![image](http://aoa.blob.core.windows.net/aspnet/dhttp_alloc_bytes.png)

Which would mean if you were performing 1M rps the GC would have to flush 6,039,000 objects and 464 Mbytes per second, 927 Mbytes per second for 2M rps and 3.2GBytes (42.3M objects) per second for 7M rps (~10GbE saturation) or 192 GBytes per minute.

**Comment by rynowak** [comment]
@benaadams - images aren't loading

**Comment by benaadams** [comment]
@rynowak better? (Have a PR for this)

**Comment by rynowak** [comment]
yeah images are showing up now.

**Comment by benaadams** [comment]
Have PR that reduces this to 136 objects

![allocs](http://aoa.blob.core.windows.net/aspnet/dhttp_alloc_after.png)

And 20434 bytes total for the lifetime of the app

![allocs](http://aoa.blob.core.windows.net/aspnet/dhttp_alloc_bytes_after.png)

**Comment by benaadams** [comment]
Using the Test aspnet site: https://github.com/benaadams/IllyriadGames.Server.Web.River.Test on the server https://www.nuget.org/packages/IllyriadGames.Server.Web.River

Before this change and https://github.com/aspnet/DependencyInjection/pull/289 running a 10 second test allows 311,043 rps:

![10 sec run](http://aoa.blob.core.windows.net/aspnet/before_10s.png)

However the GC load is very high so running the test for 3 minutes causes the network to periodically flatline as it goes 100% on GC; which means it can only do 61,468 rps with very high latencies:

![3 min run](http://aoa.blob.core.windows.net/aspnet/before_3m.png)

With these two (three PRs) changes running the same server for 3 minutes is very consistent network performance and is performing 1,422,499 rps with much much lower latency:

![3 min after](http://aoa.blob.core.windows.net/aspnet/after_3m.png)

For reference the [RIO server](https://github.com/aspnet/benchmarks/pull/12) on this hardware+network is performing 1,991,008 rps

![3 min rio](http://aoa.blob.core.windows.net/aspnet/rio_3m.png)

And this is kinda the addition of the aspnet to that server (still not parsing headers :smile:

So with these changes the RIO server goes from 1.99M rps -> 1.42M rps by adding the aspnet layer, which is quite good; and there is still scope to improve further. 

Without them its 1.99M rps -> 61.5k rps which isn't so good.

**Comment by benaadams** [comment]
@davidfowl ok if I put most findings in this Issue or do you want me to split with https://github.com/aspnet/DependencyInjection/issues/288

**Comment by benaadams** [comment]
Some background, pre-changes it starts fastish but you can see is on 100% cpu and the network performance is deteriorating over time:

![image](http://aoa.blob.core.windows.net/aspnet/pre-network-short.png)

Eventually it completely flatlines on network even though CPU is still 100%

![image](http://aoa.blob.core.windows.net/aspnet/pre-network-flatline.png)

It then recovers; though again is following same pattern of deterioration:

![image](http://aoa.blob.core.windows.net/aspnet/pre-network-running.png)

And the results are effected heavily

![image](http://aoa.blob.core.windows.net/aspnet/pre-restults-short.png)

**Comment by benaadams** [comment]
Post change, is still some saw toothing, but is very consistent and a much higher throughput

![image](http://aoa.blob.core.windows.net/aspnet/post-network-running.png)

As is shown in results:

![image](http://aoa.blob.core.windows.net/aspnet/post-network-results.png)

**Comment by benaadams** [comment]
Top numbers were 2000 requests not 2400; updated

**Comment by benaadams** [comment]
@davidfowl wanted some more details so breakdown for bytes for first level as follows (will break them down further):

![hc-0](http://aoa.blob.core.windows.net/aspnet/hc-0.png)

**Comment by benaadams** [comment]
contextFactory.CreateHttpContext(features)

![hc1](http://aoa.blob.core.windows.net/aspnet/hc-1.png)

![hc2](http://aoa.blob.core.windows.net/aspnet/hc-2.png)

**Comment by benaadams** [comment]
Not addressed in this PR (or DI one) but for completeness:

httpContext.ApplicationServices = _applicationServices;

![hc-3](http://aoa.blob.core.windows.net/aspnet/hc-3.png)
one path
![hc-4](http://aoa.blob.core.windows.net/aspnet/hc-4.png)
other path (constructor at end of line)
![hc-5](http://aoa.blob.core.windows.net/aspnet/hc-5.png)

**Comment by benaadams** [comment]
The GC pauses are pretty extreme so will wait for this hotfix rollout before testing further (though that should already be in use for dnx beta8+?): http://blogs.msdn.com/b/maoni/archive/2015/08/12/gen2-free-list-changes-in-clr-4-6-gc.aspx

**Comment by benaadams** [comment]
Update!

Previously for 2000 requests

![hc-0](http://aoa.blob.core.windows.net/aspnet/hc-0.png)

New for 2003 requests 

Drill down on Issue #288
Measurements post PR #287

![hc-new](http://aoa.blob.core.windows.net/aspnet/hc-new.png)

So is only 61% of before and down 1.5MB per 2000 requests.

However CreateContext is still Item 4 on highest allocators in plaintext test

![most-memory](http://aoa.blob.core.windows.net/aspnet/most-memory1.png)

**Comment by davidfowl** [comment]
It would be good to do an analysis after the changes
