### ISSUE TITLE
PathString argument exception that doesn't start with '/' should say so...

### ISSUE THREAD

**Issue by HaoK** [aspnet/HttpAbstractions#406]
```
                app.Map("always", map => { });
```

This currently gives you an extremely useless ArgumentException:

      System.ArgumentException :
      Parameter name: value
      Stack Trace:
           at Microsoft.AspNet.Http.PathString..ctor(String value)
           at Microsoft.AspNet.Http.PathString.op_Implicit(String s)

This should say PathStrings should start with '/' or something.  I hit this when using Map

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/issues/251
