### ISSUE TITLE
IFeatureCollection indexer is pretty bad

### ISSUE THREAD

**Issue by lodejard** [aspnet/HttpAbstractions#414]
This usage is pretty awful:
```csharp 
var feature = httpContext.Features[typeof(IServiceProvidersFeature)] as IServiceProvidersFeature;
```
It doesn't show up in intellisense, and GetFeature/SetFeature don't appear on HttpContext...

Didn't we have something more like this at one point?
```csharp
var feature = yadda.GetFeature<IServiceProvidersFeature>();
```

**Comment by Tratcher** [comment]
It moved to `httpContext.Features.Get<T>();`

**Comment by lodejard** [comment]
Oh, the namespace `using Microsoft.AspNet.Http.Features;` means it pretty much won't show up if you don't already know it exists. Is there anything we can do about that?

**Comment by Tratcher** [comment]
All the interfaces are also on that namespace, so you need to add it anyways. Would be nice if we could make the first time intellesence work better though.

VS feature? Consider the namespace of the thing currently being operated on?

**Comment by davidfowl** [comment]
We can't Felton's features. We should move things around

**Comment by Tratcher** [comment]
Just keep in mind that Features are for advanced scenarios like middleware authoring, don't munge them in with all the beginners stuff.

**Comment by HaoK** [comment]
Just a +1, I was looking for these methods, and it was hard to find them even looking for them :)

I ended up needing all 3 namespaces for the IServiceProviders change:
```
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Http.Features;
using Microsoft.AspNet.Http.Features.Internal;
```

**Comment by davidfowl** [comment]
Ugh

**Comment by muratg** [comment]
Collapsing namespaces is also a solution.

**Comment by Tratcher** [comment]
Resolved by https://github.com/aspnet/HttpAbstractions/issues/522
