### ISSUE TITLE
Move Microsoft.Framework.WebEncoders.Testing to this repo

### ISSUE THREAD

**Issue by Eilon** [aspnet/HttpAbstractions#418]
It's in https://github.com/aspnet/Testing/ right now.

There are currently some circular references in the repo-to-repo dependencies that we'd like to fix, and this is one of them. The idea of putting this package here is that if you're referencing the regular runtime package, you may very well want the companion test-helper package as well.

Note: the package needs to stay in the `/src` folder because this is a "runtime" package, even if it's test helpers.

**Comment by Eilon** [comment]
Related: https://github.com/aspnet/Logging/issues/252

**Comment by Tratcher** [comment]
Obsolete due to https://github.com/aspnet/HttpAbstractions/issues/391 ?

Also, the Testing package used to be in this repo and was moved for some reason. Need to track that down before moving it back.

**Comment by Eilon** [comment]
No we still need the test helpers regardless of where the actual encoding logic lives.

Hmm I don't recall why it was ever moved... maybe just to group all the test stuff in one place?
