### ISSUE TITLE
Allow a way to mark all cookies as "HTTP only" and "SSL required" by default

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/HttpAbstractions#42]
Basically, this would be an equivalent to the ```<httpCookies>``` element in Web.config:

```xml
<httpCookies domain="String" 
             httpOnlyCookies="true|false" 
             requireSSL="true|false" />
```

Allows marking all cookies with these flags regardless of how the CookieOptions object is constructed.  More info at http://msdn.microsoft.com/en-us/library/ms228262(v=vs.100).aspx.

**Comment by blowdart** [comment]
And rename the "secure" cookie option as part of this.

**Comment by Eilon** [comment]
Removing @GrabYourPitchforks as the assignee :smile: (Unless you like, you know, really want to do it :smile: )

**Comment by Tratcher** [comment]
@blowdart in this case `secure` is appropriate because that's the actual text used in the cookie header.

**Comment by blowdart** [comment]
That doesn't make it true though.

**Comment by Tratcher** [comment]
Agreed, but we can't change the RFC.  Renaming our APIS that set this value will just case confusion about what's being set.

**Comment by davidfowl** [comment]
Seems like this would be a feature of Hosting

**Comment by Tratcher** [comment]
Any proposals on how? High jacking the `IResponseCookiesFeature`?

**Comment by davidfowl** [comment]
I think so.

**Comment by SteveArr** [comment]
I would be interested in taking this on.  

I am already doing some work with the Secure flag on cookies for https://github.com/aspnet/Session/pull/28

**Comment by HaoK** [comment]
@blowdart how important is this for beta 6 (i.e. do we need this now?)

**Comment by blowdart** [comment]
It's a big security regression, so it would be really really nice to have as soon as possible, but I leave the exact release to your discretion. If you have time now, then please do now.

**Comment by HaoK** [comment]
Ok I will try to take a look this week

**Comment by Tratcher** [comment]
Preference for making this a middleware rather than embedding it in hosting.

**Comment by blowdart** [comment]
Added suggestion - why not change the cookie class to make cookies http only for default, and make them "secure" by default if the request is over https.

**Comment by HaoK** [comment]
Not going to happen for beta 6 at this point

**Comment by davidfowl** [comment]
@HaoK lets have a little design meeting before you tackle this.

**Comment by muratg** [comment]
@haok will you be able to look into this?

**Comment by HaoK** [comment]
```
UseCookiePolicy(new CookiePolicyOptions
{
  HttpOnly = HttpOnlyPolicy.None | Always
  Secure = SecurityPolicy.None | Always | SameAsRequest
  OnAppendCookie = ctx => 
  OnDeleteCookie = ctx => 

  AppendCookieContext ( HttpContext, CookieOption, CookieName, CookieValue)
  DeleteCookieContext ( HttpContext, CookieOption, CookieName, CookieValue)
});
```

**Comment by HaoK** [comment]
Test Map behavior

**Comment by HaoK** [comment]
Namespace: Microsoft.AspNet.CookiePolicy in security repo stand alone package.

**Comment by davidfowl** [comment]
This is nice!

**Comment by HaoK** [comment]
5cc1fea40045041f77a6bb2bd23e231e24f82da7

**Comment by mgolois** [comment]
@HaoK I just want to confirm. Im currently migrating code.

.net 4.5 mvc:
` <httpCookies requireSSL="true" />`

so in .net core mvc, it should be this:
` services.ConfigureApplicationCookie(o => o.Cookie.SecurePolicy = Microsoft.AspNetCore.Http.CookieSecurePolicy.Always);`

is that correct?

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.
