### ISSUE TITLE
MVC Controller Response - Wrong ContentType

### ISSUE THREAD

**Issue by Fosol** [aspnet/HttpAbstractions#424]
The default response ContentType of an endpoint that returns a struct value (i.e. int) is "application/json".  However the body contains invalid json as it only has the int value.

If you attempt to set the Response.ContentType = "text/plain" it ignores you and sets it to "application/json".

If you attempt to set the Response.ContentType = "text/plain" through the Response.OnStarting method it results in a body containing gibberish.

How do you set the Content Type of the response if you are returning a struct value type?

**Comment by kichalla** [comment]
@Fosol what content type do you want to send it as? text/plain?...can you check if you return the int as a string you should see the response as text/plain...otherwise you can use the `ContentResult` to set the content and content-type the way you want

**Comment by Fosol** [comment]
Here's an example endpoint.


        [HttpGet]
        [Route("add/{value1}/{value2}")]
        public int Add(int value1, int value2)
{
            return value1 + value2;
}

The default response ContentType: application/json.  But the body only has the number and therefore is invalid json.

If you return a string it does by default become text/plain.

**Comment by kichalla** [comment]
do you want to send the data in json format? if yes, you would need to have that value as a proeprty on an object...example: if your return type is `dynamic`, you can return something like `return new { result = value1 + value 2}`...the response would be in json and `{ "result":30 }`

**Comment by Fosol** [comment]
You mention the ContentResult object.  Does this only work if you are returning something like a ActionResult?

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Mvc#3245
