### ISSUE TITLE
Reduce collection wrapping

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#426]
There are several cases where low level APIs produce a basic IDictionary or similar, but then we wrap it in a IFoo : IDictionary to make it more user friendly. These wrappers cause lots of extra allocations on each request, resulting in lots of GCs.  The main culperates are request headers, response headers, query, form, and cookies.

Headers we can fix by moving IHeaderDictionary into the Features package, use it for IHttpRequestFeature.Headers & IHttpResponseFeature.Headers, and have the servers implement it directly. This is a little more work for the servers, but it removes a wrapper layer.  We'll still need the old wrapper implementation for tests though.

Query, Form, and Cookies we can address by having the callers create a collection that implements IDictionary and their own interface (IQueryCollection, IFormCollection, and ICookiesCollection), and having the parser add everything to the provided IDictionary.

**Comment by benaadams** [comment]
Quick check on "why" the additional interfaces; is this because it is a different contract?

**Comment by benaadams** [comment]
As in context exposes via new interfaces

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/pull/411
