### ISSUE TITLE
SSL CustomCertificateValidator

### ISSUE THREAD

**Issue by YZahringer** [aspnet/HttpAbstractions#430]
Hello,

How to configure allowed SSL certificates?

System.Net.ServicePointManager is unavailable, CustomCertificateValidator also not available in vNext.

There is a new way for this?

Best regards,
Yann

**Comment by Tratcher** [comment]
Wrong repo, the client HTTP APIs are in dotnet/corefx.

It sounds like you're looking for the CoreCLR API? Try WinHttpHandler.ServerCertificateValidationCallback: https://github.com/dotnet/corefx/blob/0987afcd536743bf3a5cf868b3598e898f4aea53/src/System.Net.Http.WinHttpHandler/ref/System.Net.Http.WinHttpHandler.cs#L44
