### ISSUE TITLE
Cookie.Append() escape characters for security

### ISSUE THREAD

**Issue by Codenator81** [aspnet/HttpAbstractions#450]
May be there need parameter to not parse? Like Append("key","value", true) or another function like AppendRaw() ?

**Comment by Tratcher** [comment]
`context.Response.Headers.Append("Set-Cookie", "key=value");`

**Comment by Codenator81** [comment]
@Tratcher  Yes you right I make mistake in example. There problem when I try add cookie for Localization a got cookie writed and parsed same characters

**Comment by davidfowl** [comment]
Something first class on cookies might be nice.

**Comment by muratg** [comment]
Something we can consider adding before RTM.

**Comment by diequeeq** [comment]
I faced with this behavior in my project. A third party app used cookies that I set and as a result, my cookies contained escaped characters that were not recognized by a consumer. 
If there was an option to skip escaping, I'd greatly appreciate it.

**Comment by muratg** [comment]
No changes planned.
