### ISSUE TITLE
FormFeature.ReadForm is Sync over Async

### ISSUE THREAD

**Issue by benaadams** [aspnet/HttpAbstractions#456]
Avoid Sync-over-Async http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx

**Comment by glennc** [comment]
@davidfowl are we going to do anything about this? Seems unlikely at this point.

**Comment by davidfowl** [comment]
Backlog as it's pretty easy to work around (just put a middleware in the pipeline that does an async read).

**Comment by benaadams** [comment]
@blowdart @DamianEdwards just mentioning as stuff like this is trending on twitter; if twitter trended for useful things.

**Comment by davidfowl** [comment]
The reason this isn't *as* bad as your typical sync over async is because you can always pre-load the form in middleware (or in MVC it happens in another component asynchronously before hitting user code) and in that case, the property acts like a cache.

**Comment by benaadams** [comment]
Ah, so its already handled if you use MVC, is only if you go raw or custom? (and ReadFormAsync is available)

**Comment by davidfowl** [comment]
Right, MVC doesn't automagically read the body but if you use model binding then it does and accessing Form is a n00p.

**Comment by DamianEdwards** [comment]
The much worse one in my opinion is `HttpContext.Session` if I recall.

**Comment by Tratcher** [comment]
Yeah, depending on your store. There's also an async way to load it but nobody does it for you. We could make an MVC attribute for that.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2723
