### ISSUE TITLE
[Annoucement] Moving from Microsoft.Extensions.WebEncoders.Core to System.Text.Encodings.Web

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#459]
As of RC2 the types from Microsoft.Extensions.WebEncoders.Core have been moved to System.Text.Encodings.Web. In the process there were several API changes.

IHtmlEncoder -> HtmlEncoder
.HtmlEncode -> .Encode
IJavaScriptStringEncoder -> JavaScriptEncoder
.JavaScriptStringEncode -> .Encode
IUrlEncoder -> UrlEncoder
.UrlEncode -> .Encode

The parameter ordering for some of the Encode methods has also changed.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
