### ISSUE TITLE
Add IsLocalUrl or something similar

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpAbstractions#46]
This is part of the WebFx surface area for back compat, but it's pretty low-level url functionality. We're hoping it can find a home somewhere in abstractions. Need this in some form for alpha

Used to determine if a url specifies a hostname.

`//localhost/foo` => false
`/foo` => true

Pre-existing already-security-reviewed code: https://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.WebPages/RequestExtensions.cs

**Comment by davidfowl** [comment]
Do we still need this? @rynowak @sebastienros

**Comment by rynowak** [comment]
There's no need here from MVC. If we get any requests for this as a standalone API we can move it to webutilities. Suggest closing unless @sebastienros has any bright ideas

**Comment by sebastienros** [comment]
The change made 3 months ago is fixing the non-extensibility so it's good now. If orchard needs custom behavior we can do it.
