### ISSUE TITLE
Reduce allocations in MediaTypeHeaderValue IsSubset

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpAbstractions#464]
Some allocation data and measurements based on 3000 requests to a site doing some simple conneg using MVC 6

First, there's a lot of substringing going on inside `IsSubset` - this is a pretty hot path for conneg.
![image](https://cloud.githubusercontent.com/assets/1430011/10987106/01cf67ae-83e5-11e5-8b3f-df53e507dc84.png)

Secondly, there's a boxed enumerator for `ObjectCollection<T>` that sees a lot of allocs due to `foreach`es
![image](https://cloud.githubusercontent.com/assets/1430011/10987158/82270678-83e5-11e5-9e63-f3c4b4940f9f.png)

These issues are both readily fixable, and are responsible for about 2mb/82mb total bytes allocated for this site.

**Comment by davidfowl** [comment]
@rynowak Please close

**Comment by rynowak** [comment]
308dd109a0ad077e820d1c137fd37d31d2f43886
