### ISSUE TITLE
Remove ApplicationServices from HttpContext?

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#466]
We got some feedback that is is confusing to have both on the HttpContext object. Do we need anything other than request services readily accessible?

/cc @lodejard @rynowak @Tratcher

**Comment by rynowak** [comment]
My suggestion for a while has been just to have one SP on the context. If you're using request services middleware then it replaces the app services with the request services.

**Comment by lodejard** [comment]
+1 - if there's one property just call it `IServiceProvider Services` and have it always track the currently effective scope like Ryan described.

It started as one property already, and changed in case a middleware needed to create a new child scope from the app scope instead of from the request scope. But it can just close over the app ISP at startup if that's the case. So even there this should be totally fine.

**Comment by Tratcher** [comment]
You can remove the HttpContext property but keep the [IServiceProvidersFeature](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http/Features/ServiceProvidersFeature.cs) property for components that need access to the app services.

**Comment by davidfowl** [comment]
Lets do this then.

**Comment by DamianEdwards** [comment]
Sounds good. I'm OK with this in RC2.

**Comment by davidfowl** [comment]
@Tratcher what component is that?

**Comment by Tratcher** [comment]
I don't know, why did you give access to them in the first place? Louis already pointed to one scenario.

**Comment by davidfowl** [comment]
And also called out how why it's not required. Middleware can get ISP from the IApplicationBuilder or just taking it in the ctor. It doesn't need to be a property on the HttpContext or the feature interface

**Comment by rjperes** [comment]
Just for coherence, the Controller property is called Resolver... should we change both (that and HttpContext) for Services?

**Comment by davidfowl** [comment]
I don't think so. The type was IDependencyResolver so Resolver made a bit more sense. I think we'll stick with Services here.

**Comment by rjperes** [comment]
*was* IDependencyResolver, now it is IServiceProvider! :-)
Don't you think, for coherence's sake, identical things should be called identically?
Not a big issue, though...

**Comment by davidfowl** [comment]
In general yes but in this case I'd prefer not to break everything under the sun. I actually think we should just remove ApplicationServices and leave it as RequestServices.

**Comment by JunTaoLuo** [comment]
@avanderhoorn You'll need to make changes to Glimpse after we made this change.
