### ISSUE TITLE
Re-evaluate more granular, less commonly used features

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#472]
We allocate a bunch of objects (albiet lazily) that wrap individual features like Cookies/Query/Form/Items/ServiceProviders. We should re-evaluate the granularity of these objects.

**Comment by benaadams** [comment]
Would it make sense for the default concrete types to implement both `ITypeFeature` and `ITypeCollection` 

e.g. 

`QueryCollection : IQueryCollection, IQueryFeature`

Maintains composability; but by default only allocates only one object rather than an indirection layer and an object?

**Comment by muratg** [comment]
Moving this to Backlog as we will be in RC2 ask mode very soon.  If you feel strongly about this issue, please ping me.
