### ISSUE TITLE
Don't set IHttpContextAccessor by default

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/HttpAbstractions#473]
Setting up `IHttpContextAccessor` on every request is expensive and thus should probably be opt-in. Frameworks that require it (like MVC) can add it to the container as needed. If it's in the container, then we should set it up per request, otherwise, don't.

**Comment by rynowak** [comment]
We can drop our reliance on this and similar things in MVC. See https://github.com/aspnet/Mvc/issues/3523
