### ISSUE TITLE
Return type based on Accept header

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/HttpAbstractions#474]
Considering MVC & Web API are now merged and can be served from the same controller, I was wondering if there is a way to return an appropriate type for the requested content type?

For example, consider a POST request that was successful:
From a form/MVC we may `return RedirectToAction("Index")`
From a REST call with JSON, `return new ObjectResult(newObject);`

Is there a return type that either the route or object could be returned as appropriate?

This may be more appropriate in the MVC repository, but thought it may be to do with the HTTP request/return operations so posted here. Let me know otherwise.

**Comment by davidfowl** [comment]
Definitely an MVC question.

**Comment by damienpontifex** [comment]
Thanks, will repost there.
