### ISSUE TITLE
Have a public BufferedHtmlContent-like type

### ISSUE THREAD

**Issue by Eilon** [aspnet/HttpAbstractions#477]
People writing HTML-related codes might wish to "concatenate" existing `IHtmlContent` instances. Today this is rather difficult because there's no public easy way to do this. We should make [`BufferedHtmlContent`](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Extensions.BufferedHtmlContent.Sources/BufferedHtmlContent.cs) or something similar to it public.

Inspired by: https://github.com/aspnet/Mvc/issues/3544

@rynowak

**Comment by rynowak** [comment]
You were thinking this goes in the same package right?

I'm also going to move over `HtmlTextWriter` - this will solve a bunch of laying problems.

**Comment by rynowak** [comment]
88c356f645e438ba0518d488182cde6a61fd0e21
