### ISSUE TITLE
Useless string copy

### ISSUE THREAD

**Issue by jods4** [aspnet/HttpAbstractions#480]
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/CookieHeaderValue.cs#L153

The cookie value is copied (via `Substring`) although it is already available inside `value`. It was put there by `GetCookieValueLength`, which does its own `Substring` as well.

The only difference, hinted by the comment at L152, is that if the returned length is 0, `GetCookieValueLength` puts `null` inside `value`, and the code referenced above puts the empty string. 

This difference could be accounted for more efficiently by either modifying `GetCookieValueLength` to return an empty string instead of null, or simply using `result._value = value ?? ""`.

This is not much, but it means copying each cookie value twice, which can put a little unnecessary pressure if the cookies are large (e.g. ASP.NET's own auth. cookies) or many.

**Comment by glennc** [comment]
Putting this in backlog, @jods4 if you want to send a PR with some metrics that demonstrate the perf improvements we would likely accept it. :)

**Comment by jods4** [comment]
@glennc Nah, I won't bother writing a benchmark for that. As I said I don't think it's much (well... maybe if you do 1M req/s it starts to add up :wink:).

I noticed while browsing the code trying to figure out another issue I had, so I figured I could tell you about it.

**Comment by Tratcher** [comment]
Handled by https://github.com/aspnet/HttpAbstractions/pull/844
