### ISSUE TITLE
Rename M.AspNet.Html.Abstractions namespace -> M.AspNet.Html

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpAbstractions#481]
We should chop `.Abstractions` off of the **namespace** `Microsoft.AspNet.Html.Abstractions`. It's more verbose than needed. Package should stay named as-is.

**Comment by Eilon** [comment]
:+1:

**Comment by muratg** [comment]
@ryan1234 @Eilon could someone from MVC or Razor do this? It's going to be mainly breaking them.

**Comment by ryan1234** [comment]
Think you got the wrong Ryan. =)

**Comment by Eilon** [comment]
@pranavkm, a gift from @muratg .

**Comment by pranavkm** [comment]
Can we move this to a different repo? It doesn't have much to do with `HttpAbstractions`.

**Comment by Tratcher** [comment]
The issue or the package? I'd love to move the packages.

**Comment by pranavkm** [comment]
It seems like this would be a better fit for `HtmlAbstractions` repo.

**Comment by Eilon** [comment]
Umm yeah except there's no `HtmlAbstractions` repo :smile:

**Comment by Tratcher** [comment]
Then make one, Please?

**Comment by Eilon** [comment]
Can we make do with the current repo at the moment?

**Comment by davidfowl** [comment]
Move it

**Comment by Eilon** [comment]
?

**Comment by rynowak** [comment]
https://www.youtube.com/watch?v=Dyx4v1QFzhQ

**Comment by davidfowl** [comment]
The html stuff

**Comment by Eilon** [comment]
Are you saying new repo or just change the assembly name?

**Comment by davidfowl** [comment]
Repo

**Comment by pranavkm** [comment]
@Eilon let me know when you have a repo created.

**Comment by Eilon** [comment]
Will try to do it tonight.

**Comment by muratg** [comment]
@Eilon make sure to update projectkissuelist as well.

**Comment by pranavkm** [comment]
bump

**Comment by Eilon** [comment]
https://github.com/aspnet/HtmlAbstractions

**Comment by pranavkm** [comment]
Do we need an announcement for the namespace change?

**Comment by muratg** [comment]
Probably a good idea, though I'm not sure if there are a lot of users apart form MVC/Razor.
