### ISSUE TITLE
Middleware header issue

### ISSUE THREAD

**Issue by Fosol** [aspnet/HttpAbstractions#483]
I'd like to be able to add a Response Time header to all responses. However in many cases if I attempt to add the response time header value at the end of the actual execution it will throw an exception because it no longer can make changes to the response...

So how do you add a header at the end of a response?

I was hoping the following would work;

context.Response.OnStarting(async () => {
context.Response.Headers.Add("XResponseTime", "value");
});

**Comment by Tratcher** [comment]
Yes, that is the recommended approach. OnStarting is your last chance to modify the response headers. Make sure you register it before calling the next middleware, as it may be fired as soon as Response.Body.Write is called.

**Comment by Fosol** [comment]
This works for MVC endpoints but doesn't appear to work for static files.

**Comment by Tratcher** [comment]
Is your middleware before or after the static files middleware in the pipeline? It needs to before.

**Comment by Fosol** [comment]
My middleware is before UseStaticFiles().

I always get this exception;
```
The response has already been sent and cannot be modified.
```

**Comment by rynowak** [comment]
@Tratcher - does the sendfile feature possibly trample on this event?

**Comment by Tratcher** [comment]
It shouldn't. Are you using WebListener or Kestrel?

**Comment by Fosol** [comment]
The particular app is still beta7.  I haven't had time to migrate it yet.  It's running in IIS Express presently since we haven't deployed it.
```
"web": "Microsoft.AspNet.Hosting --config hosting.ini"
```

**Comment by Tratcher** [comment]
Ah yes there was a bug with SendFile skipping OnSendingHeaders in IIS/Express on beta7. Our old IIS component was obsoleted in beta8 so this is no longer an issue.

**Comment by Fosol** [comment]
Music to my ears!  When I get a chance I'll test.  If I see any other related issues I'll repost.
