### ISSUE TITLE
Startup - Handle Exceptions

### ISSUE THREAD

**Issue by Fosol** [aspnet/HttpAbstractions#484]
I'd like to know how to handle exceptions on Startup so that I can return an appropriate error page within MVC (if possible).

I also want to be able to check for invalid configuration values and return an appropriate error page.  My specific use case is when private keys for authentication and authorization are incorrect or missing.   I want to be able to get the server up and running without them but force an error page as the response to any request.

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Hosting#486
