### ISSUE TITLE
Missing Properties in HttpResponse class

### ISSUE THREAD

**Issue by tenor** [aspnet/HttpAbstractions#486]
It seems there are two missing properties in the `Microsoft.AspNet.Http.HttpResponse` class and its default implementation.

There are no StatusDescription(ReasonPhrase) and Protocol properties.

StatusDescription can't be read from `HttpContext.Response`. It *can* be read by looking up the `IHttpResponseFeature.ReasonPhrase` property.
There is a StatusCode property in `HttpResponse`, so why isn't there StatusDescription?

There is also no way to read the response Protocol. 
I'm referring to the 'HTTP/1.1' in the first response line: 'HTTP/1/1 200 OK' 
The property doesn't exist in either `HttpResponse` or `IHttpResponseFeature`.

Krestel writes the protocol that was read in the request to the response stream. (see `CreateResponseHeader` method)
This is a fair assumption to make right now, but may not hold true in the future or in a different implementation.
I think those two protocols should be kept separate and middleware should be allowed to modify the Response protocol.

I'd argue that these two properties should be in the `HttpResponse` class since they are part of any HTTP response.

My proposal in summary:

1. Add `StatusDescription` to `HttpResponse`.
2. Add `Protocol` to `HttpResponse` and `DefaultHttpResponse`.
3. Add `Protocol` to `IHttpResponseFeature` interface.

**Comment by Tratcher** [comment]
I've explained our reasons for excluding ReasonPhrase here: https://github.com/aspnet/HttpAbstractions/issues/395#issuecomment-139328869

Setting the protocol is similar, there's very few reasons to ever do so. It may make sense as an advanced feature on IHttpResponseFeature but it should not be added to HttpResponse.

**Comment by tenor** [comment]
That makes sense. StatusDescription can still be set through IHttpResponseFeature and only the Server can set Protocol.

I do think that the way Kestrel shares Protocol between Request and Response is error-prone.
Kestrel might respond to `GET / UNKNOWN/1.1` with `UNKNOWN/1.1 400 Bad Response`.

**Comment by muratg** [comment]
Thanks @tenor!  Keeping this open in the backlog to look into potential issues with Kestrel sharing Protocol between Request and Response.

**Comment by tenor** [comment]
You're welcome!
