### ISSUE TITLE
Remove Session from HttpContext

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#488]
Can we have it be a scoped service instead?  Added via AddSessionServices. If not, could we just make leave it as a feature instead of having it as a first class property? It could be an extension method to get at it.

/cc @lodejard @Tratcher

**Comment by Tratcher** [comment]
The scoped service sounds complicated as it would still have to depend on the current request to get and set headers.

Why do you want to drop the property?

**Comment by davidfowl** [comment]
Because I don't think it makes sense to expose on the Context. I think MVC can expose it on the Controller but it feels pretty out of place.

**Comment by glennc** [comment]
@davidfowl @loudej We aren't doing this now right?

**Comment by davidfowl** [comment]
@glennc @Tratcher I want to revisit this again. We could just remove the property from HttpContext. It could just work the same way it does today but would require `Get<ISessionFeature>().Session`. 

Alternatively we can add `ISessionAccessor` that has a session property. It would be a scoped service that the session middleware adds an sets. It does not need to be on the HttpContext itself.

**Comment by muratg** [comment]
Assigning to @JunTaoLuo.  @Tratcher what are your thoughts on @davidfowl's latest proposal?

**Comment by Tratcher** [comment]
Not impressed... It's not broken, don't fix it.

**Comment by davidfowl** [comment]
> Not impressed... It's not broken, don't fix it.

Not sure what you mean.

**Comment by Tratcher** [comment]
You haven't identified any problems you're trying to solve, so it looks like you're just trying to make the feature harder to use.

People have used it and the only questions they ask are about setting up the caching services and serializing data. This addresses neither.

**Comment by davidfowl** [comment]
It's a rarely used feature to begin with and optional by default unlike the other first class properties on HttpContext. The current session implementation is also very hard for mere mortals to use so moving it off HttpContext might be a good way to give us time to see if that interface makes sense in the long run. If it's just another feature then it's just as "functional" but a little less first class.

>  People have used it and the only questions they ask are about setting up the caching services and serializing data. This addresses neither.

That's unrelated to this particular issue. It also needs to be solved for more than just session. It's about storing complex objects in a distributed cache, session just happens to be one consumer.

**Comment by Tratcher** [comment]
If you want to isolate it then the simplest approach (with least user impact) is to convert the HttpContext.Session property to a GetSession extension method. You may or may not also choose to move the feature interfaces to a Session.Abstractions package.

If your confidence in the design is that low, should Session also be put on the pre-release-at-rtw list? (Except MVC depends on it).

**Comment by muratg** [comment]
Decided not to do this.
