### ISSUE TITLE
IHeaderDictionary should implement IDictionary<string, IEnumerable<string>>

### ISSUE THREAD

**Issue by tenor** [aspnet/HttpAbstractions#490]
Why does `IHeaderDictionary` implement `IDictionary<string, StringValues>`? 

I see that `StringValues` is implicitly convertible from `string[]`, but that means the developer is forced to use either `StringValues` or `string[]` when setting headers.

I propose that `IHeaderDictionary` implement `IDictionary<string, IEnumerable<string>>` and have the default `HeaderDictionary` class use `StringValues` internally to store values.

**Comment by davidfowl** [comment]
> Why does IHeaderDictionary implement IDictionary<string, StringValues>?

Here's the announcement https://github.com/aspnet/Announcements/issues/60 

> I see that StringValues is implicitly convertible from string[], but that means the developer is forced to use either StringValues or string[] when setting headers.

Forced? The developer can set either a string or string[] just fine. Not sure why that's a problem.

> I propose that IHeaderDictionary implement IDictionary<string, IEnumerable<string>> and have the default HeaderDictionary class use StringValues internally to store values.

We're not going to make a design change like that now. We made the StringValues change so that we could efficiently represent header values being one or many and possibly next (https://github.com/aspnet/Common/issues/64) raw binary.

Having this value types gives us this kind of flexibility.

**Comment by tenor** [comment]
There's an issue of discoverability:

Say, I am a developer trying to set a header:

I type `Response.Headers.Add(`
At this point, Intellisense informs me that I need a `StringValue`.
I'm not going to stop and learn about the `StringValue` type. I'll just new one up and end up with code that looks like:

`Response.Headers.Add("myHeader", new StringValue("One"));`

This might not seem so bad but it would have been easier if I could just pass an `IEnumerable<string>` which everyone is familiar with and not have `StringValue` bleed into my application.

The other issue is that `StringValue`'s constructor accepts either a string or a string array.
This really forces developers to add .ToArray() to a collection before they can pass it to `StringValue`.
It seems that `StringValue` wants to be as transparent as possible, but it really should also accept `IEnumerable<String>` in the constructor (with an implicit conversion defined as well).

My overall point is that developers should not be burdened with an internal type. It really ought to be an implementation detail.

On ([aspnet/Common#64](https://github.com/aspnet/Common/issues/64)), It seems to me that this has little to do with `StringValues` and is more about having the header dictionary store headers in binary. Overloading this feature into `StringValues` creates a 'stringy' type that does not have a consistent behavior. Some items can be read as a UTF-16 string and some items are just bytes that only make sense in some other encoding.

**Comment by davidfowl** [comment]
The first point is actually a fair one and we discussed it quite a bit when we originally added the type but our examples will all show setting a string value or string array. It's something we're going to document.

> My overall point is that developers should not be burdened with an internal type. It really ought to be an implementation detail.

Except, it's not an internal type.

> On (aspnet/Common#64), It seems to me that this has little to do with StringValues and is more about having the header dictionary store headers in binary. Overloading this feature into StringValues creates a 'stringy' type that does not have a consistent behavior. Some items can be read as a UTF-16 string and some items are just bytes that only make sense in some other encoding

Not really. The type is constructed with a string and an encoding. The original value is preserved so all of the other operations work well. It's just a way for user code to pre-encode bytes and possibly cache for reuse.

Like I said before, at this point, we're not going to change the API to `IEnumerable<string>` but we should better document the expected usage of `StringValues` in the `IHeaderDictionary`. 

/cc @danroth27

**Comment by muratg** [comment]
As @davidfowl says, this will not change for V1.  Closing this.

**Comment by muratg** [comment]
@danroth27 Can we document this please?
