### ISSUE TITLE
Can't enumerate the FeatureCollection because it throws NotImplementedException

### ISSUE THREAD

**Issue by AspNetSmurfLab** [aspnet/HttpAbstractions#494]
Caused by https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Features/FeatureCollection.cs#L105 and https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Features/FeatureCollection.cs#L89 I'm guessing

**Comment by BrennanConroy** [comment]
5e42d26fd536ea7fbca7e3b30eb593fe876e462b
