### ISSUE TITLE
No easy way to get file names in  IFormFileCollection / IFormFile

### ISSUE THREAD

**Issue by Yves57** [aspnet/HttpAbstractions#499]
When using `IFormCollection`, it is easy to get the form keys.
But when working with the `IFormFileCollection` interface, there is not way to get all form names and file names (somehing like `IFormCollection.Keys` / `IFormCollection.FileNames`) or at least two properties `IFormFile.FileName` and `IFormFile.Name`.
I have found a workaround (using `ContentDispositionHeaderValue` like in the `FormFileCollection` class, but it is not very fun to use.

**Comment by davidfowl** [comment]
We need to expose the Name on IFormFile.

**Comment by khellang** [comment]
@davidfowl Submitted #500

**Comment by Yves57** [comment]
Only few hours to fix the issue. Thank you!
