### ISSUE TITLE
FormFile missing FileName/Name

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/HttpAbstractions#505]
I'm looking at the FormFile trying to obtain the FileName, the ContentDisposition value is "form-data; name=\"file\"; filename=\"AI Procurement - Database Analysis.docx\" yet the FormFile.FileName is not present?

**Comment by davidfowl** [comment]
It'll be in rc2

**Comment by grahamehorner** [comment]
@davidfowl thanks for your quick response; hope your feeling better after your food posioning.  do you know if this is currently a WIP item or included in the nightly build of RC2?

**Comment by khellang** [comment]
@grahamehorner This was included with #500. It should be part of the `1.0.0-rc2-16026` (or newer) package in the https://www.myget.org/F/aspnetcidev/api/v3/index.json feed :smile:

**Comment by grahamehorner** [comment]
@khellang thanks
