### ISSUE TITLE
Quirk with MapMiddleware when exception propagates outside of the branch

### ISSUE THREAD

**Issue by tuespetre** [aspnet/HttpAbstractions#510]
Here is a sample project:

https://github.com/tuespetre/aspnet-map-quirk

The issue may be reproduced with that project with the following steps:

1. Run the application, using either `dnx web` or the IIS Express option from Visual Studio
2. Load the page in the browser
3. Click the button to send a request to the page that will raise an exception
4. Send further GET requests to the page

The symptom is that, after having raised the exception, the `PathBase` of the request will be intermittently doubled up, resulting in broken links. Having stepped through the `MapMiddleware`'s `Invoke` method, I can see that the `context.Request.PathBase` is already set to `/aspnet-map-quirk` coming into the middleware, even though the request URI shows properly as `/aspnet-map-quirk` when inspecting the `Features` collection on the `HttpContext.` I am not sure if this is due to faulty context recycling on part of Kestrel or not, as I don't know much about Kestrel -- perhaps @davidfowl or @DamianEdwards would have something to say here. 

The workaround is to uncomment the following line:
https://github.com/tuespetre/aspnet-map-quirk/blob/master/AspNetMapQuirk/Startup.cs#L21

This prevents the exception from propagating out of the branch and subsequently causing the issue with the doubled-up `PathBase`.

A `try ... finally` block within `MapMiddleware`'s `Invoke` method would ultimately guard against this issue.

**Comment by Tratcher** [comment]
@BrennanConroy Add the try/finally.

@halter73 Is kestrel failing to reset the Frame for unhandled exceptions?

I would expect symptoms like this if you were using the UseErrorHandler middleware that re-executes the pipeline.

**Comment by BrennanConroy** [comment]
I don't see this issue in RC2, but I saw it in RC1

**Comment by Tratcher** [comment]
The original repro may have been caused by Kestrel.  What if you use the ErrorHandler middleware that re-executes? It should still cause this.
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Abstractions/Extensions/MapMiddleware.cs#L62
Add the try/finally.

**Comment by BrennanConroy** [comment]
c41be75796d9c81d9dde079c45958a2d54c31a63

**Comment by tuespetre** [comment]
Thanks!

**Comment by Tratcher** [comment]
Kestrel fix: https://github.com/aspnet/KestrelHttpServer/pull/412/files#diff-3ad18666c41931c02b7bd1f3226cb709R204
