### ISSUE TITLE
Application_End equivalent

### ISSUE THREAD

**Issue by tenor** [aspnet/HttpAbstractions#513]
Is there an equivalent model for `Global.Application_End` in ASP.NET 5?
I'm looking for a way to dispose resources when the application stops.

I see `IApplicationLifeTime` is available at the server level but it's not exposed at the app level.
Can this be exposed in `IApplicationBuilder` so that components can subscribe to `applicationStopped/Stopping` in `Startup.Configure`?

**Comment by benaadams** [comment]
Take `IApplicationLifetime` as a parameter to Configure and the dependency injection will do the rest

**Comment by tenor** [comment]
Very cool! Thanks @benaadams
