### ISSUE TITLE
Response stream buffering

### ISSUE THREAD

**Issue by ChristianRiedl** [aspnet/HttpAbstractions#514]
How can I control ResponseStream buffering ? I would like to disable buffering in some cases.
Where are the 'Microsoft.AspNet.Server.Weblistener' sources ? I was not able to find it.

Thanks

**Comment by Tratcher** [comment]
`httpContext.Features.Get<IHttpBufferingFeature>().DisableResponseBuffering()`
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Features/IHttpBufferingFeature.cs

Weblistener is not yet open source. /cc: @Eilon
