### ISSUE TITLE
A NullRefereceException in Blob's UploadFromStreamAsync() Func

### ISSUE THREAD

**Issue by duanjian** [aspnet/HttpAbstractions#517]
hello,  when i use 

IFormFile's  file.OpenReadStream() get the stream 

then use 

```C#
var bBlob = _container.GetBlockBlobReference(path);
await bBlob.UploadFromStreamAsync(streamInput);
```

```
and got a NullReferenceException
the StackTrace is 

   在 Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() 位置 c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:行号 77
   在 Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar) 位置 c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:行号 115

   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 Schubert.Framework.FileSystem.AzureBlobFileStorage.<CreateBlobFromStream>d__5.MoveNext() 位置 C:\Users\duan\Source\Workspaces\Labijie\ProgrameFramework\Schubert_V1\src\Framework\Schubert.Framework.Azure\FileSystem\AzureBlobFileStorage.cs:行号 46

   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Schubert.Framework.FileSystem.AzureBlobFileStorage.<CreateFileAsync>d__10.MoveNext() 位置 C:\Users\duan\Source\Workspaces\Labijie\ProgrameFramework\Schubert_V1\src\Framework\Schubert.Framework.Azure\FileSystem\AzureBlobFileStorage.cs:行号 118

   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```
in bata8 has no this problem , thank u

**Comment by davidfowl** [comment]
I don't see ASP.NET on the call stack. Why do you think this is an ASP.NET bug? Is the stream null?

**Comment by duanjian** [comment]
@davidfowl 
bata8 is ok 
the stream is not null 
got this problem is after upgrade to rc2

**Comment by davidfowl** [comment]
Did you update the azure sdk? Could it be a bug in there?

**Comment by duanjian** [comment]
@davidfowl 
the azure sdk's version is 2.7  
need to update the azure sdk?

**Comment by davidfowl** [comment]
I don't know. I'm saying that it doesn't look like an ASP.NET issue. If you copied the stream you get from ASP.NET to disk, does it fail the same way?

**Comment by duanjian** [comment]
@davidfowl 
i copied the stream get from ASP.NET to disk has no this exception , i will try to update the azure sdk.

**Comment by davidfowl** [comment]
Doesn't seem asp.net related

**Comment by pemari-msft** [comment]
@davidfowl it seems that IFormFile's stream returns `true` for `.CanSeek` even though it's not seekable. Can you confirm this?

**Comment by Tratcher** [comment]
@pemari-msft It should be seekable.
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/Features/FormFile.cs#L71
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/ReferenceReadStream.cs#L82
There are some limitations though if the buffering is incomplete:
https://github.com/aspnet/HttpAbstractions/blob/02363da94eee7311e457e136dc45edf9c5ac3494/src/Microsoft.AspNetCore.WebUtilities/FileBufferingReadStream.cs#L100
