### ISSUE TITLE
Make IFeatureCollection have generic<T> accessor 

### ISSUE THREAD

**Issue by benaadams** [aspnet/HttpAbstractions#522]
Rather than [have it as an Extension](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Features/FeatureCollectionExtensions.cs#L14); so the [type of checks](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/Http/Frame.Generated.cs#L64) in `Frame.FastFeatureGet(Type key)` becomes `typeof` checks of `T` in `Frame.FastFeatureGet<T>()` 

At that point they also become compile time constants meaning 90% of the time the entire method will be Jitted away - as per the `typeof` checks in [System.Numerics.Vectors](https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Vectors/src/System/Numerics/Vector.cs#L18)

**Comment by benaadams** [comment]
Also the runtime `typeof` rather than compile time `typeof` is an expensive beast

![runtime-typeof](http://aoa.blob.core.windows.net/aspnet/runtime-typeof.png)

As its 85% of the cost of the Get call on FeatureCollection

**Comment by martinbliss** [comment]
+1 for education, convenience, and extending GOOD patterns and practices.

**Comment by benaadams** [comment]
Test results

                Method |    AvrTime |    StdDev |          op/s |
---------------------- |----------- |---------- |-------------- |
 GenericTypeOfFunction | 35.1454 ns | 0.1927 ns | 28,454,009.51 |
        TypeOfFunction | 76.7849 ns | 1.2194 ns | 13,026,620.11 |
          TypeOfLookup | 92.7875 ns | 0.1476 ns | 10,777,342.57 |

https://gist.github.com/benaadams/c6c109982f50c6f69af2#gistcomment-1657847

**Comment by benaadams** [comment]
Results

          Method |     AvrTime |    StdDev |          op/s |
---------------- |------------ |---------- |-------------- |
   GenericTypeOf |  35.0250 ns | 0.5992 ns | 28,559,229.82 |
          TypeOf | 103.6239 ns | 0.3279 ns |  9,650,377.23 |
 TypeOfExtension | 140.4318 ns | 2.3503 ns |  7,122,799.75 |

https://gist.github.com/benaadams/c6c109982f50c6f69af2

**Comment by benaadams** [comment]
Updated results and methods

https://gist.github.com/benaadams/c6c109982f50c6f69af2#gistcomment-1657847

                        Method |     AvrTime |    StdDev |          op/s |
------------------------------ |------------:|---------- |--------------:|
               NoBranchingCast |  26.9415 ns | 0.5009 ns | 37,129,998.18 |
             NoBranchingAsCast |  27.7353 ns | 0.0483 ns | 36,055,296.46 |
 GetGenericExtensionCastInline |  27.3106 ns | 0.0365 ns | 36,615,855.50 |
        GetGenericClassWrapped |  50.6726 ns | 0.8665 ns | 19,740,174.53 |
       GetGenericExtensionCast |  58.9959 ns | 0.0298 ns | 16,950,345.39 |
       GetGenericStructWrapped |  63.5347 ns | 0.0668 ns | 15,739,445.84 |
                GetGenericCast |  97.1922 ns | 0.1434 ns | 10,288,916.32 |
        GetGenericStructUnwrap |  97.9715 ns | 1.6985 ns | 10,210,053.51 |
         GetGenericClassUnwrap |  98.6284 ns | 0.1372 ns | 10,139,086.32 |
        GetTypeOfExtensionCast  *(current)* | 147.9895 ns | 2.6713 ns |  6,759,391.15 |
                  GetGenericAs | 162.8011 ns | 2.8732 ns |  6,144,292.82 |
        GetGenericExtenstionAs | 174.7144 ns | 0.1204 ns |  5,723,630.47 |
          GetTypeOfExtensionAs | 221.3632 ns | 6.3888 ns |  4,520,834.53 |

**Comment by benaadams** [comment]
Actually, might be able to work round this with `Frame`

**Comment by halter73** [comment]
@benaadams So where did you land on this? If we we change `IFeatureCollection` so we can pass `TFeature` as a generic parameter all the way down to `FastFeatureGet` in Kestrel where the if statements can look like this:

            if (typeof(TFeature) == typeof(global::Microsoft.AspNet.Http.Features.IHttpRequestFeature))

Will the JIT compiler perform branch elimination despite `TFeature`s all being reference types and the method being accessed through the `IFeatureCollection` interface? Do we do it anyway so we can avoid the creation of a runtime type object?

**Comment by benaadams** [comment]
Still working on it; the jit does do the branch elimination if the method is extracted locally rather than a call (i.e. inlined) regardless of them being reference types.

However; it won't inline via an interface. Nor will it inline a virtual method (so subclassing won't work either).

Will add going via an interface to the tests and see if generics are still faster. Also have an idea on how to get the branch elimination working still...

**Comment by benaadams** [comment]
The changed interface implementation of FeatureCollection seems to cause the Jit to change inlining, and no longer inline the agressive inline method :-/

                         Method |     AvrTime |     StdDev |           op/s |        |
------------------------------- |------------ |----------- |--------------- |-------:|
       GetConcreteStructWrapped |   7.5178 ns |  0.1262 ns | 133,054,091.49 | 2263.0%
                NoBranchingCast *(baseline)* |  29.2430 ns |  0.2302 ns |  34,198,218.52 | 507.3%
              NoBranchingAsCast *(baseline)* |  32.2000 ns |  0.1380 ns |  31,056,481.25 | 451.5%
               INoBranchingCast *(baseline)* |  39.2279 ns |  0.4047 ns |  25,494,653.98 | 352.8%
      IGetConcreteStructWrapped |  55.1374 ns |  0.2007 ns |  18,136,746.06 | 222.1%
        GetGenericStructWrapped |  76.5400 ns |  1.2237 ns |  13,068,333.88 | 132.1%
                 GetGenericCast |  97.8845 ns |  1.7258 ns |  10,219,152.21 | 81.5%
         GetGenericStructUnwrap | 103.8999 ns |  1.9795 ns |   9,627,983.16 | 71.0%
  GetGenericExtensionCastInline | 109.8775 ns |  1.8892 ns |   9,103,677.66 | 61.7%
        GetGenericExtensionCast | 111.2737 ns |  0.3054 ns |   8,986,912.43 | 59.6%
       IGetGenericStructWrapped | 123.6148 ns |  2.0920 ns |   8,091,910.21 | 43.7%
                IGetGenericCast | 156.4677 ns |  0.3672 ns |   6,391,129.96 | 13.5%
                   GetGenericAs | 158.7277 ns |  2.6942 ns |   6,301,874.13 | 11.9%
        IGetGenericStructUnwrap | 160.7520 ns |  2.8691 ns |   6,222,654.29 | 10.5%
 IGetGenericExtensionCastInline | 164.4973 ns |  4.6456 ns |   6,083,670.51 | 8.0%
       IGetGenericExtensionCast | 167.3065 ns |  4.3638 ns |   5,980,989.43 | 6.2%
         GetTypeOfExtensionCast | 171.1575 ns |  2.9481 ns |   5,844,228.66 | 3.8%
         GetGenericExtenstionAs | 174.9372 ns |  0.5404 ns |   5,716,391.21 | 1.5%
        IGetTypeOfExtensionCast  *(current)* | 178.2726 ns | 12.2992 ns |   5,630,807.91 | --
           GetTypeOfExtensionAs | 239.1550 ns |  2.6341 ns |   4,181,875.96 | -25.7%

Fastest now being `IGetConcreteStructWrapped` which causes a concrete implementation of the generic function rather than a shared method.

Generic's via the interface without extension (IGetGenericCast) are 13.5% faster. Wrapping in a non-generic struct via interface is 222.1% faster; think can get there via the generic interface method.

**Comment by benaadams** [comment]
Hmm... no, as you'd need to lookup the concrete struct to use, which would put you back in the original situation :-/
