### ISSUE TITLE
Share StreamCopyOperation implementations

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#528]
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNet.Http.Extensions/StreamCopyOperation.cs
https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNet.StaticFiles/StreamCopyOperation.cs

**Comment by glennc** [comment]
If StaticFiles already uses Http.Extensions then we should just use that location, otherwise find somewhere else for it to live.

**Comment by davidfowl** [comment]
Internal helper in common?

**Comment by BrennanConroy** [comment]
We can make it public in Http.Extensions since StaticFiles already depends on that and then we'll copy Ben's changes to the StaticFiles one over to Http.Extensions

**Comment by BrennanConroy** [comment]
Fixed via 3f84e992f48f52d86404732915ebe86bfdd2a610
