### ISSUE TITLE
Remove IsLocal

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#536]
We keep getting questions like this: https://github.com/aspnet/Hosting/issues/570#issuecomment-171571555

Environments are the correct way to handle these scenarios most of the time.

We should remove IsLocal, and possibly replace it with an extension method that just returns RemoteIP.Equals(LocalIP).

@davidfowl @muratg @blowdart

**Comment by blowdart** [comment]
Yea, kill it IMO

**Comment by davidfowl** [comment]
> We should remove IsLocal, and possibly replace it with an extension method that just returns RemoteIP.Equals(LocalIP).

If we add it back as an extension method won't be in the same place? It seems like an OK thing to remove from `ConnectionInfo` though.

**Comment by Tratcher** [comment]
Current recommendation is to remove it without adding an extension.

**Comment by muratg** [comment]
Yup, no extension method. This was redundant anyway.

**Comment by BrennanConroy** [comment]
Fixed via 1f21540fd53a839dcfe7004788abe1e9a1d820a4

**Comment by dazinator** [comment]
I found this useful for authorising a user based on if it is a Local request or not. I am aware that this information (ip address) could be spoofed, but I am happy to accept that risk given that this functionality is in place only when the web application is first installed, and it treats the local user as a local admin whilst they set up the site, and blocks non local requests.

What's the replacement?

**Comment by Tratcher** [comment]
IsLocal is more dangerous than it once was because of the prevalence of local reverse proxies (e.g. Nginx, HttpPlatformHandler, AspNetCoreModule, etc.), most requests now appear to be local.

How would your setup process work for a site deployed to a hoster like Azure Web Sites where there is no local access?

Consider using a Staging Environment mode or real credentials based authentication.

**Comment by dazinator** [comment]
@Tratcher understood. If there is a chance of IsLocal no longer being accurate then I don't wish to use it. I'll have to re-think my setup process. :(

**Comment by blowdart** [comment]
So what I've seen working for some folks is

1. Check for the presence of a marker file or database entry to see if already configured. If present goto 6.
2. Check for the presence of a first run password in a settings file, if not present throw error with instructions on how to set it. Never set a default one in any installer.
3. Login page which asks for the setup password
4. Run setup
5. Drop the "I've been configured" marker
6. Profit.

**Comment by dazinator** [comment]
@blowdart haha thanks - I like that suggestion, Team City uses that concept too, it generates an system admin login token which it writes to a local log file. Cheers
