### ISSUE TITLE
Don't make things null in Dispose

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/HttpAbstractions#540]
src/Microsoft.AspNet.WebUtilities/HttpRequestStreamReader.Dispose nulls out properties. According to @Tratcher https://github.com/aspnet/HttpAbstractions/pull/539#discussion_r49917289 we should instead set up a disposed bool so we don't accidentally get nullrefs.

**Comment by rynowak** [comment]
Not against following a more traditional pattern if it makes people happy, but look closer at the code. The stream null-check is used where you'd normally see `if (_disposed)` it's functionally the same.

**Comment by Tratcher** [comment]
Until there are race conditions, then null refs. It's a defensive practice. Nulling things out doesn't help the gc in any meaningful way.

**Comment by muratg** [comment]
Moving this to Backlog as we will be in RC2 ask mode very soon.  If you feel strongly about this issue, please ping me.
