### ISSUE TITLE
Allocations in FileBufferingReadStream

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpAbstractions#548]
It would be nice to use buffer-pooling for buffering of form-data. This shows up as perf-sensitive in a bunch of MVC scenarios:

![image](https://cloud.githubusercontent.com/assets/1430011/12692914/8299ff96-c6b3-11e5-95c2-f254530f354b.png)

If we're not going to use the pool for this, we could consider choosing an initial size based on the Content-Length (with a limit of course). The above shows reallocations (3000 requests).

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/HttpAbstractions/issues/545

**Comment by SajayAntony** [comment]
:fearful:  per request [MemoryStreams](https://github.com/aspnet/HttpAbstractions/blob/02363da94eee7311e457e136dc45edf9c5ac3494/src/Microsoft.AspNetCore.WebUtilities/FileBufferingReadStream.cs#L24) 
Given that it is a REPLAY type stream it would definitely be worth pooling and you already dispose file resources on dispose so pooling with return makes sense since you already have resource clean up semantic in ```FileBufferingReadStream```

**Comment by muratg** [comment]
@DamianEdwards Do we want to take more perf improvements in RC2?

**Comment by DamianEdwards** [comment]
@muratg if we have capacity to (i.e. devs have no other work pertaining to moving to .NET Core CLI and getting our core scenarios working) then by all means.

**Comment by benaadams** [comment]
Should be resolved by #550, except when content is buffered to disk; which needs this issue resolving in corefx dotnet/corefx#5598 

This is due to FileStream's internal buffer is not being exposed/settable.

**Comment by benaadams** [comment]
The buffer pool changes in #550 (superseded by #556) mean these allocations just no longer exist

e.g. for 30,000 requests - `byte[]` allocations are as follows

![allocs](http://aoa.blob.core.windows.net/aspnet/bufferpool-2.png)

**Comment by muratg** [comment]
Nice!

**Comment by Tratcher** [comment]
https://github.com/aspnet/HttpAbstractions/commit/bd60507dcd317f2c1f42da37afd9dbc928f50928
