### ISSUE TITLE
FormReader creates x2 strings when parsing

### ISSUE THREAD

**Issue by benaadams** [aspnet/HttpAbstractions#552]
BuildWord creates a string to pass to Uri.UnescapeDataString which then creates another string as experienced in https://github.com/aspnet/Mvc/issues/4016

**Comment by rynowak** [comment]
I re-ran my benchmark after some model binding changes and don't see a whole heck of a lot of allocations coming from this callstack

![image](https://cloud.githubusercontent.com/assets/1430011/12822280/3666ac2e-cb1c-11e5-934a-3ba3c6df3526.png)

It's probably because most of my strings are on the happy path (don't need escaping).

**Comment by benaadams** [comment]
The change is for both sync and async as its a change to `BuildWord` specifically from
```
        private string BuildWord()
        {
            _builder.Replace('+', ' ');
            var result = _builder.ToString();
            _builder.Clear();
            return Uri.UnescapeDataString(result); // TODO: Replace this, it's not completely accurate.
        }
```
to
```
        private string BuildWord()
        {
            if (_builder.Length == 0)
            {
                return string.Empty;
            }
            var result = UrlDecode(_builder, _bytePool, _charPool);
            _builder.Clear();
            return result;
        }
```

**Comment by benaadams** [comment]
Ah, see what you mean

**Comment by rynowak** [comment]
I'm not saying don't fix it :trollface: this is definitely a step in the right direction.

**Comment by benaadams** [comment]
Not sure about my implementation :-/

**Comment by benaadams** [comment]
Actually issue, is valid, solution isn't - corefx issue: https://github.com/dotnet/corefx/issues/5888

**Comment by muratg** [comment]
Putting this in 1.0.0 for consideration post RC2.

**Comment by Eilon** [comment]
Talked to @rynowak and this is just within the implementation details of form reading, so moving to post-1.0.0.

**Comment by muratg** [comment]
@rynowak Are you planning to look into this more?

**Comment by muratg** [comment]
@davidfowl Were you looking into this?

**Comment by muratg** [comment]
Closing per triage decision.

**Comment by muratg** [comment]
Closing per triage decision.
