### ISSUE TITLE
Allocations in FormReader

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpAbstractions#553]
#### There's a lot of overhead right now in FormReader

Data is from 3000 requests to https://github.com/aspnet/Performance/tree/dev/testapp/BigModelBinding (x64). The client is doing a form post of about 100 form fields - we kinda consider this the upper bound for the amount of data (and shape of data) that you'd want to put through MVC model binding.

![image](https://cloud.githubusercontent.com/assets/1430011/12822124/596eacc2-cb1b-11e5-8448-167d49b4d552.png)

Based on this profile, my napkin math shows about 77mb of allocations from our underlying representation (`string` + `System.Collections.Generic.Dictionary<String, StringValues>` + etc) and about 122mb coming from various overheads.

I'm excluding from the 122mb stuff that's in theory covered by @benaadams current work (byte/char buffers, etc).

------------------

##### `Task<string>` - 47mb
![image](https://cloud.githubusercontent.com/assets/1430011/12822658/e7b6d598-cb1d-11e5-82d5-47885f6604e3.png)
Cost of being async

##### `Task<Nullable<KeyValuePair<string, string>>>` - 28mb
![image](https://cloud.githubusercontent.com/assets/1430011/12822696/1859fee6-cb1e-11e5-89b0-62d885221ebf.png)
Cost of being async

##### `Dictionary<string, List<String>>`, `List<string>`, `string[]` - 25mb 12mb 9mb
![image](https://cloud.githubusercontent.com/assets/1430011/12822782/80c70b86-cb1e-11e5-9c37-fefecead57de.png)
Scratch data used in `KeyValueAccumulator` to build the final `Dictionary<string, StringValues>`

Note that 5mb of `string[]` allocations are coming from a hashset in MVC, so I excluded it from this total

==================

##### Some thoughts

We should consider a design for `FormReader` where we pass the accumulator around or store values in fields/properties instead of returning them via `Task<T>`. Using `async` plus `Task<T>` at such a chatty level is what causes all of this overhead. Using `Task` on the other hand can avoid this issue. 

If we're in a state where we know the entire body is buffered in memory, we might want to just optimize that path to do a synchronous read. That's probably a simpler fix, and it will result in running much more efficient code without *any* async overhead.

We should also consider changing `KeyValueAccumulator` to just operate on `Dictionary<string, StringValues` directly. Having multiple values for the same fields is the less-common case.  If we wanted to be smart about it, we could basically build `List<T>`'s resizing behavior into a `StringValues.Add` method (returns a `StringValues` since they are immutable), and then all cases would be pretty optimal. 

Right now we're making the worst case the common case by allocating a `List<string>` and `string[]` for the common case of a single value per key.

**Comment by benaadams** [comment]
`ValueTask` would also be an option here its also the exact scenario it was designed for.

**Comment by benaadams** [comment]
Though `TextReader` is `Task` rather than `ValueTask` :(

**Comment by benaadams** [comment]
#554 + #556 *should* hopefully resolve all of the above

**Comment by rynowak** [comment]
Would it be better overall to just make formreader a "push" parser? Using value task might kill the allocs, but it's still a lot of code to run. We could also avoid a second pass on the "output" stream.

Pseudocode:
Stream input = ...;
Stream output = ...; // our buffered stream
byte[] bBuffer = ...;
char[] cBuffer;
Decoder decoder;
FormReader formReader = ...;

while (await input.Read(bBuffer, 0, bBuffer.Length > 0)
{
    var chars = decoder.GetChars(...);
    formReader.Write(cBuffer, 0, chars);

   await output.WriteAsync(bBuffer, 0, bBuffer.Length > 0);
}

output.Seek(Begin, 0);
formReader.Complete();

**Comment by rynowak** [comment]
I'll do some profiling this AM. I want to see where reading form data fits in to the big picture in a sampling profile

**Comment by rynowak** [comment]
Some sampling data (same benchmark):

**MVC at a high level**

![image](https://cloud.githubusercontent.com/assets/1430011/12893206/b70e0478-ce44-11e5-9ef5-d2f19817ebe7.png)

The 100% in this case is time spend inside MVC+Routing (only negligible work done in other parts of the pipeline).

The 13.39% `AddValueProviderAsync` is the time spend reading the form data and building the form value provider. I'll provide a further drill-down here.
The 2.65% `AddValueProviderAsync` is the jQuery form value provider which parses and duplicates the form data keys for some reasons
The 80.05% `InvokeExceptionFilterAsync` is model binding + the action code

Some extras:
2.47% `InvokeResultFilterAsync` is JSON.Net outputting the same data as JSON.
About 1% of time spend on routing and other misc overhead to get to this point.

**Breaking down form reading**
![image](https://cloud.githubusercontent.com/assets/1430011/12893478/28d75f7c-ce46-11e5-90ef-17bc61922950.png)

There's a very small amount of overhead here between MVC and the form reader, I was surprised how small it was. So, reading and parsing the input is 13.29% of the request time. Let's drill in more.

**More drill in**
![image](https://cloud.githubusercontent.com/assets/1430011/12893717/9363b4c0-ce47-11e5-958e-5de472d32e38.png)

The bottom-up breakdown provided by dottrace is pretty instructive:
![image](https://cloud.githubusercontent.com/assets/1430011/12893731/b7b99aa6-ce47-11e5-9720-de2c74a6223e.png)

We're looking at a pretty significant amount of time spend in async/task overhead 11.63% spent in `AsyncMethodBuilder` and 17.95% in `<ReadWordAsync>...`s exclusive time. The call tree above clearly shows that all the methods called here were **not** inlined https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/FormReader.cs#L112 and are not included in the 17.95%. The fact that `StringBuilder.Append(char)` wasn't inlined seems like a red flag.


Additionally, another big cost is hashing. In the common case, we hash each key twice (once for a `TryGetValue` and again for an `Insert`. If we can find a way to avoid rehashing, that would be a significant gain (hashing was 18.75%).

**Comment by benaadams** [comment]
Is this pre or post change?

**Comment by benaadams** [comment]
Is this pre or post change? ValueTask should also kill a lot of the AsyncTaskMethodBuilder work

**Comment by benaadams** [comment]
Re: the high multi-hashing cost in [KeyValueAccumulator](https://github.com/benaadams/HttpAbstractions/blob/keyvalue-accul/src/Microsoft.AspNetCore.WebUtilities/KeyValueAccumulator.cs#L23-L61) for Dictionary @stephentoub proposed a `TryAdd` here https://github.com/dotnet/corefx/issues/1942 though it would probably need a `Func<TKey, TVal, TVal, TVal>` on the exists branch that has access to current & new value to avoid a closure, as that's where it does interesting things.

Other approach would be to not use `Dictionary` and use a different data structure - however that's more complicated as its also the return type (to allow struct enumerable rather than IEnumerable)

**Comment by rynowak** [comment]
@benaadams - well we're using dictionary as a multi-map, so really the best choice for us would be a dedicated multi-map type, or something like python's `dict` which lets you specify the default value for a key.

Really for our usage, a sorted list<kvp<string, *>> is probably more efficient overall than hashing.

**Comment by rynowak** [comment]
> Is this pre or post change? ValueTask should also kill a lot of the AsyncMethodBuilder work

This is without any of your changes I think.

**Comment by benaadams** [comment]
> if you're doing more than that, you've got an extreme scenario and your design is crazy.

Is user input though so want to avoid a data structure that might behave like this did http://www.troyhunt.com/2012/08/fixing-hash-dos-good-and-proper-and.html

**Comment by benaadams** [comment]
Actually `TryAdd` would probably cut a lot of these...

**Comment by stephentoub** [comment]
@benaadams, @rynowak, if the concern is that we need to frequently double-hash, have you considered storing a:
```C#
struct StringWithHash
{
    public int HashCode;
    public string Value;
    ...
}
```
as the key rather than a raw string?  You can either compute the hash upfront and store it in the struct, and override GetHashCode to return it, or you can compute the hash lazily in GetHashCode if it wasn't already computed.

**Comment by rynowak** [comment]
@stephentoub - that introduces yet another tradeoff, on the common-case path we're directly building the dictionary that's going to exposed to the user as `IDictionary<string, StringValues>`.

A custom dictionary implementation would get us out of this mess, but I'd rather try literally everything else first.

Do you have any thoughts on the `AsyncMethodBuilder` overhead? Will using `ValueTask<>` change anything there or is our best bet to rewrite this as a push parser?

**Comment by stephentoub** [comment]
> Do you have any thoughts on the AsyncMethodBuilder overhead?

Where in ```Async*MethodBuilder```?  And is this trace on full framework or CoreCLR?

> Will using ValueTask<> change anything 

Depends where the costs are.

**Comment by rynowak** [comment]
Snapshot from some similar data - 10% of execution time reading the form is in `AsyncMethodBuilder`:
![image](https://cloud.githubusercontent.com/assets/1430011/12954770/d2dc15d2-cfd4-11e5-9520-b51746c58791.png)

This is x64 CoreCLR 

**Call Tree**
![image](https://cloud.githubusercontent.com/assets/1430011/12954844/2021b3ce-cfd5-11e5-8416-0bc228b6f3f5.png)

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/FormReader.cs#L188

There's a parsing loop *around* async reads of a stream

**Comment by rynowak** [comment]
BTW @benaadams - this benchmark is here https://github.com/aspnet/Performance/tree/dev/testapp/BigModelBinding

`npm install -g loadtest` to get the driver
`dnx web`
modify `loadtest.ps1` to your liking

**Comment by stephentoub** [comment]
In that case, yes, I'd expect @benaadams' PR at https://github.com/aspnet/HttpAbstractions/pull/556 to help.

**Comment by benaadams** [comment]
@stephentoub some thoughts, not conclusions...

Not sure storing the hash code is possible; doesn't [Dictionary have randomised string hashing](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Dictionary.cs#L366-L372) for strings that was specifically introduced for aspnet and user-input, would hashing on an int cause issues? 

However, string does look like it uses `InternalMarvin32HashString` to generate the hashcode so it might be ok; but there is a lot of behaviour determined by `#if` in this area so am not entirely sure what the code paths are.

I did briefly look previously as to whether [string could cache its hash](https://github.com/benaadams/coreclr/commit/2915bb3ce8fb0d6df19d1c3018285839613e6da3) before realising the special relationship between `string` and `m_firstChar` would mean it would need changes in the C++ (also didn't know whether it was a viable overhead either adding it to every string - or how it would behave with previously interned strings, or whether dictionary would actually use it).

Not changing the public signature (e.g. returning `Dictionary<string, StringValue>`) but using `Dictionary<StringWithHash, StringValue>` internally would mean a double hash in the dictionary conversion and an extra dictionary create for the return. 

This could be hidden via implementing the interface `IDictionary<string, StringValues>` but it would need an additional `Dictionary<StringWithHash, StringValue>` return for those areas that want access to the struct enumerator (which is why its exposed as a `Dictionary` on the return currently) - then that type would be on the public api.

**Comment by benaadams** [comment]
@rynowak it wasn't happy with the wacky date format; so set it to 1st Jan, but have the tests working now

**Comment by benaadams** [comment]
@rynowak I'm getting degraded perf with  #556; but there is a lot of changes in it so investigating.

**Comment by benaadams** [comment]
Hitting disk; need to check if I changed the buffer default amount

**Comment by benaadams** [comment]
Hitting disk; due to different Length behaviour with fixed sized MemoryStream, correcting.

**Comment by benaadams** [comment]
Current

![current](http://aoa.blob.core.windows.net/aspnet/formreader-current.png)

With #556 (Buffers + ValueTask)

![valuetask](http://aoa.blob.core.windows.net/aspnet/formreader-next.png)

With both #554 + #556 (+ Accumulator)

![Accumulator](http://aoa.blob.core.windows.net/aspnet/formreader-combo.png)

So they all give a boost

**Comment by benaadams** [comment]
BufferAsync breakdown

![buffer-async](http://aoa.blob.core.windows.net/aspnet/buffer-async.png)

**Comment by benaadams** [comment]
Revisiting the original allocation issue from 30,000 requests (x10 on original)

![task-allocations](http://aoa.blob.core.windows.net/aspnet/formreader-allocations.png)

ValueTask basically eliminates the allocations (7MB vs 750MB)

**Comment by benaadams** [comment]
Re: Dictionary hashing on non string types https://github.com/dotnet/coreclr/issues/2279

**Comment by Tratcher** [comment]
Summary:
- Switching from Tasks to ValueTasks would help allocations, but requires writing your own state machine at 10x the code & complexity. Maybe Roslyn can do this for us? https://github.com/dotnet/roslyn/issues/7169
- There are still string hashing issues in the KeyValueAcumulator
