### ISSUE TITLE
Null RemoteIpAddress

### ISSUE THREAD

**Issue by eriksendc** [aspnet/HttpAbstractions#560]
Hi All,

I'm using RC1. When running under IIS Express locally or under IIS on Windows Server 2012 R2 the value for HttpContext.Connection.RemoteIpAddress is always null. Any clues? Also, I've seen [somewhat older] comments about using the following to access the remote ip address value:

string clientIpAddress;
var connection = context.HttpContext.GetFeature<IHttpConnectionFeature>();
if (connection != null) {
    clientIpAddress = connection.RemoteIpAddress.ToString();
}
// Do something with clientIpAddress

The weird thing is that I can't get this to work... GetFeature doesn't resolve. I probably need some extension method in some package I don't have, but I have no idea what package contains GetFeature.

Thanks in advance for any help.

-Brian Eriksen

**Comment by Tratcher** [comment]
https://github.com/aspnet/KestrelHttpServer/issues/632
