### ISSUE TITLE
`ResponseCookies.Append()` allocates lots, big lots

### ISSUE THREAD

**Issue by dougbu** [aspnet/HttpAbstractions#561]
Despite using `StringValues`s, `ResponseCookies.Append()` is very allocation-heavy. Even just reusing the `StringBuilder` created in `SetCookieHeaderValue.ToString()` would be a significant improvement.

For example, running a scenario that adds an Antiforgery token to every response (~156 characters in the token in this case) allocates almost 1 KB extra _per response_. That's more than 2% of the allocations in this scenario.

Data for 3000 requests:
![responsecookies append strings](https://cloud.githubusercontent.com/assets/6431421/13084660/1be72258-d48f-11e5-9798-ccda36d1935f.png)
![responsecookies append chars](https://cloud.githubusercontent.com/assets/6431421/13084662/1e8c93a8-d48f-11e5-9e29-e35ccf0b64cb.png)

**Comment by muratg** [comment]
@dougbu Are you able to send a PR to reuse the StringBuilder?

**Comment by dougbu** [comment]
Sure. I'll do that today.

**Comment by dougbu** [comment]
Offline discussion w/ @Tratcher: Reusing a `StringBuilder` per `ResponseCookies` instance won't do much because few cookies are set per request. Will instead add an object pool of a small class containing (at least for now) just a `StringBuilder` instance.

**Comment by muratg** [comment]
@dougbu That makes sense.

**Comment by dougbu** [comment]
For exposing the feature interfaces (no longer in `.Internal` namespaces):
- 6f24508
- aspnet/Hosting@bb3809d
- aspnet/KestrelHttpServer@f13c418
- aspnet/Security@9361960

**Comment by dougbu** [comment]
Part two for the actual fix:
- @80813f7
- aspnet/Hosting@b06a844 (always register an `ObjectPoolProvider`)
- aspnet/WebListener@f0a5a01 (react to `HttpContextFactory` constructor change)
- aspnet/Antiforgery@0c81df8 (no need to register an `ObjectPoolProvider`)
- aspnet/Mvc@43836ae  (no need to register an `ObjectPoolProvider`)
- aspnet/Routing@39b4f6f  (no need to register an `ObjectPoolProvider`)
