### ISSUE TITLE
IFormFile and FileName

### ISSUE THREAD

**Issue by LorenDorez** [aspnet/HttpAbstractions#570]
Hello,

I am uploading files in my new App and wanted to get the Original FileName from the upload file. Per Articles i see this is done by the following code

```
 var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
```

However when i do this i am getting the full Path not just the filename as expected. 

So instead of 'testdoc.txt' im getting 'C:\this is a Folder\another folder\etc...\Testdoc.txt'

**Comment by Tratcher** [comment]
That value is provided by the client. What client are you using?

**Comment by LorenDorez** [comment]
Currently testing in IE Edge.  Shouldnt this be included in the IFormFile handling? or another Propery called FullPath. As its kind of deceptive

**Comment by Tratcher** [comment]
We're just giving you the `FileName` field from the request. The client can put anything they want in that field.

**Comment by Tratcher** [comment]
Try it on a few different clients for comparison.

**Comment by Eilon** [comment]
The RFC defines the field as a "filename" (and that's indeed the key used in the header), so we had the names in ASP.NET's APIs match the spec. The RFC also suggests that the client (i.e. sender) can put just about anything they want there (just filename, full path, garbage, as long as it's US-ASCII).
