### ISSUE TITLE
Update AuthenticationManager.AuthenticateAsync to return an AuthenticationTicket

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/HttpAbstractions#572]
In June, the `AuthenticateAsync` method was updated to return a `ClaimsPrincipal` instead of an `AuthenticationResult` (a type similar to `AuthenticationTicket`). As a consequence, retrieving the authentication properties is much harder, and can only be done using the rather unusual overload taking an `AuthenticateContext` parameter:

https://github.com/aspnet/HttpAbstractions/pull/323#discussion_r31666811

@HaoK's main argument was that retrieving authentication properties was not really frequent. Sadly, I don't think it's true, as retrieving the expiration date from the ticket is quite popular: http://stackoverflow.com/a/34535003/542757

If you really think having a method returning a `ClaimsPrincipal` is important, why not adding an extension method?

```csharp
public static async Task<ClaimsPrincipal> GetPrincipalAsync(this AuthenticationManager manager, string scheme) {
    if (manager == null) {
        throw new ArgumentNullException(nameof(manager));
    }

    return (await manager.AuthenticateAsync(scheme))?.Principal;
}
```

**Comment by brockallen** [comment]
+1

**Comment by HaoK** [comment]
I'm not opposed to bringing back AuthenticateResult I guess, perhaps as an AuthenticatePrincipal overload instead of a Get...

```
public abstract class AuthenticationManager {
  public AuthenticationResult AuthenticateAsync(string authenticationScheme);
  public ClaimsPrincipal AuthenticatePrincipalAsync(string authenticationScheme);
```

**Comment by muratg** [comment]
@Eilon

**Comment by PinpointTownes** [comment]
Is it too late for RC2? I think it would be worth fixing that before RTM.

**Comment by Eilon** [comment]
I don't really know what this stuff is :smile: 

If @HaoK and/or @Tratcher think this is useful, sure, we can look into adding it.

**Comment by Eilon** [comment]
And @blowdart for that matter.

**Comment by blowdart** [comment]
I'm fine with it

**Comment by Tratcher** [comment]
@HaoK can you take this? And give us an estimate on churn? I'm concerned that this will be too much churn for RC2.

**Comment by HaoK** [comment]
I can take it, its not too bad if we do something like:

Today's Authenticate => AuthenticateUser
New Autenticate returns AuthenticateResult again

Its a breaking change but not that widespread outside of identity and maybe Authorize filter in MVC

**Comment by HaoK** [comment]
Or if we want to minimize churn we can flip the names...

Authenticate stays the same returning Principal.
AuthenticateProperties returns both

**Comment by PinpointTownes** [comment]
As mentioned by @HaoK the impact should be limited (https://github.com/search?q=user%3Aaspnet+AuthenticateAsync&ref=reposearch&type=Code&utf8=%E2%9C%93), but I can help with the task :clap: 

I also think we should remove the `AuthenticateAsync(AuthenticateContext context)` overload, as it's the only one that takes a context parameter, which is inconsistent and weird in a public API.

**Comment by Eilon** [comment]
We'll bring back the old `AuthenticateResult` as a new `AuthenticateInfo`, and then add a new method, something like `public AuthenticateInfo AuthenticateUserAndGetInfoAsync(string authenticationScheme);`

**Comment by HaoK** [comment]
Thoughts on `AuthenticateInfo GetAuthenticateInfoAsync(string authenticationScheme)` for the new overload?

**Comment by Eilon** [comment]
I dig it.

**Comment by Tratcher** [comment]
`Task<AuthenticateDetails> GetAuthenticateDetailsAsync(string authenticationScheme)`?

**Comment by PinpointTownes** [comment]
I think @HaoK's [initial proposition](https://github.com/aspnet/HttpAbstractions/issues/572#issuecomment-188231209) was a good compromise, and was clear enough, but as long as the overload taking an `AuthenticateContext` parameter is removed from the public contract, I'm fine :smile:

**Comment by HaoK** [comment]
I'm ambivalent between AuthenticateDetails/Info.  Maybe `AuthenticateResult` is best, since that satisfies being different from IdentityModel's AuthenticationResult and is what we want to convey (this is the result of an Authenticate)

**Comment by HaoK** [comment]
So here's what I'm thinking for the new shape:

```C#
   // On the abstract base AuthenticationManager:
   public abstract Task<AuthenticateResult> GetAuthenticateResultAsync(string authenticationScheme);
   public abstract Task<ClaimsPrincipal> AuthenticateAsync(string authenticationScheme);
  // Remove: public abstract void AuthenticateAsync(string authenticationScheme);

  public class AuthenticateResult {
    public ClaimsPrincipal Principal { get; set; }
    public AuthenticationProperties Properties { get; set; }
  }

```

**Comment by PinpointTownes** [comment]
Does aspnet/Security already have an `AuthenticateResult`?

**Comment by HaoK** [comment]
Ugh that's right, name was too good to still be available :)  That's the problem with having the same method I guess...  Whelp back to AuthenticateInfo/Details then...

**Comment by HaoK** [comment]
3a7f6a7228fe10b14996b97eed83bcb72684088a
