### ISSUE TITLE
Authorization missing from Request.GetTypedHeaders?

### ISSUE THREAD

**Issue by chadly** [aspnet/HttpAbstractions#574]
Back in WebAPI, I could use `HttpRequestMessage.Headers.Authorization`. It seems like `HttpRequest.GetTypedHeaders()` is the evolution of that concept. However, there is no `Authorization` property on the `RequestHeaders` object.

Is this by design or an oversight?

**Comment by Tratcher** [comment]
We intentionally skipped it because it has minimal defined syntax, it's just `Scheme blablabla`, and we didn't want to bother with additional types for simple headers.

**Comment by chadly** [comment]
:disappointed: It's not a big deal, but it did make it ever so easier to be able to do `Headers.Authorization.Scheme == "whatever"` and not having to do the string split myself.
