### ISSUE TITLE
MultipartStreamReader has suboptimal boundary search in stream

### ISSUE THREAD

**Issue by DavidObando** [aspnet/HttpAbstractions#575]
Method [SubMatch](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/MultipartReaderStream.cs#L309) in class MultipartStreamReader has a naïve implementation of a substring search that make this method a hotpath in multpart upload scenarios.

In an ad-hoc test uploading a number of files ranging from 10 MB to 1 GB, method SubMatch consumed 53.4% exclusive samples during a profiling session.

![image](https://cloud.githubusercontent.com/assets/950290/13437003/e70812be-df96-11e5-8139-dedd1336c9cc.png)

Its current implementation has an O(NM) complexity that can be improved by using a faster algorithm such as [Boyer–Moore–Horspool](https://en.wikipedia.org/wiki/Boyer%E2%80%93Moore%E2%80%93Horspool_algorithm).

Method SubMatch looks for two things:
  1. Whether the byte array segment fully contains the boundary, or
  2. Whether the byte array ends with the start of the boundary.

Case 1 can implement a faster algorithm. Case 2 can be more natural and check character by character as typically the boundary string is very short compared to the length of the byte array segment.

**Comment by DavidObando** [comment]
Implemented a modified Boyer–Moore–Horspool algorithm with an average-case complexity of O(N) on random text. Worst case, it behaves similarly to the previous implementation O(MN), where M is the length of the boundary and N is the length of the buffer to operate on.

This took the cost down to 16.1%. I think I know how to bring it a bit lower, will try that. My skip table is currently a `Dictionary<byte, int>` when it could simply be a `byte[256]`.

![image](https://cloud.githubusercontent.com/assets/950290/13443961/7a408d9c-dfb8-11e5-9f26-bfb91f1b2820.png)

**Comment by DavidObando** [comment]
Indeed, changing the skip table type from `Dictionary<byte, int>` to `int[256]` brought times down as expected. SubMatch now costs 7.6%. I'll run some more tests and then submit a PR.

![image](https://cloud.githubusercontent.com/assets/950290/13444446/31ed3de4-dfbb-11e5-874d-0a23ba1e3fae.png)

**Comment by davidfowl** [comment]
W00t

**Comment by DavidObando** [comment]
Fixed 15649b7.
