### ISSUE TITLE
ASP.NET Core RC1 Microsoft.AspNet.Mvc.HttpRequest properties incorrectly populated

### ISSUE THREAD

**Issue by dotcom9** [aspnet/HttpAbstractions#577]
If an application is deployed in to an IIS virtual directory the Path property does not contain the virtual directory path as expected, but a path representing the website root.

For example, if deployed to https://www.xyz.com/MyApp, Request.Path contains "/" and not "/MyApp".

When the application is accessed via a port number, the Request.Host.Value contains the host and port number enclosed in square brackets which causes a parsing error when reading the property. 

Eg, when deployed to https://www.xyz.com:8443, Request.Host.Value contains "[www.xyz.com:8443]".

**Comment by Tratcher** [comment]
What's an Mvc.HttpRequest? You mean Http.HttpRequest?

See https://github.com/aspnet/IISIntegration/issues/14 for vdirs, though your description sounds reversed. Idealy PathBase should contain "/MyApp" and Path should be "/", but currently you should see PathBase is empty and Path contains "/MyApp".  (To limit confusion I recommend removing your vdir question discussing it in https://github.com/aspnet/IISIntegration/issues/14, it's best to focus on one question per issue).

**Comment by Tratcher** [comment]
Those square brackets are bizarre, they should only be used around IPv6 addresses (`[::1]:8443`).
A) What client are you using? Are you sure it's not sending them? You can use Fiddler to verify.
B) You're using rc1-final packages for everything?
C) Does it depend on which server you're using? E.g. IIS Express & Kestrel, IIS & Kestrel, IIS & VDirs & Kestrel, just Kestrel, just WebListener, etc..

**Comment by muratg** [comment]
@dotcom9 If you still have issues or questions either re-open or file another one.
