### ISSUE TITLE
SignOutAsync should take [] of AuthenticationSchemes

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#585]
_From @rustd on March 14, 2016 22:22_

A user has to specify SignOut per authentication scheme as follows https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/OrganizationalAuth/Single/Controllers/AccountController.cs#L24
With this change we will have the same code as in Katana

_Copied from original issue: aspnet/Security#742_

**Comment by Tratcher** [comment]
I don't think we need this, we had considered it as an intermediate design that didn't provide AuthProperties but opted for https://github.com/aspnet/Security/issues/743 instead.

**Comment by PinpointTownes** [comment]
The syntax in MVC would be much better if https://github.com/aspnet/Mvc/pull/4259 was merged.

/cc @danroth27

**Comment by Tratcher** [comment]
@haok is this still relevant or can we close it? It looks like MVC is doing most of the work for us.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2721
