### ISSUE TITLE
QueryHelpers.AddQueryString to update the query or UpdateQueryString

### ISSUE THREAD

**Issue by jasonwilliams200OK** [aspnet/HttpAbstractions#593]
Current situation:

```c#
var url = "http://example/path?key1=value1&key2=value2";

Console.WriteLine(QueryHelpers.AddQueryString(url, "key1", "value3"));

// http://example/path?key1=value1&key2=value2&key1=value3
```

The desired behavior was to update the key, not cause the duplicate: `http://example/path?key1=value3&key2=value2`.

If this is some kind of an uncanny breaking change, can we at least have an override: `QueryHelpers.AddQueryString(string url, string key, string value, bool overwrite = false)` and in the above example, call it like `QueryHelpers.AddQueryString(url, "key1", "value3", overwrite: true)` to get the desired result? Alternatively, a separate `UpdateQueryString` method?

**Comment by Tratcher** [comment]
This API is not remotely that smart. Right now it just checks if it needs to add `?` or not. Reparsing the existing query string for a key match is a whole different level, not to mention inefficient.  If this happens it should be a separate method like the `UpdateQueryString` you suggested.

**Comment by muratg** [comment]
We won't be adding this for RTM. This can be implemented as an extension on the app level.
