### ISSUE TITLE
ReferenceReadStream implementation doesn't properly implement Begin/End pattern

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#602]
The null ref described in this issue https://github.com/Azure/azure-storage-net/issues/202 occurs because of a bug in the Azure sdk and a bug in http abstractions. ReferernceReadStream implements BeginRead using ReadAsync (https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/Internal/ReferenceReadStream.cs#L128), the code in ReadAsync always calls the callback, even if ReadAsync completes synchronously. This can cause stackoverflows in calling code and bugs like the null reference one in the storage sdk.

/cc @Tratcher

**Comment by davidfowl** [comment]
Since we're using Task as the `IAsyncResult` implementation the easiest fix would be to dispatch the callback.

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/HttpAbstractions/issues/517#issuecomment-165420630
