### ISSUE TITLE
Broken URLs 404 for the specifications

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/HttpAbstractions#607]
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Owin/OwinConstants.cs

The URLs to the specifications are broken and return 404 Not Found.

The specification on the website have been moved.

**Comment by BrennanConroy** [comment]
504a8254063f7166bedcee8a27787e743d3550c2
