### ISSUE TITLE
Use of non-standard OWIN keys?

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/HttpAbstractions#608]
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Owin/OwinConstants.cs#L76

`ssl.LoadClientCertAsync`, `server.ConnectionId` and `host.AppName` among other keys are never mentioned in the specification.
http://owin.org/html/CommonKeys.html
http://owin.org/html/spec/owin-1.0.1.html
http://owin.org/html/spec/middleware-1.0.0-draft.1.html

What are these keys?
How come they are declared in the `CommonKeys` class, even though they are not in the specification?

**Comment by Tratcher** [comment]
CommonKeys hasn't been updated in 2-3 years. Nor has the working group ever ratified those keys, it's just a list of things that were in use at the time I wrote that doc.

Some of these were additions to Katana that never made it back into CommonKeys.
http://katanaproject.codeplex.com/wikipage?title=OWIN%20Keys

That said, we don't require any of those keys and could remove them.
