### ISSUE TITLE
IFormFile.SaveAsAsync

### ISSUE THREAD

**Issue by Bartmax** [aspnet/HttpAbstractions#610]
I'm moving a RC1 project to RC2, i found every change but one.

`IFormFile.SaveAsAsync` looks like it's missing (i can't even find it on github history)

is this removed, moved, or something else?

Thanks

**Comment by davidfowl** [comment]
It got removed because it was untestable. We added CopyTo and CopyToAsync (https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Features/IFormFile.cs#L61). You now own opening the file stream yourself.

**Comment by Bartmax** [comment]
Thank you. +1. Unfortunately I loved that method being out of the box.

**Comment by davidfowl** [comment]
I know but I like tests more.

**Comment by mostafamahran** [comment]
When I Identify Using Microsoft.AspNetCore.Http , the program can`t read it why
