### ISSUE TITLE
Responding status code 401 from MapWhen

### ISSUE THREAD

**Issue by am11** [aspnet/HttpAbstractions#613]
Given this middlewares configuration:

```c#
app.MapWhen(
    context => context.Request.Headers.ContainsKey("super-secret-semaphore") &&
               context.Request.Method == "POST",
    application => application.Run(async context =>
    {
        // snip

        if (someCondition)
        {
            context.Response.StatusCode = StatusCodes.Status401Unauthorized;
        }
        await context.Response.WriteAsync(response);
    });

app.Use(async (context, next) =>
{
    /* snip */
});

// snip

app.UseMvc( /* snip */ );
```

When `someCondition` is met, the next (`app.Use`) middleware is called, while the intention is to respond the caller with 401 status code and discontinue further propagation of the request pipeline.

Apparently, 401 is the only status code possessing this behavior.

Based on https://github.com/aspnet/HttpAbstractions/issues/53#issuecomment-41408927, I tried setting:

```c#
context.Response.Headers.Append("WWW-Authenticate", "no-no");
```

but still no luck achieving the desired behavior. Is it even possible?

**Comment by Tratcher** [comment]
MapWhen always forks the pipeline, you won't continue from the map to the external pipeline. Run always terminates a request, it will not pass control to subsequent middleware. Have you verified in the debugger that you're entering the MapWhen and the Run?

**Comment by am11** [comment]
@Tratcher, yes I have verified with debugger that returning response with 403, 400, 200 or any non-401 status code from `MapWhen(_, app=>app.Run..)` does exactly what you have described; but with 401 status code set, the breakpoint hits in the subsequent middleware (body of `app.Use(async (context, next) =>` and finally reaches `app.UseMvc`).

**Comment by Tratcher** [comment]
With 401s the client may automatically submit a new request with credentials. Are you sure you're still on the same request?

**Comment by am11** [comment]
That is indeed the case. I just tested by putting a breakpoint in `MapWhen`'s condition predicate and found out that it is called again with the same secret header but HTTP method `GET` (although the original request from client was with `POST`) which is like weirdness++ ..

If I remove the `POST` check from the condition, then it repeatedly hits the `MapWhen` middleware when 401 is set.

My client is another ASPNET-core app using `HttpClient`:

```c#
var request = new HttpRequestMessage
{
    RequestUri = _baseAddress,
    Method = HttpMethod.Post
};

request.Headers.Add("super-secret-semaphore", MyJwtTokenFactory.ProduceTokenFor(_httpContext));

bool result = false;

await _httpClient.SendAsync(request)
      .ContinueWith(async taskWithMessage =>
      {
          var responseMessage = await taskWithMessage;
          result = responseMessage.IsSuccessStatusCode;
      });
```

Is there anyway to prevent it from automatically re-attempting with credentials (and wrong `HttpMethod`)?

**Comment by Tratcher** [comment]
That's up to the client, 401 is supposed to be retriable. Use 403 if you don't want them to retry.

**Comment by muratg** [comment]
@am11 Closing this one. 403 should stop clients from retries.

**Comment by am11** [comment]
@muratg and @Tratcher: we are using 403 status in our project.

Despite of it being an uncommon usecase, I still believe it would be a helpful note/gotcha about 401 status in middleware docs: https://docs.asp.net/en/latest/fundamentals/middleware.html.

Thanks for your helpful tips and support.

**Comment by Tratcher** [comment]
What sort of note about 401 in middleware? This was a client behavior, not middleware.
