### ISSUE TITLE
Should Fetch be made more inline-friendly?

### ISSUE THREAD

**Issue by rynowak** [aspnet/HttpAbstractions#617]
It's common in MVC to see traces like:
![image](https://cloud.githubusercontent.com/assets/1430011/14624142/d65f7648-058c-11e6-9935-77ca8e34ed3e.png)

There's about 1.33% of a request's time spent just doing the initial feature access. 

We should probably see what the JIT has to say about this code path and try to either optimize for:
- first read (`cached == null`) **OR**
- multiple reads (`cached != null && Revision == collection.Revision`)

by breaking this up into an inlinable fast path and non-inlinable slow path

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Features/FeatureReferences.cs#L26

**Comment by benaadams** [comment]
trickier as cached is often a struct

**Comment by benaadams** [comment]
@rynowak is latest commit on #623 now improved for this?

**Comment by rynowak** [comment]
@benaadams - I'll give this a try when I can - that will probably be next week unf. The profiler should be able to tell whether it's getting inlined or not.

**Comment by benaadams** [comment]
#623 was nothing, #704 is the mother lode...
