### ISSUE TITLE
Query parameter without equals sign are not added to `Request.Query`

### ISSUE THREAD

**Issue by pakrym** [aspnet/HttpAbstractions#624]
For request `http://localhost:5000/?q` query collection would be empty so to check if parameter exists user would need to parse it manually. On other hand `http://localhost:5000/?=` works and creates item with empty name and empty value, which is semantically correct but is much less useful.

**Comment by muratg** [comment]
@moozzyk If a key doesn't have any value, just make it an empty string.

**Comment by moozzyk** [comment]
Fixed in e854d3aa9a31493c891324080428b16fcd5d0503
