### ISSUE TITLE
Request.Form throws 'Unexpected end of stream` if Request.Body was read

### ISSUE THREAD

**Issue by pakrym** [aspnet/HttpAbstractions#625]
```
using (var streamReader = new StreamReader(context.Request.Body))
{
    streamReader.ReadToEnd();
}
if (context.Request.HasFormContentType) { 
    var form = context.Request.Form; // << exception here
}   
```

Can we give better error message?

**Comment by Tratcher** [comment]
Was this for form or multipart form?

Recommendation?

**Comment by pakrym** [comment]
It was multipart form. Something like "Could not read Form after body have been read" would be more descriptive I think.

**Comment by Tratcher** [comment]
`Unexpected end of Stream, the content may have already been read by another component.`?

**Comment by pakrym** [comment]
Sounds good.
