### ISSUE TITLE
No way to get the UserInfo string from HttpRequest

### ISSUE THREAD

**Issue by tuespetre** [aspnet/HttpAbstractions#628]
[Per RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.2.1), a URI's authority component may contain a 'userinfo' subcomponent before the hostname, which is delimited from the hostname by the at-sign. Although putting `username:password` into this subcomponent is deprecated, the 'userinfo' subcomponent as a whole is not. In some scenarios it can be useful. "ASP.NET classic" (I really don't know what the preferred term is here, 4.x?)  put a URI object on the Request which could contain the UserInfo string, but there is no such accessor on ASP.NET Core's `HttpRequest`.

Would the team consider adding any such accessor to `HttpRequest`?

**Comment by Tratcher** [comment]
The whole URI isn't transmitted from the client. What client are you using? If you look at a trace (Fiddler, Wireshark, etc.) where do you see this data in the raw request?

**Comment by tuespetre** [comment]
Doh, leave it to me to miss an important detail like that! :dancers:
