### ISSUE TITLE
React to: Add Stream.Begin/EndRead and Stream.Begin/EndWrite

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#629]
We'll be able to remove our ifdefs

**Comment by muratg** [comment]
https://github.com/dotnet/corefx/pull/8378

**Comment by davidfowl** [comment]
@muratg This should be in 2.0

**Comment by JunTaoLuo** [comment]
Spoke with @pranavkm about this and apparently this won't be possible. Seems like we will be cross compiling against netstandard2.0 and netstandard 1.x so we will still keep the ifdefs. Closing in favour of https://github.com/aspnet/Coherence/issues/166 for tracking updates of repos to netstandard2.0 where possible.
