### ISSUE TITLE
Finding Original RequestUri with IHttpRequestFeature

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/HttpAbstractions#630]
I'm trying to log the request URI when an exception is thrown. Logging is too abstracted out to do it so I thought that IHttpRequestFeature was my trick. Here's what I'm trying, please let me know if I'm way off the right track:

First I'm using an exception page:

```
app.UseExceptionPage("/Exception");
```

This logs the exception, but just the bare exception, no state of the request.

So, inside the Action for /Exception, I'm doing this:

```
    [HttpGet("Exception")]
    public IActionResult Exception()
    {
      var exception = HttpContext.Features.Get<IExceptionHandlerFeature>();
      var request = HttpContext.Features.Get<IHttpRequestFeature>();

      if (exception != null && request != null)
      {
        var originalPath = request.Path;
        // I could cast the request object to a Frame to get at the information, but that feels dirty

        // Manually logging the information
      }

      return View();
    }
```

**Comment by Tratcher** [comment]
This issue was moved to aspnet/Diagnostics#292
