### ISSUE TITLE
Http post is broken by recent changes?

### ISSUE THREAD

**Issue by kerryjiang** [aspnet/HttpAbstractions#632]
Hello guys, my website is broken after I restored the packages.

It seems all http post actions cannot work.

The exception I caught in the console is:

**System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.WebUtilities.MultipartReader.set_HeadersCountLimit(Int32)'.
   at Microsoft.AspNetCore.Http.Features.FormFeature.<InnerReadFormAsync>d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenStore.<GetRequestTokensAsync>d__3.MoveNext()**

Other information:
Before I restore, the package Microsoft.AspNetCore.WebUtilities's version is 1.0.0-rc2-20668.
After the restore, it was changed to 1.0.0-rc3-20533.

Source code which can reproduce this issue, just try to login with any credential:
https://github.com/kerryjiang/dotnetcore-samples/tree/master/mvc-identity

Somebody can help me check this issue?

**Comment by Tratcher** [comment]
Make sure all of your restored dependencies for AspNetCore are the same version. RC3 packages should only be coming from our dev feed right now.

**Comment by kerryjiang** [comment]
@Tratcher Yes, thanks!

That's wired.

I think my nuget.config file is correct:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcirelease/api/v3/index.json" />
  </packageSources>
</configuration>
```

And the dependencies should be setup correctly in project.json:

```
"dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-*",
    "Microsoft.EntityFrameworkCore": "1.0.0-rc2-*",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-rc2-*",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-*"
    }
  } 
```

But I still got wrong references link in project.lock.json?

It looks ok in this part:

```
"Microsoft.AspNetCore.Http/1.0.0-rc2-20901": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNetCore.Http.Abstractions": "1.0.0-rc2-20901",
          "Microsoft.AspNetCore.WebUtilities": "1.0.0-rc2-20901",
          "Microsoft.Extensions.ObjectPool": "1.0.0-rc2-20901",
          "Microsoft.Extensions.Options": "1.0.0-rc2-20901",
          "Microsoft.Net.Http.Headers": "1.0.0-rc2-20901",
          "System.Buffers": "4.0.0-rc2-24027",
          "System.Threading": "4.0.11-rc2-24027"
        },
        "compile": {
          "lib/netstandard1.3/Microsoft.AspNetCore.Http.dll": {}
        },
        "runtime": {
          "lib/netstandard1.3/Microsoft.AspNetCore.Http.dll": {}
        }
      }

```

But the assembly of rc3 is still introduced:

```
"Microsoft.AspNetCore.WebUtilities/1.0.0-rc3-20533": {
        "type": "package",
        "dependencies": {
          "Microsoft.Extensions.Primitives": "1.0.0-rc3-20533",
          "System.Buffers": "4.0.0-rc2-23931",
          "System.Collections": "4.0.11-rc2-23931",
          "System.IO": "4.1.0-rc2-23931",
          "System.IO.FileSystem": "4.0.1-rc2-23931",
          "System.Text.Encodings.Web": "4.0.0-rc2-23931"
        },
        "compile": {
          "lib/netstandard1.3/Microsoft.AspNetCore.WebUtilities.dll": {}
        },
        "runtime": {
          "lib/netstandard1.3/Microsoft.AspNetCore.WebUtilities.dll": {}
        }
      }
```

Is it an issue of NuGet? Should I  upgrade my CLI to the latest version?

My current version is 1.0.0-rc2-002543.

**Comment by kerryjiang** [comment]
Changed the dependencies to rc2-final can fix this issue. Is it a reference issue in your package?

```
"dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-*",
    "Microsoft.EntityFrameworkCore": "1.0.0-rc2-*",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-rc2-*",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-*"
    }
  },
```

**Comment by Tratcher** [comment]
Try moving from aspnetcirelease back to aspnetcidev now that we've released rc2, or just stick with rc2-final.

**Comment by muratg** [comment]
Or if you want to use supported RC2 bits, just keep using nuget.org only, and remove the myget feeds from your nuget.config. 

Let us know if you still have issues with those changes.

**Comment by kerryjiang** [comment]
Thanks for your suggestions!
