### ISSUE TITLE
Add IsAvailable to ISession

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/HttpAbstractions#634]
As part of https://github.com/aspnet/Session/pull/113. We realized there is value in adding a `IsAvailable` property to the `ISession` interface to indicate whether the session has loaded correctly. This value can depend on factors such as whether the underlying caching data is available and is valid.

**Comment by kichalla** [comment]
cc @ajaybhargavb 

@JunTaoLuo @Tratcher  is the expectation that where ever session is required to be present, the code should check for IsAvailable explicitly and throw? (for example: MVC's TempData depends on it...can you file an issue on Mvc to update it https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/SessionStateTempDataProvider.cs#L61)

**Comment by JunTaoLuo** [comment]
@kichalla The idea is that if the Session is not available, you should not depend on it to give you any information. You should have some fall back logic to handle it and depending on the case, throwing and failing the request may or may not be the right thing to do. 

Note that if the session is not available, it will no op when you try to access or modify it. `TryGetValue()` will return `false` and `Set`/`Remove` will no-op.

**Comment by Tratcher** [comment]
It's up to the caller to decide what to do. IsAvailable is just a hint to the app so it can fail more gracefully if expected values are not present.

**Comment by kichalla** [comment]
Ok sure, thanks.
