### ISSUE TITLE
Make multipart reading related methods public

### ISSUE THREAD

**Issue by kichalla** [aspnet/HttpAbstractions#638]
This was from the following PR related to multipart file upload. Here many of methods (for example: in MultipartRequestHelper.cs) were borrowed from `FormFeature`. It would be good to make these public for consumption.

https://github.com/aspnet/Entropy/pull/123

**Comment by rynowak** [comment]
I think it's more than just that, the PR includes 30 or so lines of boilerplate. If this is code we expect users to write we don't want to have so many required details.

**Comment by muratg** [comment]
Additive change. Putting into 1.0.1 milestone.

**Comment by victorhurdugaci** [comment]
Talked to @Tratcher . I'll do this
