### ISSUE TITLE
overriding max upload limit

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#641]
_From @Ryuuke on May 27, 2016 18:30_

Hello, 
I encountered this error when uploading large file (~200MB).

> An unhandled exception occurred while processing the request.
> Multipart body length limit 134217728 exceeded
> at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.UpdatePosition(Int32 read)

I already tried to modify my web.config file :
httpRuntime maxRequestLength="1073741824" executionTimeout="300000"
and requestLimits maxAllowedContentLength="1073741824"

but still, I get the same error.

I'm using the RC2 version, is there a way to override that limit ?

_Copied from original issue: aspnet/KestrelHttpServer#891_

**Comment by Tratcher** [comment]
These are limits on the request form. Where are you trying to read the Form, an MVC Controller/Action?

The limits can be adjusted per action like this:
https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Controllers/RequestFormLimitsController.cs#L19

Or for the whole app like this (but don't do this just for one file):
https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Startup.cs#L34

**Comment by davidfowl** [comment]
@Tratcher @Eilon @kichalla should that filter be built into mvc?

**Comment by Tratcher** [comment]
@rynowak Probably.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Filters/RequestFormSizeLimitAttribute.cs

**Comment by Ryuuke** [comment]
Hey, thanks for your reply, yeah i'm trying to read the form from the an MVC action, I just wanna point out that you helped me solve the problem, it was not about the KeyCountLimit, but the MultipartBodyLengthLimit property inside the FormOptions that I updated to a larger value than the default and It Worked well.

**Comment by victorhurdugaci** [comment]
This is something that should be in MVC. cc @kichalla @rynowak

**Comment by Eilon** [comment]
Is this the same as https://github.com/aspnet/Mvc/issues/481?

**Comment by Tratcher** [comment]
Not quite, this is specific to forms.

**Comment by muratg** [comment]
This issue was moved to aspnet/Mvc#5128
