### ISSUE TITLE
[Questions] About back slash support in URI 

### ISSUE THREAD

**Issue by chinadragon0515** [aspnet/HttpAbstractions#643]
This is related to issue https://github.com/OData/RESTier/issues/414

Now we have a URL with back slash in it, when the service receive the request, I find Web Api will auto convert back slash to slash, and slash is not "%5C" but becomes the character '\'.

I did some search, I find this configuration,

```Xml
  < uri>
    < schemeSettings>
      < add name="https" genericUriParserOptions="DontUnescapePathDotsAndSlashes"/>
      < add name="http" genericUriParserOptions="DontUnescapePathDotsAndSlashes"/>
    < /schemeSettings>
  < /uri>
```
This does not work for me, I see there is an option DontConvertPathBackslashes, but when I set here, it indicates this is not correct setting.

Can you help to advise how I can configure a request with back slash? Or this is not supported?

For our project, it is created  via 
"C# > Web > ASP.NET Web Application.", and 
In the New ASP.NET Project dialog box, select the Empty template.
Check the Web API check box.

If this is not right space for question, can you help to advise where I should ask this question.

**Comment by davidfowl** [comment]
Ask this question github.com/dotnet/corefx

**Comment by chinadragon0515** [comment]
@davidfowl thanks

**Comment by chinadragon0515** [comment]
Seems this issue is more related to ASP .NET, so I reopen the issue.

**Comment by Tratcher** [comment]
This is a behavior of Http.Sys/IIS. I assume you're running in IIS?

**Comment by chinadragon0515** [comment]
@Tratcher Yes, I am using IIS, is there any configuration I can disable this convert? thanks.

**Comment by Tratcher** [comment]
No, there's no way to change this in IIS right now.

**Comment by chinadragon0515** [comment]
@Tratcher thanks, I close the issue as this is not supported.
