### ISSUE TITLE
Merge QueryString & Query Properties

### ISSUE THREAD

**Issue by niemyjski** [aspnet/HttpAbstractions#644]
Currently the request object has a `Host` property that has `Host.Host` and `Host.Port` and it makes it easier to get that info. There is one place to look.  But when it comes to the query string there are inconsistencies and it's not as discoverable. At first I saw the QueryString property and looked in intellisense for QuerySring but didn't even think to look for Query after working with Host and some of the other complex property types. 

There is a `Query` property that gives you a parsed query string and then a `QueryString` property that builds up the Query into a single string. It would be nice if the `IQueryCollection` had a ToString() implementation to display the query string, but at the same time it should be separated out and not responsible for building it. Which is why I see there are two properties. With this said I guess the question is, should these be merged into a complex type that has both QueryString and Query or just an Extension Method that builds the query string from IQueryCollection?

**Comment by niemyjski** [comment]
Only closest issue we found on slack was: https://github.com/aspnet/HttpAbstractions/issues/50

**Comment by MaximRouiller** [comment]
I know that in the past, it was represented as a list KeyValuePair.

Why is this now a string only? It doesn't seem like there's an actual way to extract that information without re-parsing it. 

Unless it's a write-only structure, it should allow us to parse it at the very least.

**Comment by Tratcher** [comment]
Why are you adding values to the request query?

**Comment by niemyjski** [comment]
I'm not, I'm trying to shred the request info into our model...

https://github.com/exceptionless/Exceptionless.Net/blob/feature/netstandard/src/Platforms/Exceptionless.AspNetCore/RequestInfoCollector.cs

This really should get changed regardless, it's not consistent or as efficient as it could be.

**Comment by Tratcher** [comment]
Your usage does not appear to be related to the issues you mentioned above.

We're in the process of finalizing v1.0 and are unlikely to make structural changes at this point. If you see performance issues those are best conveyed via profiler traces.

**Comment by niemyjski** [comment]
@Tratcher I was just putting an example of what the api could look like for interacting with it..  Take a look at the code there are way more allocations and parsing going on than what is needed. Right now I think it's a mistake labeling this sole package as an rtm knowing users will want the query string info and it will need to be parsed all the time to get that info.

**Comment by niemyjski** [comment]
I've updated this issue based on further investigation.

**Comment by Tratcher** [comment]
Thanks, that's a clearer description. 

I'm still trying to figure out why your scenarios discuss query building on the request. Most of the request properties are provided to deconstruct the raw HTTP into useful components. The request target is deconstructed into PathBase, Path, and QueryString. QueryString is further deconstructed into Query key value pairs. The Query property is index into to retrieve individual values.  Query is not mutable and I don't know why you'd use it to build a QueryString when you already have the original.  One reason for keeping the QueryString property is that it's useful for generating redirect links like `newScheme + "://" + Host + PathBase + Path + QueryString`. It's also available for scenarios where the query contains something other than key value pairs.

Are there additional scenarios we should be addressing?

**Comment by niemyjski** [comment]
@Tratcher I only included a sample to adding to query as a user might want to build up there own query string using it and return it in a header... Most cases users will not modifying it and I will not be.. But it's a valid scenario... My thing is I saw query string and didn't even look for query, it sounded like something I shouldn't be touching (Query as in a database query etc, not something I'd look for for a key value pair that makes up the query string).

**Comment by muratg** [comment]
Triaging out of 1.0.0 and we'll have another look once we RTM.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2719
