### ISSUE TITLE
Suggestion - Rename IFormFile.OpenReadStream to IFormFile.GetInputStream()

### ISSUE THREAD

**Issue by am11** [aspnet/HttpAbstractions#645]
In MVC5 app, we were passing around `HttpPostedFileBase.InputStream` reference from controller action to a helper, which uploads files to remote storage (and generates CDN links etc.).

With MVC Core, we are achieving the same by using `IFormFile.OpenReadStream()` which returns the reference to the underlying stream.

It would probably make sense to have this method renamed to `GetInputStream()` or `GetReadStream` to depict what it returns.

**Comment by davidfowl** [comment]
We're not going to be renaming this method at this point.

**Comment by am11** [comment]
Thanks @davidfowl. With `File.OpenRead` analogy, `OpenReadStream` probably is a better choice. I thought I should suggest anyway. 😄
