### ISSUE TITLE
IHttpContextAccessor resolved as null

### ISSUE THREAD

**Issue by JakeGinnivan** [aspnet/HttpAbstractions#646]
I am using IdentityServer3 with dotnet core and am upgrading to RC2 and have hit a snag.

I have a custom user service which I want to resolve out of the aspnet core container. So I get access to the Request services like this:

```
var idsrvOptions = new IdentityServerOptions
{
    Factory = new IdentityServerServiceFactory
    {
        UserService = new Registration<IUserService>(r =>
        {
            var owin1 = r.Resolve<OwinEnvironmentService>();
            var httpContext1 = (HttpContext) owin1.Environment["Microsoft.AspNetCore.Http.HttpContext"];
            return httpContext1.RequestServices.GetService<CustomUserService>();
        })
    }
...
```

Not pretty, but I couldn't figure out how else to go from identity servers internal container to the request container without doing this. It calls into my factory fine:

```
services.AddScoped(p =>
{
    var httpContextAccessor = p.GetService<IHttpContextAccessor>();
    var portalOptions = p.GetService<IOptions<AuthenticationApiOptions>>();
    return new IdentityStoresApi(
        portalOptions,
        _portalApiHandler(),
        httpContextAccessor,
        _selfApiHandler);
});
```

Inside the AddScoped callback, `httpContextAccessor` is null. Any ideas what I have missed? The options are resolved fine.

**Comment by khellang** [comment]
In RC2, `IHttpContextAccessor` isn't registered by default. This means you have to register it yourself, explicitly; https://github.com/aspnet/Mvc/blob/dd774366f6fb18af9382ca84c276e6eb73c66b3a/test/WebSites/BasicWebSite/Startup.cs#L23

Related: https://github.com/aspnet/Razor/issues/768

**Comment by manikandan05** [comment]
Following is my startup.cs file code snippet

` public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddMvc();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddSingleton<IActionContextAccessor, ActionContextAccessor>();
            //services.AddCaching();
            services.AddSession();
            // Add application services.
            services.AddTransient<IEmailSender, AuthMessageSender>();
            services.AddTransient<ISmsSender, AuthMessageSender>();
        }`

I'm unable to get Httpcontext in my static class

` public static class TestHelper
    {
        public static IHttpContextAccessor HttpContextAccessor;
        
        public static void Configure(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }
public static string UrlFinder(this IHtmlHelper helper, string controlid)
        {
            HttpContextAccessor httpContextObj = new HttpContextAccessor();
//This line worked in RC1
 var urlHelper = httpContextObj.HttpContext.RequestServices.GetRequiredService<IUrlHelper>();
};
}

`

I already tried the steps said in following link comments 

1. https://github.com/aspnet/Mvc/issues/3936
2. https://github.com/aspnet/Razor/issues/768

Please help us to find out solution.

**Comment by khellang** [comment]
@manikandan05 You can't just create an instance of `HttpContextAccessor` and expect it to know about the current `HttpContext`. You need to get it from the container. That's why you're registering it.

**Comment by manikandan05** [comment]
Hi @khellang , I just want to get the urlHelper for my action. I tried out get the value from the below mentioned way.

'  var urlHelper = httpContextObj.HttpContext.RequestServices.GetRequiredService<IUrlHelper>(); '

**Comment by JakeGinnivan** [comment]
@khellang so the behaviour of the DI in core is to return null when things are not registered rather than throw an error? That seems broken =/

I didn't even check for it not being registered because I assumed if something is not registered it would throw saying it cannot resolve.

**Comment by khellang** [comment]
@JakeGinnivan Yes, when calling `GetService`. If you want to make sure it throws for invalid configurations, you need to call `GetRequiredService` :smile:

**Comment by khellang** [comment]
@manikandan05 I'm not sure what you're trying to do. You want to resolve `IHtmlHelper` from the services? You already have it as a parameter?

You could do something like

```csharp
public static class TestHelper
{
    public static string UrlFinder(this IHtmlHelper helper, string controlid)
    {
        var httpContext = helper.ViewContext.HttpContext;

        // Do something with httpContext...
    }
}
```

BTW, it sounds like you want to get the URL for something. You know there's already a utility called `IUrlHelper`?

**Comment by JakeGinnivan** [comment]
Sweet, i'm all sorted. will leave this issue open for @manikandan05

**Comment by JakeGinnivan** [comment]
Gonna close this, @manikandan05's issue doesn't seem to be related.

**Comment by manikandan05** [comment]
Hi @JakeGinnivan, still i'm trying to resolve from my end. i didn't get solution for get the value from IUrlHelper in GetRequiredService<>()

**Comment by khellang** [comment]
@manikandan05 I suggest you file a separate issue with a good description of what you're trying to achieve and why it's not working. It doesn't seem related to this...

**Comment by manikandan05** [comment]
Hi @khellang, i have tried your solution also, but i'm cant escape from this UrlHelper. Now i have the face some other problem.

Please help to find out the solution.
[WebApplication4.zip](https://github.com/aspnet/HttpAbstractions/files/295638/WebApplication4.zip)

**Comment by khellang** [comment]
I'd prefer not to download and unpack a random zip on my computer. Can you post it as a gist or something? Create a GitHub repo?

It would be nice if you could try to explain what you're trying to achieve. Or provide more info on what's wrong. :smile:

**Comment by manikandan05** [comment]
Hi @khellang, I have posted my code snippet (gist) in the following online link.

https://gist.github.com/manikandan05/5fa6bc50ae739675834fa75ec5025024

**Comment by khellang** [comment]
@manikandan05 I've basically give you the solution above. Get the `HttpContext` from the `IHtmlHelper`: `helper.ViewContext.HttpContext`

**Comment by manikandan05** [comment]
ok @khellang , After HttpContext, i'm not further using RequestServices.GetRequiredService<>() get the UrlHelper value to call Action(controller,method). This is the issue form my starting point.

**Comment by khellang** [comment]
@manikandan05 I still can't remember reading what your original issue is. Are you not getting the `IUrlHelper` from the services? Can't you just create it? `new UrlHelper(helper.ViewContext)`

**Comment by manikandan05** [comment]
Hi @khellang, Thanks for your valuable suggestion. Now i got the solution :smile:

Thanks...
