### ISSUE TITLE
UriBuilder does not work well with QueryBuilder

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/HttpAbstractions#647]
The `UriBuilder` class automatically prepends a `?` to its `Query` property which is troublesome when trying to construct a new uri.

For instance:
![image](https://cloud.githubusercontent.com/assets/2008729/15729422/df59a0a8-2818-11e6-9100-1b6c05f4dabb.png)

**Comment by Tratcher** [comment]
What were you going to do with the result?

System.Uri is not well suited for use in HTTP headers. https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/UriHelper.cs works better there.

MVC has other APIs for building urls in HTML bodies.

**Comment by NTaylorMullen** [comment]
Was going to pass the resulting `Uri` to an `HttpClient`. Its post methods accept a `Uri` so the `UriBuilder`/`QueryBuilder` _seemed_ well suited.

**Comment by Tratcher** [comment]
Ah. UriHelper should work in place of UriBuilder too.

**Comment by NTaylorMullen** [comment]
Hmm? How would you use [UriHelper](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/UriHelper.cs) to do what `UriBuilder` does? From the class it looks that it's only good for encoding and reading info from a request.

**Comment by Tratcher** [comment]
```
            var query = new QueryBuilder()
            {
                { "hello", "world" }
            }.ToQueryString();

            var encoded = UriHelper.Encode("http", new HostString("contoso.com"), query: query);
            var uri = new Uri(encoded, UriKind.Absolute);

            Console.WriteLine(uri.AbsoluteUri);
```

**Comment by NTaylorMullen** [comment]
Is that really what we expect users to be doing? The APIs seem very awkward.

**Comment by Tratcher** [comment]
We never ask users to build a System.Uri, it's only used in client APIs.

**Comment by NTaylorMullen** [comment]
Talked offline and we both agree that `QueryBuilder` on its own is actually a really nice API; however, the end-to-end usage of it is horribad :smile:. This is primarily due to the `UriHelper` API.

Therefore, closing this in favor of fixing https://github.com/aspnet/HttpAbstractions/issues/573. If you want to also add API to make this consumable from `UriBuilder` feel free to reopen this.
