### ISSUE TITLE
HttpRequest has inconsistent naming

### ISSUE THREAD

**Issue by strohhut** [aspnet/HttpAbstractions#649]
Currently there is 

```
public abstract HostString Host { get; set; }
public abstract PathString Path { get; set; }
public abstract QueryString QueryString { get; set; }
public abstract IQueryCollection Query { get; set; }
```

wouldn't it be more consistent with something like

```
public abstract QueryString Query { get; set; }
public abstract IQueryCollection QueryParameters { get; set; }
```

?

**Comment by Tratcher** [comment]
Related discussion: https://github.com/aspnet/HttpAbstractions/issues/644

**Comment by Tratcher** [comment]
It would be more consistent, but less useful. The IQueryCollection is used far more often than the QueryString.

**Comment by strohhut** [comment]
I'd say better consistency makes it easier to use than shorter names.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
