### ISSUE TITLE
HttpContext.Request.Scheme Is Always "http" In Azure

### ISSUE THREAD

**Issue by kspearrin** [aspnet/HttpAbstractions#650]
After moving from RC1 to RC2 a new problem has come up. It seems that after publishing a solution to Azure `HttpContext.Request.Scheme` is always reading "http", even when we are using a secure an https endpoint. This of course causes `httpContext.Request.IsHttps` to always return false.

**Comment by Tratcher** [comment]
Duplicate: https://github.com/aspnet/IISIntegration/issues/140#issuecomment-215135928
