### ISSUE TITLE
AuthenticationManager.AuthenticateAsync(AuthenticateContext context) and post-RC2

### ISSUE THREAD

**Issue by dogguts** [aspnet/HttpAbstractions#653]
In RC2 it is possible to get the AuthenticationContext through: `AuthenticationManager.AuthenticateAsync(AuthenticateContext context)`
Thus eg. being able to show `context.Error?.Message` in a view (as to the reason why authentication failed) when an AuthenticationHandler returned with `AuthenticateResult.Fail(string)`

I noticed (in dev) through [https://github.com/aspnet/HttpAbstractions/commit/3a7f6a7228fe10b14996b97eed83bcb72684088a](https://github.com/aspnet/HttpAbstractions/commit/3a7f6a7228fe10b14996b97eed83bcb72684088a) 
the `AuthenticateAsync(AuthenticateContext context)`-method is bound to be removed in future release(s): 

> // Will remove once callees have been updated
> public abstract Task AuthenticateAsync(AuthenticateContext context);

And `Task<AuthenticateInfo> GetAuthenticateInfoAsync(string authenticationScheme)` is introduced in return.

However, while `AuthenticateInfo` contains the Principal, Properties and Description, it does seem to be missing the/an Error-property.

**Comment by muratg** [comment]
@Tratcher's example shows how you can achieve this currently. We don't plan to add the sugar.
