### ISSUE TITLE
[Announcement] CookieSecureOption & SecurePolicy merged to CookieSecurePolicy

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#662]
CookieSecureOption and SecurePolicy have been merged into CookieSecurePolicy and moved to the Microsoft.AspNetCore.Http namespace and Microsoft.AspNetCore.Http.Abstractions package. This was done to enable re-using the type in additional places.

Before:
Microsoft.AspNetCore.Authentication.Cookies.CookieSecureOption: SameAsRequest, Never, Always
Microsoft.AspNetCore.CookiePolicy.SecurePolicy: None, Always, SameAsReqeuest

After:
Microsoft.AspNetCore.Http.CookieSecurePolicy: SameAsRequest, Always, None

RE:
aspnet/HttpAbstractions#612
aspnet/HttpAbstractions#631
aspnet/Security#817

**Comment by justdmitry** [comment]
Why you labeled announcement as **milestone 1.0.0**, while 1.0.0 RTM is already released?

**Comment by Tratcher** [comment]
Because the change was made during 1.0.0, the announcement was just late.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
