### ISSUE TITLE
IsClientConnected

### ISSUE THREAD

**Issue by DonObin** [aspnet/HttpAbstractions#668]
Hello,

I'm working with SSE and I don't see `Response.IsClientConnected` like in .NET Framework. It was renamed or deleted in .NET Core?

**Comment by davidfowl** [comment]
You can use HttpContext.RequestAborted.IsCancellationRequested https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/HttpContext.cs#L67

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
