### ISSUE TITLE
Default IHttpResponseFeature implementation does not implement OnStarting and OnCompleted

### ISSUE THREAD

**Issue by jijiechen** [aspnet/HttpAbstractions#669]
The default implementation of IHttpResponseFeature, that is [Microsoft.AspNetCore.Http.Features.HttpResponseFeature](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/Features/HttpResponseFeature.cs) does not implement OnStarting and OnCompleted methods.

Some middlewares (such as AuthenticationMiddleware) will invoke Response.OnStarting and this lead to invocation of HttpResponseFeature.OnStarting if no custom IHttpResponseFeature implementation is used. Lacking implementation for those two methods makes exceptions (of type System.NotImplementedException) when use intance of DefaultHttpContext to be handled in a test application (which powered by a TestServer) with Authentication configured.

Despite that these issues can be solved by replacing default HttpContextFactory and set another implementation for IHttpResponseFeature, but the behavior is still not expected.

**Comment by davidfowl** [comment]
Are you actually experiencing an issue? All of the servers provided by the ASP.NET team implement this feature (the default isn't used). Did you write a unit test that news up the DefaultHttpContext or something similar?

**Comment by jijiechen** [comment]
@davidfowl Thank you for replying.
Yes, exceptions are thrown in my tests.
I have no knowledge or expectation that I need to implement this feature when writing tests, so please leave default implementation will help.
Thanks.

**Comment by davidfowl** [comment]
Can you show the code that reproduces this?

**Comment by jijiechen** [comment]
Yes, I tried using RequestDelegate to invoke a new DefaultHttpContext directly, and it throws NotImplemtedException.
Luckily, the small project I am working on is also open source, so you can checkout the code [here](https://github.com/jijiechen/openaspnetorg/blob/f4ac088fc79ec7fe5c21f428374580e108f882f0/test/Discussion.Web.Tests/StartupSpecs/MiddlewareConfigureSpecs.cs#L48). I need to configure a custom IHttpResponseFeature (in line 77) to override those methods to prevent exceptions.

**Comment by davidfowl** [comment]
That's a lot of code, why don't you just use the TestServer ?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.TestHost/TestServer.cs

**Comment by jijiechen** [comment]
@davidfowl 
I simplified a little, please checkout [this gist](https://gist.github.com/jijiechen/afd1254aad99d3dee994a0846f94e05b)

In some cases, I only want to verify the request handler pipeline works as expected, so I want a simpler TestServer, just as shown in the gist.
That's why I am not using the TestServer here.
Thanks @Tratcher

**Comment by Tratcher** [comment]
This is exactly what TestServer is designed for. OnStarting and OnCompleted cannot be implemented without knowledge of the request life-cycle which DefaultHttpContext does not have on its own.

**Comment by jijiechen** [comment]
So is there any builtin HttpContext implementation can be used in my case?

**Comment by davidfowl** [comment]
@jijiechen I don't understand what you mean. Can you use the TestServer and create a repro of the problem. We use this ourselves to test all of our middleware so I would be surprised if it did throw.

**Comment by jijiechen** [comment]
@davidfowl  I am clear now. I have to set a custom IHttpResponseFeature to HttpContext before I can use it to be processed. I think this is the point I missed out.

Closing this thread.
Thank you guys.

**Comment by davidfowl** [comment]
> @davidfowl I am clear now. I have to set a custom IHttpResponseFeature to HttpContext before I can use it to be processed. I think this is the point I missed out.

You don't, you can use the TestServer which already does this.

**Comment by jijiechen** [comment]
@davidfowl I know, TestServer is very great for most scenarios, but sometimes I really want to reference an HttpContext instance to confirm it is correctly processed.

Thank you.

**Comment by Tratcher** [comment]
Yeah, we used to have something like that in the [Katana](http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Testing/TestServer.cs) version, where you could create the server-side context and directly Invoke the pipeline. I'd like a similar option, as HttpClient does not always give you enough granular control. Want to open a new bug against TestServer in Hosting?

**Comment by jijiechen** [comment]
@Tratcher  Good suggestion.
