### ISSUE TITLE
UriHelper.GetDisplayUrl() throws NullReferenceException if request is lacking host header

### ISSUE THREAD

**Issue by mikeharder** [aspnet/HttpAbstractions#671]
If a client makes a valid HTTP 1.0 request without a host header, UriHelper.GetDisplayUrl() throws NullReferenceException.
# Server Code

``` csharp
public class Program
{
    public static void Main(string[] args)
    {
        new WebHostBuilder()
            .UseKestrel(options =>
            {
                options.UseConnectionLogging();
            })
            .UseStartup<Program>()
            .Build()
            .Run();
    }

    public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
    {
        loggerFactory.AddConsole(LogLevel.Trace);
        var logger = loggerFactory.CreateLogger("Default");

        app.Run(async context =>
        {
            await context.Response.WriteAsync(context.Request.GetDisplayUrl());
        });
    }
}
```
# Client Commands

```
> curl --http1.0 http://localhost:5000
http://localhost:5000/

> curl -v -H "Host:" --http1.0 http://localhost:5000
HTTP/1.1 500 Internal Server Error
```
# Server Log

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Extensions.UriHelper.GetDisplayUrl(HttpRequest request)
```

**Comment by Tratcher** [comment]
Was the Host header requirement a 1.1 addition?

**Comment by mikeharder** [comment]
Yes, it's optional in 1.0: http://stackoverflow.com/a/247026/102052

**Comment by Tratcher** [comment]
Hmm, this method can't generate a complete url without the Host header. Should it throw InvalidOperationException or return an incomplete url like `/path?query` or `http://<unknownhost>/path?query`

**Comment by mikeharder** [comment]
Exception seems bad, since every call to this method would need to be wrapped in a try/catch, sicne the app developer can't control whether clients will send a host header.

Could the method use something like `Dns.GetHostName()` or an IP address if there's no host header?

**Comment by Tratcher** [comment]
LocalIp and port are OK, but also optional for servers. They'll also be different when you're behind IIS/Express.

Guessing is likely to confuse the user. I'd rather indicate that we didn't know.

**Comment by mikeharder** [comment]
I would just use the incomplete URL then (`/path?query`).  At least this is a valid (relative) URL.

**Comment by Tratcher** [comment]
Yeah. The biggest downside is that it drops information you do know, the scheme.

**Comment by mikeharder** [comment]
Agreed, but since there's no standard for "scheme and path without host", I think `/path?query` is better than something we make up like `scheme://<unknownhost>/path?query`.

**Comment by muratg** [comment]
Backlogging for now. If we get enough customer complaint/request, we may reconsider.

**Comment by Flavien** [comment]
This issue also manifests if you use ``IHttpContextAccessor``, which under specific circumstances and when running on Linux will return an ``HttpContext`` that doesn't have a ``Host`` property defined. This doesn't happen on Windows, which makes debugging even more difficult.

**Comment by rynowak** [comment]
Are you trying to do this on a thread that isn't handling a request? None of this stuff is thread safe.

**Comment by Flavien** [comment]
Yes, I'm doing this on a thread that isn't handling a request, so I'm not sure why ``IHttpContextAccessor`` isn't returning null in the first place.

What's not thread safe and why should that have to be thread safe?

**Comment by Flavien** [comment]
Ok I see what's going on: I'm creating a ``Task`` from a request, which continues after the request has completed, so ``IHttpContextAccessor`` thinks I'm running this as part of the request, and because the request has already completed, the ``HttpContext`` that it returns is messed up.

**Comment by Flavien** [comment]
I am puzzled, how can I start a background task from a request without capturing the HttpContext (so that ``IHttpContextAccessor`` return null). I tried everything, and every time, IHttpContextAccessor return the old ``HttpContext``.

**Comment by rynowak** [comment]
>I am puzzled, how can I start a background task from a request without capturing the HttpContext (so that IHttpContextAccessor returns null).

>I tried everything, and every time, IHttpContextAccessor returns the old HttpContext.

If you want to do some work on a background task you need to capture all of the data you want to see up front and then spawn your task. Doing **any** access to an `HttpContext` on a randomly spawned task is going to continue to cause issues for you.

If you can share a little more about what you're trying to accomplish we can provide some suggestions.

Keep in mind, the server is already massively parallel (many requests) so attempting to parallelize the work of a single request is usually an overall loss of performance.

**Comment by Flavien** [comment]
I don't care about performance, I just need the request to complete and return to the client while a long running operation continues running on the server for a couple of minutes. This is fairly standard asynchronous API design.

I'm trying to access the ``HttpContext`` from a custom ``ILogger`` implementation that adds the current request path to the log output **if this is being logged as part of a request**. Of course, I need to be able to detect weather the logging is not being done as part of the request (so that I don't access an invalid ``HttpRequest``). Unfortunately, ``IHttpContextAccessor`` always returns an ``HttpContext`` (sometimes the context of a completely unrelated request), even if not called as part of a request.

**Comment by Tratcher** [comment]
`ThreadPool.UnsafeQueueUserWorkItem`?

**Comment by Flavien** [comment]
This doesn't seem to exist on .NET Core.

**Comment by davidfowl** [comment]
@Flavien unfortunately, until .NET Core 2.0 there isn't an easy way to avoid capturing the async local. Here's a sample of what you could do:

```C#
public class ThreadPoolImpl : IThreadPool
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public ThreadPoolImpl(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public void QueueUserWorkItem(Func<Task> workitem)
    {
        _ = Execute(workitem);
    }

    private async Task Execute(Func<Task> workItem)
    {
        _httpContextAccessor.HttpContext = null;
        await workItem();
    }
}

public interface IThreadPool
{
    void QueueUserWorkItem(Func<Task> workItem);
}
```

Basically just set the `HttpContext` to null before executing the work item. That logic can also be isolated into a service so that you can swap the impl out for a simpler one in .NET Core .2.0

**Comment by Flavien** [comment]
@davidfowl Thanks that seems to work. What are the mechanics behind ``HttpContextAccessor`` and ``AsyncLocal``? It seems to revert to its initial value after ``Execute`` has returned. Is that behavior documented somewhere?

**Comment by volak** [comment]
@muratg I want to make a note - hopefully changing the "backlog" status. 

HaProxy by default will use HTTP/1.0 to do health checks on http servers.  See: https://www.haproxy.com/documentation/aloha/7-0/traffic-management/lb-layer7/health-checks/#check-http-service

This bug causes the service to report NullReferenceExceptions each and every health check

```
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.0 GET http:///health  

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Extensions.UriHelper.GetDisplayUrl(HttpRequest request)
   at ServiceStack.AppHostBase.<ProcessRequest>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

There is a workaround - instead of using the config line `option  httpchk GET /health` you would do `option  httpchk GET /health HTTP/1.1`

but in my case I have little to no control of haproxy config as its set by another package.  I'll have to investigate if there's a way to change this line in their configs

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/issues/1289 would address this.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2718
