### ISSUE TITLE
[Question] EnableRewind in the Microsoft.AspNetCore.Http.Internal namespace

### ISSUE THREAD

**Issue by BadriL** [aspnet/HttpAbstractions#673]
The extension method on request `EnableRewind` is in the `Microsoft.AspNetCore.Http.Internal` namespace. Does that mean we cannot use this method? Being in the internal namespace means for internal use only?

What is the significance of "Internal" namespace in general? I use `Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint` in MVC and `Microsoft.Extensions.Logging.Internal.FormattedLogValues` too.

**Comment by davidfowl** [comment]
Internal means we reserve the right to break the API in between minor/major releases. There's no guarantee or doc comments 😄
