### ISSUE TITLE
ResponseCookiesFeature Allocates when unused

### ISSUE THREAD

**Issue by benaadams** [aspnet/HttpAbstractions#676]
![response-cookie-allocation](https://aoa.blob.core.windows.net/aspnet/rep-cookies.png)

Resolved by: https://github.com/aspnet/HttpAbstractions/pull/675

**Comment by muratg** [comment]
Investigation

**Comment by davidfowl** [comment]
@muratg dude label the bugs..

**Comment by muratg** [comment]
This doesn't seem to have a lot of benefits.

**Comment by benaadams** [comment]
@muratg I would suggest it is absurd though...

So 48MB per 1M requests is being unnecessarily allocated so that in a response where I set cookies on the server (perhaps a login authentication) [it can get a StringBuilder from a pool](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/Internal/ResponseCookies.cs#L48-L65) to set the cookie.

Putting it in context: if per page [the average number of requests is 100](http://httparchive.org/trends.php) and say best case for setting cookie ratio: go to login page, login, see another page. 200 requests allocating 9.6kB for this request feature so that one request can save a little on string concat? Which is very doubtfully going to be 9.6kB saved...

**Comment by benaadams** [comment]
Since you don't like the lazy init approaches, just drop all the allocations entirely? https://github.com/aspnet/HttpAbstractions/pull/699
