### ISSUE TITLE
FormFeature allocates when unused

### ISSUE THREAD

**Issue by benaadams** [aspnet/HttpAbstractions#677]
![form-feature-allocation](https://aoa.blob.core.windows.net/aspnet/form-feature.png)

Resolved by: https://github.com/aspnet/HttpAbstractions/pull/675

**Comment by muratg** [comment]
Investigation

**Comment by muratg** [comment]
Investigation

**Comment by pakrym** [comment]
We don't see difference in performance even when removing FormFeature and CookieFeature allocations completely (https://github.com/aspnet/HttpAbstractions/commit/72d30a5ec0945f60308f235dafa4471069c8d81e).

**Comment by davidfowl** [comment]
You mean throughput. We should be looking at memory as well which this does improve right?

**Comment by pakrym** [comment]
@davidfowl it does, a bit, question is is 88 bytes worth it?

**Comment by davidfowl** [comment]
Every byte counts. If it's easy and non-breaking lets do it. If it complicates things too much then naw.

**Comment by Tratcher** [comment]
So far the solutions have been pretty complicated.

**Comment by benaadams** [comment]
> most real world applications use both cookies and forms.

But not most requests > 50% of webpages ([8M sample](https://css-tricks.com/average-web-page-data-analyzing-8-million-websites/)) have a form and they will be served by a GET request without a form data; as well as all the assets on page (images, fonts, script etc)

A lot of requests and sites are unauthenticated don't have cookies (asset servers) and/or don't care about the cookies (3rd party analytic cookie). There's also vogue not to use cookies but to use [local storage and tokens for auth](https://auth0.com/blog/ten-things-you-should-know-about-tokens-and-cookies/).

So having the features created for every unauthed GET request seems unnecessarily.

> question is is 88 bytes worth it? 

It is when you start densely packing sites on a server with more restricted RAM so the GC becomes more aggressive. You can [create the processes in Jobs](https://blogs.msdn.microsoft.com/maoni/2016/05/23/job-support-in-the-gc/) to simulate this.

**Comment by Yves57** [comment]
Just a question for curiosity: why Factories are not a solution (at least for the less used features)?
I imagine something like `public void Set<TFeature>(Func<TFeature> factory)` in `IFeatureCollection`, that would allow create the feature only the first time it is requested...

**Comment by pakrym** [comment]
@Yves57 that's exactly what I've tried: https://github.com/aspnet/HttpAbstractions/pull/691

**Comment by benaadams** [comment]
@Yves57 its carrying the initalization state for the feature that's problematic

**Comment by muratg** [comment]
This doesn't seem to be bringing a lot of perf benefits.
