### ISSUE TITLE
app.Map blocks root path

### ISSUE THREAD

**Issue by cnblogs-dudu** [aspnet/HttpAbstractions#683]
`dotnet run` the following code in Startup.cs

``` csharp
app.Map("/", _ =>
{
    _.Run((context) =>
    {
        context.Response.Redirect("/markdown/ToHtml");
        return Task.FromResult(0);
    });
});
```

Then get the following exception.

> Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The path must not end with a '/'
> Parameter name: pathMatch
> at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Action`1 configuration)

**Comment by Tratcher** [comment]
As noted in the PR, Map is a StartsWith check, not an Equals check. All paths start with `/`, so `Map("/", ...` does not have a meaningful behavior.

**Comment by khellang** [comment]
@Tratcher Isn't that just an implementation detail? I think `Map("/", /* blah */)` makes perfect sense. I'd just assume it'd strip the trailing slash and do a `StartsWith(string.Empty)`.

**Comment by Tratcher** [comment]
Compare to the normal scenario:
`Map("/foo"...` matches requests `/foo`, `/foo/`, and `/foo/bar`.
But now you're expecting `Map("/"...` to match request `/`, but not `/foo` or `/foo/bar`?

**Comment by khellang** [comment]
No, I'm expecting it to handle `/`, `/foo`, `/foo/` `/foo/bar` etc. Everything, basically :smile:

**Comment by khellang** [comment]
I know that it makes little sense, since you could just do a `.Run` call, but I don't see why it couldn't be allowed?

**Comment by davidfowl** [comment]
It could be allowed but we don't see any benefit in doing so. You can achieve the same thing without a call to Map

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
