### ISSUE TITLE
Need for terminal middleware

### ISSUE THREAD

**Issue by jerriep** [aspnet/HttpAbstractions#686]
I had the following code which used to work fine in RC2

```
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        loggerFactory.AddConsole(LogLevel.Debug);
        
        app.Use(async (context, next) =>
        {
            await context.Response.WriteAsync("<p>Hello from Middleware 1</p>");

            await next.Invoke();
            
            await context.Response.WriteAsync("<p>Goodbye from Middleware 1</p>");
        });

        app.Use(async (context, next) =>
        {
            await context.Response.WriteAsync("<p>Hello from Middleware 2</p>");

            await next.Invoke();

            await context.Response.WriteAsync("<p>Goodbye from Middleware 2</p>");
        });
    }
}
```

But now with 1.0 this does not seem to work anymore. I get the following error:

```
 Connection id "0HKU1UAM61D6F": An unhandled exception was thrown by the application.
System.InvalidOperationException: Status code cannot be set, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.<>c.<Build>b__16_0(HttpContext context)
   at MiddlewareDeepDive.Startup.<>c.<<Configure>b__1_1>d.MoveNext() in C:\Development\AspnetCasts\MiddlewareDeepDive\02 - Your first middleware pipeline\After\MiddlewareDeepDive\Startup.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MiddlewareDeepDive.Startup.<>c.<<Configure>b__1_0>d.MoveNext() in C:\Development\AspnetCasts\MiddlewareDeepDive\02 - Your first middleware pipeline\After\MiddlewareDeepDive\Startup.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

And also I only get the following output displayed:

```
Hello from Middleware 1

Hello from Middleware 2
```

Is this something that has changed in 1.0 RTM? Should the middleware pipeline now always contain terminal middleware at the end on the pipeline?

Edit:
FWIW, here is a video proving that this used to work fine in RC2:
https://www.youtube.com/watch?v=B2WftX-etVo

See from around the 8:20 mark...

**Comment by Tratcher** [comment]
This was a Kestrel bug that was fixed for RTM: https://github.com/aspnet/KestrelHttpServer/issues/805

There is always a terminal 404 middleware at the end of the pipeline. It's failing because the status code can't be changed after you call write.

As a guideline, it's a bad practice to call next if you have started the response. Middleware should produce a response OR call next.

**Comment by jerriep** [comment]
Thanks for explanation @Tratcher

**Comment by joeaudette** [comment]
just fyi, I landed on this issue because I was getting the same exception after upgrading my app to 1.1.

The difference is I was only doing response.writeasync from a controller action not middleware, no exception thrown in my code but after the action method completes kestrel throws this error.

I solved it in my app by changing to return an IActionResult instead of using response.writeasync but it seems weird that you can't do that from a controller action without an error

**Comment by Tratcher** [comment]
@joeaudette when you were calling WriteAsync directly in your controller what were you returning from the controller? MVCs behavior is highly dependent on what you return.

**Comment by joeaudette** [comment]
@Tratcher the action method was just async Task with no return type, I was either setting Response.StatusCode or writing a string into the response. it is a method called by ajax to edit or create a blog post and the string I was writing to the response was just the url for the post on success. So my method was completing with no error and only writing string into the response, then kestrel was throwing this error.
The code changes to solve the error led to better code but still thought you should be able to use response.write without an exception happening after, it worked fine in 1.0 so it is something different in 1.1

**Comment by Tratcher** [comment]
@joeaudette can you share your error and stack trace? I'll ask @ryanbrandenburg to take a look.

**Comment by joeaudette** [comment]
sure I'm logging to json files and this is what it logged:

{"Id":"f36bee83-bd38-4337-9010-a0117bef37a9","LogDateUtc":"2016-11-30T18:08:06.0950414Z","IpAddress":"127.0.0.1","Culture":"en-US","Url":"/Blog/AjaxPost","ShortUrl":"/Blog/AjaxPost","Thread":"","LogLevel":"Error","Logger":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","Message":"An unhandled exception has occurred while executing the request\r\nSystem.InvalidOperationException: OnStarting cannot be set, response has already started.\r\n   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.ThrowResponseAlreadyStartedException(String value)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.OnStarting(Func`2 callback, Object state)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at SaasKit.Multitenancy.Internal.TenantPipelineMiddleware`1.<Invoke>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at SaasKit.Multitenancy.Internal.TenantResolutionMiddleware`1.<Invoke>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()","StateJson":"[{\"Key\":\"{OriginalFormat}\",\"Value\":\"An unhandled exception has occurred while executing the request\"}]","EventId":0}

**Comment by joeaudette** [comment]
if you want to see the diff of what I changed to fix it in my app ie to see more specifically what the method was doing before, it is here: https://github.com/joeaudette/cloudscribe.SimpleContent/commit/19ead4f6e12e0ee76bc17ad89f373542417135b7

**Comment by Tratcher** [comment]
Ahh, that's a different error. You're hitting this: https://github.com/aspnet/Mvc/issues/5555

**Comment by pravinhabbu4u** [comment]
@Tratcher I am facing below issue with Kestrel server in Middleware. I am using           "Microsoft.AspNetCore.Server.Kestrel": "1.1.0". Same code works fine on my local machine with IIS Express, however, it fails whenever I deploy it on Windows server 2012.  Can I help me with the same?

        public async Task Invoke(HttpContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (ShouldRespondToRequest(context.Request))
            {
                await WriteResponseAsync(context.Response).ConfigureAwait(true);
                //await Task.Delay(5000); was trying this to see if issue gets resolved
            }
            //Continue On
            await next.Invoke(context);
            //await next(context).ConfigureAwait(true);

        }

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL2DV24BLUGV": An unhandled exception was thrown by the application.
System.InvalidOperationException: StatusCode cannot be set, response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.<>c.<Build>b__16_0(HttpContext context)
   at GraphQL.Middleware.GraphQLMiddleware.<Invoke>d__4.MoveNext() in C:\Examples\TestGraphQLServer3\src\TestGraphQLServer3\GraphQLMiddleware.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.Middleware.GraphiQLMiddleware.<Invoke>d__5.MoveNext() in C:\Examples\TestGraphQLServer3\src\TestGraphQLServer3\GraphiQLMiddleware.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

**Comment by pravinhabbu4u** [comment]
[https://github.com/wesamco/ASP.Net-Core-GraphQL-Middleware/issues/1#issuecomment-277362355](url)

**Comment by pravinhabbu4u** [comment]
#https://github.com/wesamco/ASP.Net-Core-GraphQL-Middleware/issues/1#issuecomment-277362355

**Comment by Tratcher** [comment]
Return after writeresponseasync, don't call next.

**Comment by pravinhabbu4u** [comment]
@Tratcher  Thanks a ton. It worked like a charm after adding return after adding return in both Middlewares after writeasync

Middleware 1:
        public async Task Invoke(HttpContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (ShouldRespondToRequest(context.Request))
            {
                 
                await WriteResponseAsync(context.Response).ConfigureAwait(true);
                return;
            }

            await next.Invoke(context);
        }

Middleware 2:
        public async Task Invoke(HttpContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (ShouldRespondToRequest(context.Request))
            {
                var executionResult = await ExecuteAsync(context.Request).ConfigureAwait(true);
                await WriteResponseAsync(context.Response, executionResult).ConfigureAwait(true);
                return;
            }

            await next(context).ConfigureAwait(true);
        }

**Comment by HarelM** [comment]
How does one return a proper 404 page? I get the same error as above when using this code:
```
app.Use(async (context, next) =>
            {
                await next();
                if (context.Response.StatusCode == 404)
                {
                    context.Request.Path = "/resourceNotFound.html";
                    await next();
                    // return 404 error code instead of 200 - this will throw...
                    context.Response.StatusCode = 404;
                }
            });
```
Basically what I want to do is return 404 code but present the resourceNotFound.html page.
This was possible with ASP.NET 4 and owin and I can't figure out how to do it with .Net core...?

**Comment by Tratcher** [comment]
@HarelM that worked before because the response body was buffered, so you could change the status code before it was sent. ASP.NET Core does not buffer responses by default. You could enable buffering, but I think there's a better way.

Why not serve the file directly from your middleware? (This would also go at the end of the pipeline rather than in the middle). Something like:
```
Configure(IApplicationBuilde app, IHostingEnvironment hostingEnvironment)
{
...
            app.Run(async context, =>
            {
                    context.Response.StatusCode = 404;
                    var file = hostingEnvironment.WebRootFileProvider.GetFileInfo("/resourceNotFound.html");
                    return context.Response.SendFileAsync(file);
            });
}
```

**Comment by HarelM** [comment]
I'm sorry, can you post the full code? I'm not sure how to change the response.
Somewhere in the pipe line I'll get a 404 code, how would I go about returning the html file?
Something like that?
```cs
app.Use(async (context, next) =>
            {
                await next();
                if (context.Response.StatusCode == 404)
                {
                    app.Run(async context, =>
                   {
                          context.Response.StatusCode = 404;
                          var file = hostingEnvironment.WebRootFileProvider.GetFileInfo("/resourceNotFound.html");
                          return context.Response.SendFileAsync(file);
                  });
                }
            });
```
I haven't tried it yet but I'm not sure I understand how to use the app.Run method...?

**Comment by Tratcher** [comment]
(Actually compiled it this time..)
```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace WebApplication69
{
    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            app.Run(context =>
            {
                context.Response.StatusCode = 404;
                context.Response.ContentType = "text/html";
                var file = env.WebRootFileProvider.GetFileInfo("/resourceNotFound.html");
                context.Response.ContentLength = file.Length;
                return context.Response.SendFileAsync(file);
            });
        }
    }
}
```

Its important to remember that almost nothing in the pipeline returns a 404 by itself. If it can't find a matching resource it just passes control to the next component. There is a default 404 middleware at the end of the pipeline, this sample just replaces that.

**Comment by HarelM** [comment]
Wouldn't have guessed it if my life were dependent on it :-) 
Thanks! working like a charm!
