### ISSUE TITLE
CookieOptions doesn't have MaxAge property

### ISSUE THREAD

**Issue by themacguffinman** [aspnet/HttpAbstractions#688]
Even though `SetCookieHeaderValue` supports it, `CookieOptions` does not have a `MaxAge` property which means that there is no way to append cookies with a Max-Age.

**Comment by Tratcher** [comment]
Interesting, you're the first to ask for it.

Note you can use SetCookieHeaderValue and add the header directly.

**Comment by themacguffinman** [comment]
Thanks @Tratcher.

For anyone reading this, here's a quick extension method that uses `SetCookieHeaderValue` directly:

```
public static class HttpExtensions
{
	public static void AppendCookie(this IHeaderDictionary headers, SetCookieHeaderValue cookie)
	{
		headers[HeaderNames.SetCookie] = StringValues.Concat(headers[HeaderNames.SetCookie], cookie.ToString());
	}
}
```

Usage:
```
Response.Headers.AppendCookie(new SetCookieHeaderValue("usid", String.Empty)
{
	Path = "/",
	HttpOnly = true,
	MaxAge = TimeSpan.Zero,
});
```

**Comment by muratg** [comment]
Thanks for the recommendation. We'll consider post 1.1. Feel free to send a PR :)

**Comment by jkotalik** [comment]
We may also have to modify CookieBuilder.cs to accommodate this change.
