### ISSUE TITLE
PathString implicit string converters are asymmetric 

### ISSUE THREAD

**Issue by jkotalik** [aspnet/HttpAbstractions#690]
In PathString.cs

```
public static implicit operator PathString(string s)
        {
            return new PathString(s);
        }
```

Will create the unescaped new PathString while

```
        public static implicit operator string(PathString path)
        {
            return path.ToString();
        }
```

Will create the escaped ToString.

**Comment by davidfowl** [comment]
That's not great...

**Comment by khellang** [comment]
I thought that was the whole point of `PathString`? Make it easier to do "the right thing" by expecting an unescaped and outputting an escaped string. This prevents someone accidentally `ToString`'ing a path in its unescaped form.

**Comment by Tratcher** [comment]
@khellang We didn't specify which was wrong, just that it's asymmetric. If anything I think it's the string -> PathString converter that's wrong, it should use FromUriComponent to maintain symmetry. Unfortunately that's not how we normally to use it either.

**Comment by muratg** [comment]
This would be a breaking change. We'll reconsider in 2.0

**Comment by Tratcher** [comment]
@muratg we should re-triage this if we're ever going to fix it.

**Comment by HaoK** [comment]
12f89f66a687bdb1c1b683b0d7abd2732c05eb1a
