### ISSUE TITLE
HttpRequest should expose the IRequestFeature.RawTarget value.

### ISSUE THREAD

**Issue by matthewDDennis** [aspnet/HttpAbstractions#692]
Having added the RawTarget property to the IRequestFeature, it would be nice to expose this on HttpRequest.

Secondly, why doesn't HttpRequest inherit from IHttpFeature?  Same question for the other HttpContext properties.  Then when new properties are added to a Feature, the corresponding HttpContext propery would also get it.  In fact, the property could be implemented as a reference to the feature in the HttpContext.Features collection.

**Comment by Tratcher** [comment]
RawTarget was intentionally excluded from the public surface area, it is unsanitized and unsafe general use.

Note that the presentation and organization vary between the HttpContext/Request/Response surface area and the lower level features. HttpContext is about ease of use, where the features are exposing raw data. E.g. IHttpRequestFeature.Path is a string, where HttpRequest.Path is PathString.

**Comment by davidfowl** [comment]
> Having added the RawTarget property to the IRequestFeature, it would be nice to expose this on HttpRequest.

Why do you need it? (Also if you do need it you can access the underlying feature).

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
