### ISSUE TITLE
FormFeature.ReadForm() Incorrect ContentT-Type: Application/json 

### ISSUE THREAD

**Issue by BBoteaWork** [aspnet/HttpAbstractions#694]
Hello,

I am trying to call a Asp.Net Core WebApi Method from JavaScript:

```
// DataModel class
public class User
{
      public string Name { get; set; }
      public string Password { get; set; }
}

// Controller class
[Route("api/[controller]")]
public class UserController : Controller
{
      [HttpPost("/checkCredentials")]
      public bool CheckCredentials(User user)
      {
             if(user.Name == "username1" && user.Password == "pass1") 
                  return true;
             else 
                  return false;
      }
}
```

```
var data = { "Name": "username1", Password: "pass1" };     
$.ajax({
       method: 'POST',
       dataType: 'json',
       contentType: 'application/json',
       url: 'api/User/checkCredentials',
       data: JSON.stringify(user),
       success: function (data) {
             alert(data);
       },
       error: function (error) {}                                   
});
```
**The 'user' parameter is always null.**
After doing some research I have cloned [this MiddlewareSample](https://github.com/aspnet/Docs/tree/master/aspnet/fundamentals/middleware/sample/src/MiddlewareSample) and put a brakepoint in the Startup class to see the Request object ([brakepoint location](https://github.com/aspnet/Docs/blob/master/aspnet/fundamentals/middleware/sample/src/MiddlewareSample/Startup.cs#L25)).
Using the Postman app I have created the same request and it seems that the application/json is not supported by Asp.Net Core (I have seen the code in this repository at **FormFeature.ReadForm()**).
![screenshot from 2016-08-26 16-36-07](https://cloud.githubusercontent.com/assets/21261849/18007107/52ff9c94-6bab-11e6-9959-f84726b3f55f.png)

I have noticed that only the content type application/x-www-form-urlencoded is supported in the method **FromFeature.HasApplicationFormContentType**.

Will this scenario be supported in the near future or is there an workaround?

**Comment by dougbu** [comment]
You're submitting JSON to the service but the `CheckCredentials()` action expects `application/x-www-form-urlencoded` data. Either apply `[FromBody]` to the `user` parameter in the action or change the JavaScript to send `application/x-www-form-urlencoded` data.

**Comment by BBoteaWork** [comment]
Please read more carefully my question. 
I do not wish to change the content type of the call or change the code of the controller. 

> I have noticed that only the content type application/x-www-form-urlencoded is supported in the method FromFeature.HasApplicationFormContentType.

Why the media type 'application/json' is not supported out of the box?

> Will this scenario be supported in the near future or is there an workaround?

**Comment by davidfowl** [comment]
> Why the media type 'application/json' is not supported out of the box?

Because that makes no sense for form posts. Form posts require the content type to be `application/x-www-form-urlencoded` and it's `application/json`. 

> Will this scenario be supported in the near future or is there an workaround?

Not for forms but if you read @dougbu 's reply, he told you how to get it working in MVC.

> I do not wish to change the content type of the call or change the code of the controller.

You have to change the code there's a problem with it.

**Comment by BBoteaWork** [comment]
I have read more and changed my controller so that the parameters have `[FromBody]`,`[FromForm]`,`[FromQuery]`. 
By doing this I was able to send data via `application/json`.
Thank you for support!

**Comment by dougbu** [comment]
Glad you got it working!
