### ISSUE TITLE
IApplicationBuilder.ApplicationServices instance, returns different scoped services/objects from 'HttpContext.RequestServices instance

### ISSUE THREAD

**Issue by jlVidal** [aspnet/HttpAbstractions#697]
Suppose that I registered a scoped service.

`services.AddScoped<IMyService, MyService>();`

Now, consider the following scenario... On startup class:

```
app.Map("/test", level2 =>
{
    level2.Use(
                    a =>
                    {
                        return (b =>
                        {
                                var instance = context.RequestServices.GetService<IMyService>();
                                DoSomething(instance);

                            return a.Invoke(b);
                        });
                    });
    });

     level2.UseStaticFiles(new StaticFileOptions
                   {
                       FileProvider = new MyFileProvider(level2.ApplicationServices);
                   });
}
```

Consider that I'm trying to use IMyService implementation inside of MyFileProvider, but that would happen just when a request comes in. During the same request as the "Use" method, the MyService instance is being created again (same request/same thread, just accessed by IServiceProvider (from IApplicationBuilder.ApplicationServices) instead of IServiceProvider (from HttpContext.RequestServices). 

Anyway, since the service was defined scoped. Is that supposed to be a normal behavior?

**Comment by muratg** [comment]
I believe this is the current design. Services taken from ApplicationServices is not scoped. Does it break any common scenario for you?

**Comment by khellang** [comment]
Actually, the service resolved from `ApplicationServices` ends up being a singleton, because the container is never disposed (before app shutdown). This is something that'should called a captive dependency and will throw an exception in v1.1.

A scoped instance is always resolved from the provider you're asking. There's no shared, scoped instances between providers.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
