### ISSUE TITLE
Make RequestHeaders a struct

### ISSUE THREAD

**Issue by Yves57** [aspnet/HttpAbstractions#700]
`RequestHeaders` are generally allocated one time per request (see the [Response Caching Context](https://github.com/aspnet/ResponseCaching/blob/dev/src/Microsoft.AspNetCore.ResponseCaching/ResponseCachingContext.cs#L36) or my PR about compression in `BasicMiddleware` for example), and it is a small object.
So I suppose it would be be better for the GC to make it `struct` instead of `class`.

**Comment by davidfowl** [comment]
+1, I think these things need an overhaul. They are mostly used to get a typed view of the stringy header collection.

**Comment by rynowak** [comment]
Yes, you can't really use these today in perf-sensitive code. We avoid them in MVC 99% of the time for this reason.

**Comment by Tratcher** [comment]
Breaking change?

Also, when we tried this before with IOwinContext/Request/Response the compiler wouldn't allow it because it thought there were issues with the mutable properties (even though there weren't any actual issues because the properties were mutating non-struct state).

**Comment by Yves57** [comment]
In my compression middleware PR, I just removed 'RequestHeaders' allocation, and I use the low level `StringWithQualityHeaderValue.TryParseList()` code.

But at least I think it would be nice to have extension methods like
```
public static IList<StringWithQualityHeaderValue> GetAcceptEncoding(this IHeaderDictionary headers)
```
* Easy to implement because everything already exists
* Clearer user code
* No perf problem
* Not necessary to use a [KnowListParsers](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/HeaderDictionaryTypeExtensions.cs#L210) map :-)

**Comment by davidfowl** [comment]
Agreed. We can make the breaking changes for v2. All of the existing APIs can be avoided in our code base though. We can also
Improve the quality of the code to be less allocatey without breaking the contract.

**Comment by muratg** [comment]
Breaking change. We'll reconsider in 2.0

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2717
