### ISSUE TITLE
Add PathBase to request as header

### ISSUE THREAD

**Issue by eByte23** [aspnet/HttpAbstractions#702]
Hi,

I recently encountered the issue when reverse proxy with nginx with my site on a sub directory
and I understand this was the fix for future.
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/Extensions/UsePathBaseMiddleware.cs

Would a pr doing something similar to my example here be excepted, or up for discussion as this makes life easy.

https://github.com/eByte23/AspNetCore-pathbase/blob/master/Microsoft.AspNetCore.Http.Abstractions/Extensions/UsePathBaseMiddleware.cs

Thanks

**Comment by davidfowl** [comment]
It doesn't make sense to send it as a header, it's static configuration and should be sent once. That's what happens for IIS in the same configuration. How are you configuring NGINX to pass that information to the application?

**Comment by eByte23** [comment]
Sure, I understand, even if we utilised the same environment varible sent in iis
ASPNETCORE_APPL_PATH?

Did it that same way?

```
server {
        listen       80;
        server_name  localhost;

        location /api {
            proxy_pass http://localhost:17425;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header ASPNETCORE-PATH-BASE "/api";
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection keep-alive;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
```

**Comment by eByte23** [comment]
I just think it should be nice than saying you must define inside a configuration or hard code when other things are done in environment varibles

**Comment by davidfowl** [comment]
@eByte23 What you're trying to achieve is fine. I just don't want any automatic behavior in lower level components. Maybe there's another component that understands `ASPNETCORE-PATH-BASE` as an env variable or header and does the right thing but it shouldn't be the default experience. It should be code in your application, not code in the framework. We've worked extremely hard to remove as much policy as possible from lower level components.

BTW, what stops a client from setting that header and spoofing the path base? Isn's there a security concern there?

**Comment by eByte23** [comment]
@davidfowl Sure, but how would you suggest one would use this for the circumstance where "hey i'll just put this app on a sub dir..." means you would have to change your app code or have a config in there all the time to read it.

If its a no we are never going to this, that's fine I'll just make my own modified version for the env/header version.

Correct, I'm sure there would be I have fully tested the client side putting of that header, I'd image the server defined would override it anyhow.

**Comment by eByte23** [comment]
Okay so I updated it, now it would use the same environment variable as what iis puts in (this could be change to be friendlier). 

```app.UsePathBaseEnvironment();``` which in turn invokes```app.UsePathBase()```
This also adds an optional flag where by if its !pathBase.HasValue then it will continue.

https://github.com/eByte23/AspNetCore-pathbase/blob/master/Microsoft.AspNetCore.Http.Abstractions/Extensions/UsePathBaseMiddleware.cs

**Comment by Tratcher** [comment]
This couples the source of the information and it's application too closely. UsePathBase is just a building block, it's the responsibility of a higher level component to configure and add it to the pipeline. If you look at the IIS code the data comes from config and it only adds the middleware if the key exists at all. I expect we'll do something similar for the proposed UseNginx extension.

https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs

**Comment by eByte23** [comment]
Moved as request. https://github.com/aspnet/Hosting/issues/849
