### ISSUE TITLE
Reduce FormReader allocations

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#707]
1000 requests (I ran a console app in a loop) yields the following.

``` C#
while (true)
{
    Console.WriteLine("Press any key to run");
    Console.ReadLine();

    for (int i = 0; i < 1000; i++)
    {
        var formReader = new FormReader("name=David&Age=12&Developer=Chris");

        var form = formReader.ReadForm();
    }
}
```

![image](https://cloud.githubusercontent.com/assets/95136/18338415/713cdeaa-754d-11e6-8094-eec70572c9c1.png)

**Comment by davidfowl** [comment]
This is post 2.0.0 once we have pipelines + span in place

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2716
