### ISSUE TITLE
WebSockets does not have support for extensions

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/HttpAbstractions#711]
The `WebSocket` class does not have support for extensions. Which is part of the rfc6455 standard:
https://tools.ietf.org/html/rfc6455#section-9

It should read the `Sec-WebSocket-Extensions` HTTP header from the client.

The `WebSocket` class does not expose a `Extensions` property.

**Comment by vanillajonathan** [comment]
Depends on upstream support in `System.Net.WebSockets`.

Depends on issue dotnet/corefx#11874.

**Comment by Tratcher** [comment]
Did you have any specific extensions you want to use?

**Comment by vanillajonathan** [comment]
No, this exposes to the server the extension(s) that the client requests.
Then the server have to negotiate with the client and send back which extensions it supports.

Then any extension has to be implemented by the client and the server on top of this which only exposes the requested extension.

**Comment by Tratcher** [comment]
Note this hasn't been done yet because there has been little interest expressed for any websocket extensions. We're unlikely to add the the property if we don't think it will actually get used.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2715
