### ISSUE TITLE
ApplicationBuilder for testing in TestHost

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/HttpAbstractions#713]
For introspective tests I'd like to add a bit of middleware to the start of the middleware pipeline for diagnostics of the middleware pass bag (properties). 

This time I could get by through overriding my Startup class, add a middleware and calling the base, but I imagine there are enough cases where everyone needs a bit more control.

I've come to the following conclusion:

- I can add a new IApplicationBuilderFactory concrete to the services via ConfigureServices
- That factory builds a special ApplicationBuilder that has methods useful for testing, e.g. more hooks into the moving parts. 

I was expecting to find something like this ready to use in the TestHost package, however no such thing. Is this something you would consider adding?

**Comment by davidfowl** [comment]
You can use an `IStartupFilter` to do this already, no need to replace the `IApplicationBuilderFactory`

**Comment by NinoFloris** [comment]
These IStartupFilters are tacked on the front of the pipeline?
Only have to add it to the services I presume?

Not to be pedantic but where are the docs for this nice piece of extensibility?

**Comment by davidfowl** [comment]
> These IStartupFilters are tacked on the front of the pipeline?

You can add them before or after. Like middleware.

> Only have to add it to the services I presume?

Yep. An example: https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/AutoRequestServicesStartupFilter.cs

> Not to be pedantic but where are the docs for this nice piece of extensibility?

Not sure, can you file an issue on https://github.com/aspnet/Docs.

**Comment by NinoFloris** [comment]
> You can add them before or after. Like middleware.

Well that's not completely true now right?

>  Microsoft.AspNetCore.Hosting.Internal.WebHost:143-155

```cs

    var builder = builderFactory.CreateBuilder(Server.Features);
    builder.ApplicationServices = _applicationServices;

    var startupFilters = _applicationServices.GetService<IEnumerable<IStartupFilter>>();
    Action<IApplicationBuilder> configure = _startup.Configure;
    foreach (var filter in startupFilters.Reverse())
    {
        configure = filter.Configure(configure);
    }

    configure(builder);

    return builder.Build();
```

They are configured before calling the configure delegate, hence they will always be in front of the Startup middlewares.

Thank you for your pointer to this stuff though!

I will reference this issue in a new one on https://github.com/aspnet/Docs.

**Comment by NinoFloris** [comment]
EDIT: nvm, didn't look at the examples.

I thought it was just a middleware func being added, but its a pipeline wrapping the next pipeline.
