### ISSUE TITLE
Add support for facets and structured syntax suffix to MediaType

### ISSUE THREAD

**Issue by khellang** [aspnet/HttpAbstractions#718]
Moved the MediaType parts of issue https://github.com/aspnet/Mvc/issues/5273

It would be nice if `MediaTypeHeaderValue` had support for parsing faceted subtypes and structured syntax suffixes.

See [RFC6838](https://tools.ietf.org/html/rfc6838) for more info.

// @Tratcher

**Comment by muratg** [comment]
Related to #825

**Comment by muratg** [comment]
cc @Eilon we'll be moving some functionality when we do consolidate header parsing logic from MVC (#825)

**Comment by Eilon** [comment]
Please set up a mtg with @Tratcher , @rynowak , @javiercn , @danroth27 , and me.

**Comment by muratg** [comment]
@glennc could you schedule a design meeting?

**Comment by jkotalik** [comment]
@muratg May I go ahead and schedule this?

**Comment by Tratcher** [comment]
MVC wants this, correct?

**Comment by rynowak** [comment]
https://www.youtube.com/watch?v=CeRoi43azds

**Comment by Eilon** [comment]
@rynowak your meme vid has scrombled me.

**Comment by dougbu** [comment]
Put another way&hellip;

Yes, we currently have structured syntax suffix support (see https://tools.ietf.org/html/rfc6839) in our `MediaType` structure.

**Comment by Eilon** [comment]
@jkotalik ỳ̱̻̠̹e̢̼͔s̹̟̜͉̟̱ ̳̟̤͚̹̞͇p͏̠̯͖͖l͇̦e͎a̯̱̬̖s̶̝̗̞͔e̢͈̰͖̣ ̻̳̣͓̘͎͜s̡͇c͔̙͍̪̣h̙̬e͔̞̖̬̺d̦́u̧̩l̡̘͇͙̭̭e̯͍.

**Comment by jkotalik** [comment]
Alright boss.

**Comment by jkotalik** [comment]
@khellang @tuespetre We are currently in the middle of adding this feature to HttpAbstractions. Suffixes will be added in for sure, but we were wondering what are the main use cases for facets that you two are interested in? Currently we are considering providing a property that would return a list of facets. What else, if anything, would you like on top of that?

**Comment by tuespetre** [comment]
@jkotalik The spec seems to indicate that only the text preceding the initial period constitutes 'the facet' of a media type -- singular, similar to how the text following the last plus sign constitutes 'the suffix'. I don't have a use for facets either way, though. A facet is only as useful as its complete subtype while a suffix is going to be equally applicable to all subtypes (over-generalizing)

**Comment by khellang** [comment]
> What else, if anything, would you like on top of that?

If you can get the facets parsed out as an ordered collection of some sort, accessible by index, then that's probably fine. People can do whatever they want with them at that point :smile:

Some examples of faceted media types used in the wild (most of these are [registered with IANA](https://www.iana.org/assignments/media-types/media-types.xhtml)):

- `text/vnd.ascii-art`
- `application/vnd.hal+json`
- `application/vnd.github.v3+json`
- `application/vnd.github.v3.raw+json`
- `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
- `application/vnd.openxmlformats-officedocument.presentationml.presentation`

As you can see, there's a wide range of information contained in different facets. There's honestly very little structure to them besides the first "registration tree" prefix (see [RFC 6838, Section 3](https://tools.ietf.org/html/rfc6838#section-3)), but I don't think that's worth pulling into a separate property.

**Comment by khellang** [comment]
> The spec seems to indicate that only the text preceding the initial period constitutes 'the facet' of a media type -- singular

Heh. Funny. I read it the exact opposite; a sub type can have multiple facets (separated by `.`), and the first facet is called the (registration) tree prefix, similar to the structured syntax suffix.

I see other libraries ([like this, for Node](https://github.com/lovell/media-type)) has a collection for this as well.

**Comment by jkotalik** [comment]
@tuespetre @khellang Thanks. I think from a usability standpoint, having a list of "facets" would be better. It seems like from [RFC 6838 Section 3.2](https://tools.ietf.org/html/rfc6838#section-3.2), a faceted name is considered to contain all segments following the initial name.

**Comment by tuespetre** [comment]
@khellang @jkotalik I caught that and struck through my mistake once I re-read it and realized it meant the "registration facet" when speaking of the initial period. Such mistakes SHOULD cause embarassment and you MAY point and laugh. (Aren't specs fun?)
