### ISSUE TITLE
Encoders for HTML, URL, and JavaScript

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/HttpAbstractions#72]
System.Web.HttpUtility has methods for encoding values for inclusion in HTML attributes JavaScript string literals, etc. We need these again in the this world.

from @DamianEdwards aspnet/mvc#420

**Comment by GrabYourPitchforks** [comment]
PR is out for the HtmlEncode implementation:
https://github.com/aspnet/HttpAbstractions/pull/187

Working on porting UrlEncode, UrlDecode, and HtmlDecode. It'll take a few more days to get those in.

**Comment by GrabYourPitchforks** [comment]
PR https://github.com/aspnet/HttpAbstractions/pull/187 now includes UrlEncode and JavaScriptStringEncode.

**Comment by GrabYourPitchforks** [comment]
PR https://github.com/aspnet/HttpAbstractions/pull/187 now includes UrlEncode and JavaScriptStringEncode.

**Comment by GrabYourPitchforks** [comment]
Committed as https://github.com/aspnet/HttpAbstractions/commit/1008e1725954dd59a157722434c9f823f6160272.
