### ISSUE TITLE
Implement MapRun

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#721]
Map and Run are a common combination. Add an extension that combines the two with MapRun.

Before:

```
            app.Map("/hello", subApp =>
            {
                subApp.Run(context =>
                {
                    return context.Response.WriteAsync("Hello world");
                });
            });
```

After:

```
            app.MapRun("/hello", context =>
            {
                 return context.Response.WriteAsync("Hello world");
            });
```

**Comment by davidfowl** [comment]
There's some overlap here with routing. Also, we don't plan to build a child pipeline for this do we? That seems wasteful.

**Comment by muratg** [comment]
It can be basic sugar method, no?

**Comment by Tratcher** [comment]
Map has semantics about updating PathBase that I don't think would be needed here. `MatchRun` or `RunMatch` might be better. There's no need to build a sub-pipeline or update PathBase.

**Comment by muratg** [comment]
cc @glennc

**Comment by muratg** [comment]
cc @glennc

**Comment by Tratcher** [comment]
Killed by @davidfowl
