### ISSUE TITLE
IApplicationBuilder does not contain a definition for 'XYZ' and the best extension method overload requires a receiver of type IApplicationBuilde

### ISSUE THREAD

**Issue by scionwest** [aspnet/HttpAbstractions#724]
I have an ASP.Net Core web project and a .Net Core Library project. The asp.net project can't find the extension method I've wrote against IApplicationBuilder, even though the extension exists and I can _see_ the static class and the method via intellisense in the asp.net project.

In the library project, I have added the `Microsoft.AspNet.Http.Abstraction` dependency so that I can build an extension method against `IApplicationBuilder`. This is the project.json for it.

    {
    "version": "1.0.0-*",

    "dependencies": {
      "Dapper": "1.50.2",
      "Microsoft.AspNet.Identity": "3.0.0-rc1-final",
      "Microsoft.Extensions.Localization.Abstractions": "1.0.0",
      "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
      "Microsoft.AspNetCore.Http.Abstractions": "1.0.0",
      "Microsoft.Extensions.Options": "1.0.0",
      "NETStandard.Library": "1.6.0",
      "System.Data.Common": "4.1.0"
    },

    "frameworks": {
      "netstandard1.6": {
        "imports": "dnxcore50",
        "dependencies": {
          "DataAccess.Abstraction": {
            "target": "project"
          },
          "Domain.Security": {
            "target": "project"
          },
          "Security.Abstractions": {
            "target": "project"
          }
        }
      }
    }
  }

In that library I have the following extension method

    public static class IApplicationBuilderExtensions
    {
        public static IApplicationBuilder UseTokenProvider(this IApplicationBuilder builder, IConfiguration configuration, Action<TokenProviderOptions> options)
        {
            // .....
            return builder;
        }
    }

In my asp.net project, I've added the library as a project library dependency. This is the project.json

    {
      "dependencies": {
        "Microsoft.AspNetCore.Diagnostics": "1.0.0",
        "Microsoft.AspNetCore.Razor.Tools": {
          "version": "1.0.0-preview2-final",
          "type": "build"
        },
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
        "Microsoft.AspNetCore.Identity": "1.0.0",
        "BundlerMinifier.Core": "2.2.281",
        "Microsoft.ApplicationInsights.AspNetCore": "1.0.1",
        "Microsoft.AspNetCore.Mvc": "1.0.1",
        "Security.AspIdentity": "1.0.0-*",
        "Microsoft.Extensions.DependencyInjection": "1.0.0",
        "Microsoft.Extensions.Configuration": "1.0.0"
      },

      "tools": {
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
        "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final"
      },

      "frameworks": {
        "netcoreapp1.0": {
          "dependencies": {
            "Microsoft.NETCore.App": {
              "version": "1.0.1",
              "type": "platform"
            },
            "DataAccess.Abstraction": {
              "target": "project"
            },
            "DataAccess.SqlServer": {
              "target": "project"
            },
            "Domain.Provider": {
              "target": "project"
            },
            "Domain.Security": {
              "target": "project"
            },
            "Security.Abstractions": {
              "target": "project"
            }
          },
          "imports": [
            "dotnet5.6",
            "portable-net45+win8"
          ]
        }
      },

      "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
      },

      "runtimeOptions": {
        "configProperties": {
          "System.GC.Server": true
        }
      },

      "publishOptions": {
        "include": [
          "wwwroot",
          "Views",
          "Areas/**/Views",
          "appsettings.json",
          "web.config"
        ]
      },

      "scripts": {
        "prepublish": [ "bower install", "dotnet bundle" ],
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
      }
    }

Inside of my `Configure` method, I attempt to add my middleware via the extension method.

    public IConfiguration Configuration { get; set; }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        // ........
        app.UseTokenProvider(this.Configuration, options => { });
            
        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");
        });
    }

However this won't compile. I'm given the following compiler error.

> 'IApplicationBuilder' does not contain a definition for 'UseTokenProvider' and the best extension method overload 'IApplicationBuilderExtensions.UseTokenProvider(IApplicationBuilder, IConfiguration, Action<TokenProviderOptions>)' requires a receiver of type 'IApplicationBuilder'	Apps.Web..NETCoreApp,Version=v1.0

Inside of the `Configure` method, I can type `IApplicationBuilderExtensions.UseTokenProvider` and see it in intellisense. I'm also consuming other Types out of that project (and `IServiceCollection` extensions) in my `ConfigureServices` method, so I know the reference is there and working fine. Why can't it find my extension method against the `IApplicationBuilder`?

**Comment by muratg** [comment]
Probably not related, but why do you have `Microsoft.AspNet.Identity": "3.0.0-rc1-final",` dependency? I wouldn't mix RC1 and RTM bits.

**Comment by scionwest** [comment]
I don't know, that's what the VS package manager used. I searched for Microsoft.AspNet.Identity and that was the only package (non abstraction) that said it was an implementation for score.

**Comment by Tratcher** [comment]
That should be `Microsoft.AspNetCore.Identity`

**Comment by scionwest** [comment]
Thanks I'll change it, sure wish VS would be more helpful with that kind of thing. I think that's independent of my current issue though.

**Comment by scionwest** [comment]
I solved this issue. The problem was that in my static extension methods class, I had `using Microsoft.AspNet.Builder;`. Changing it to `using Microsoft.AspNetCore.Builder;` fixed it. Why does the interface live under two different namespaces in the same assembly?

**Comment by Tratcher** [comment]
It moved and you were probably referencing an old version transitively from Identity.

**Comment by muratg** [comment]
Yeah, it's old and new versions of the assembly (not the same assembly).
