### ISSUE TITLE
Consider increasing HttpResponseStreamWriter.DefaultBufferSize constant

### ISSUE THREAD

**Issue by halter73** [aspnet/HttpAbstractions#725]
As https://github.com/aspnet/Mvc/issues/5364#issuecomment-252486546 demonstrates, increasing `HttpResponseStreamWriter.DefaultBufferSize` to something only marginally larger like 4096, could nearly double the RPS of a controller action writing a large JsonResult.

@ajaybhargavb @Tratcher @mikeharder

**Comment by benaadams** [comment]
Its taken from `ArrayPool` so shouldn't cause any extra memory use. On thing to watch is the overall distribution of default sizes (which should be powers of 2) as if they are all the same that may increase contention on a particular bucket of the pool.

**Comment by ajaybhargavb** [comment]
cc @rynowak

**Comment by mikeharder** [comment]
@halter73: Were thoughput tests run on the scenario in https://github.com/aspnet/Mvc/issues/5364#issuecomment-252486546?  The data I see in that issue is for single-request latency rather than throughput.

**Comment by halter73** [comment]
Yeah. I'm extrapolating a bit. It's really reducing the latency for requests made over a single connection. I could be wrong about the RPS improvement, but it stands to reason.

**Comment by mikeharder** [comment]
Also, is this the correct place to improve performance, or should it be done at an even lower layer?  Why does the buffer size at this layer make such a large difference?

**Comment by halter73** [comment]
My suspicion is after Kestrel's response buffer fills up and flushes (at least partially), it causes a 1KB write instead of a potentially larger (e.g. 4KB) write which would be more efficient. This could be mitigated by something like nagleing or making Kestrel's default response buffer larger, but these both have trade offs like increased write latency and higher memory usage respectively.

**Comment by rynowak** [comment]
@mikeharder - we're still not done collecting data for #5364

**Comment by muratg** [comment]
@halter73 Do we have recent measurements with the increased buffer size?  Do we still want to do this in 2.0.0?

**Comment by halter73** [comment]
MVC already bumped [MemoryPoolHttpResponseStreamWriterFactory.DefaultBufferSize](https://github.com/aspnet/Mvc/pull/6192/files) buffer size from 1k to 16k. That's what's used to serialize JsonResults by default.

Based on https://github.com/aspnet/Mvc/pull/6192, `HttpResponseStreamWriter.DefaultBufferSize` isn't actually used anywhere other than tests, so maybe that const should just be removed.

If the `HttpResponseStreamWriter.DefaultBufferSize` isn't removed, then it probably should be increased. I experimented again with changing the buffer sizes for the WebApiPerformance sample I used in the original MVC issue. With a 1k buffer, a response to about 80ms on average. With a 16k buffer, the average was 55ms.

**Comment by muratg** [comment]
@natemcmaster moved this to you from @JunTaoLuo. You can ping @halter73 for details.

**Comment by natemcmaster** [comment]
Discussed with @halter73. It appears this API isn't in use anywhere in our stack, so we're can remove the public const. However, we still need a default unless we want to drop the `HttpResponseStreamWriter(Stream stream, Encoding encoding)` we still need a default. 

What I've proposed in #877 is that we make `DefaultBufferSize` internal, and increase it to 16k to match what MVC has done.
