### ISSUE TITLE
QueryHelpers should have a function to build parameters

### ISSUE THREAD

**Issue by pebezo** [aspnet/HttpAbstractions#726]
In QueryHelpers we have ParseQuery() that returns Dictionary<string, StringValues>, however, there's no function to put those back together. 

Internally the functionality is already there: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/QueryHelpers.cs#L92 but it's not accessible from outside.

Would you consider a function that would basically build a string out of Dictionary<string, StringValues>? (could send PR)

**Comment by Tratcher** [comment]
What about https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/QueryHelpers.cs#L48
or
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/QueryString.cs#L158
?

**Comment by pebezo** [comment]
The first link won't work because I actually need to remove a parameter from the URL. The second link is pretty much what I ended up using. 

The only difference is that the first character of the returned string is "?", and when I assign that to UriBuilder.Query it duplicates it ( although, according to source, it shouldn't https://github.com/dotnet/corefx/blob/master/src/System.Private.Uri/src/System/UriBuilder.cs#L278 ). 

That may be more of a UriBuilder issue; here's a repro:

var builder = new UriBuilder("http://example.com/");
builder.Query = "?foo=bar"; // builder.Query is now "??foo=bar"

(It would've been nice to have all this functionality in one place; I got no hits for QueryString via Google)

**Comment by Tratcher** [comment]
Yeah, that's a known issue with System.UriBuilder. Those issues can go here:
https://github.com/dotnet/corefx
https://github.com/dotnet/corefx/issues/12421

**Comment by pebezo** [comment]
If you're considering adding this to UriBuilder then that's even better. Feel free to close this issue.

**Comment by muratg** [comment]
Closing based on the comments. System.UriBuilder change requests should go to dotnet/corefx.
