### ISSUE TITLE
HttpResponse.Redirect() accepts a string, not a PathString

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/HttpAbstractions#727]
Shouldn't the `Redirect` method in the `HttpResponse` class accept a `PathString` as the parameter, instead of a `string`?

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/HttpResponse.cs#L99

**Comment by Tratcher** [comment]
No, redirects often include more than paths. They may be paths, path+query, or an absolute url. PathString can be used to build the redirect though, its default conversion ToString encodes the path for use in a header.

**Comment by vanillajonathan** [comment]
Thanks for the clarification.
