### ISSUE TITLE
Make sure IHttpContextAccessor is always registered

### ISSUE THREAD

**Issue by dotnetjunkie** [aspnet/HttpAbstractions#728]
The `IHttpContextAccessor` allows access to the current executing `HttpContext` and seems to be a core component of ASP.NET. Still however, the `IHttpContextAccessor` is not registered by default by ASP.NET while it IMO definitely should.

The whole idea behind the new configuration model in ASP.NET is that everything is registered for you magically behind the covers, but even if you call `AddMvc` or even `AddMvcCore` the `IHttpContextAccessor` isn't registered, while there are many integration scenarios that require its availability. This means that 3rd parties (or possibly even future framework components) always need to check its availability and throw an exception when it's not registered and application developers always need to register it manually.

**Comment by davidfowl** [comment]
> The whole idea behind the new configuration model in ASP.NET is that everything is registered for you magically behind the covers, but even if you call AddMvc or even AddMvcCore the IHttpContextAccessor isn't registered, while there are many integration scenarios that require its availability. This means that 3rd parties (or possibly even future framework components) always need to check its availability and throw an exception when it's not registered and application developers always need to register it manually.

Not everything, everything that is required. We did extra work to make sure that our own types don't rely on it (because ambient state is bad and hard to reason about). 

One of the reasons we took it out for performance. We don't want every ASP.NET application to enable execution context copies (what happens as soon as you use async local). Also, we don't really want users to use this type unless they need it.

**Comment by davidfowl** [comment]
Though to be honest, if nobody resolves it, there should be no cost.

**Comment by dotnetjunkie** [comment]
> One of the reasons we took it out for performance.

I find it hard to believe that the use of such Ambient Context will actually cause any detectable performance hit. Especially with all the I/O going on. Have you actually measured this and publically described this somewhere what the performance impact is?

> we don't really want users to use this type unless they need it.

I don't believe that adding this by default will cause users to automatically use it. I just think that not adding it by default will simply cause users to add it by hand. 

> because ambient state is bad

Apparently not that bad, because ASP.NET uses it for logging scopes.

> every await and dispatch to threadpool is no longer on the default execution context fast path.

Since everybody uses logging in their application, doesn't this mean that we never run on this context fast path?

**Comment by benaadams** [comment]
> > because ambient state is bad

> Apparently not that bad, because ASP.NET uses it for logging scopes.

Only ConsoleLogScope alters the execution context in this way

**Comment by davidfowl** [comment]
Ah yes that was the problem with turning it on by default. *We* need to resolve it ourselves to set it. It needs to be added by the components that need it.

**Comment by davidfowl** [comment]
> I find it hard to believe that the use of such Ambient Context will actually cause any detectable performance hit. Especially with all the I/O going on. Have you actually measured this and publically described this somewhere what the performance impact is?

Yes, @benaadams measured it as part of our benchmarks runs and it was significant. Scoped logging *does* tend to use async local as well so the cost might be incurred there depending on the logging system. These things are fine, they just can't be all on by default.

**Comment by dotnetjunkie** [comment]
> Yes, @benaadams measured it as part of our benchmarks runs and it was significant.

Can you link to his benchmark results?

**Comment by davidfowl** [comment]
This was the change that disabled it. 
- First the benchmark - https://github.com/aspnet/benchmarks/commit/909a929d2b37a57934b92de1ef760d55f3b65d43
- Officially removed- https://github.com/aspnet/HttpAbstractions/pull/475

Can't find any performance numbers on the repo but you might be able to the differences in the excel spreadsheet in the **Updated Results** commit after the change:

https://github.com/aspnet/benchmarks/commits/dev?after=G6n%2FgPpHkWvHSt0NmAuyU1ZqXqIrMTM5

**Comment by benaadams** [comment]
> Have you actually measured this and publically described this somewhere what the performance impact is?

https://github.com/aspnet/Hosting/issues/330
https://github.com/aspnet/Hosting/issues/356

On 4.6+ it allocates 680k per 2000 requests and creates an addtional dictionary per request

Every await that is async allocates an additional 8 bytes https://github.com/dotnet/coreclr/pull/3157

When the HttpContext is set [ExecutionContext.SetLocalValue](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/ExecutionContext.cs#L205-L250) is additionally run

**Comment by benaadams** [comment]
You don't normally need to use IHttpContextAccessor as DI will inject the HttpContext for you if you ask for it.

**Comment by davidfowl** [comment]
You don't normally need ambient state. It shouldn't be the default way of doing things. This is an  optional convenience for people. Unfortunately it's required to get the scoped service provider for scenarios like this https://github.com/aspnet/Mvc/issues/5403

**Comment by davidfowl** [comment]
Moar perf numbers - https://github.com/aspnet/Mvc/issues/3523

**Comment by dotnetjunkie** [comment]
What I see is that the there is especially a perf hit under .NET 4.5.1 where there is no optimized AsyncLocal. Besides that, we will see the improvement be deminished when any I/O is done. But since this optimization is a very conscious action, I understand that you won't go to the 'default on' scenario. It's unfortunate though that this makes less intuitive for non-conformers.

**Comment by davidfowl** [comment]
@dotnetjunkie It shouldn't be exposed if you add the right services. `services.AddSimpleInjectorServices()`

**Comment by dotnetjunkie** [comment]
> It shouldn't be exposed if you add the right services. services.AddSimpleInjectorServices()

@davidfowl that's a discussion for a different thread.

**Comment by Metamorphus** [comment]
OK, but what if I need access to HttpContext inside my class library. I'll have to oblige all the developers using it to register HttpContextAccessor? My library is for web applications, so it should be able to get the request domain.

P.S. Passing HttpContext from client code's contorollers to my class isn't an option either: clients can create web applications without MVC.

**Comment by dotnetjunkie** [comment]
> You don't normally need to use IHttpContextAccessor as DI will inject the HttpContext for you if you ask for it; and then is scope is more controlled (as you shouldn't be using it outside of a request)

@benaadams, injecting `HttpContext` directly into a component's constructor is a bad idea, because `HttpContext` is runtime data and [runtime data should not be injected into application components during construction](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99). 

It's for [this very reason](https://github.com/aspnet/Identity/issues/674) that Identity Framework [fixed a bug](https://github.com/aspnet/Identity/commit/167bb54c8d7aaafa12983164f8033cc25d0af39e#diff-bfbbcc7825aec8772885e70b17f60a84R44) prevented the `SignInManager` from taking `HttpContext` as constructor argument.

**Comment by Tratcher** [comment]
> P.S. Passing HttpContext from client code's contorollers to my class isn't an option either: clients can create web applications without MVC.

How do client's call your library? HttpContext is not part of MVC, it's part of the underlying ASP.NET Core framework.

**Comment by Metamorphus** [comment]
Sorry, my library needs request domain just to check its license (license keys are bound to domains). Its functionality doesn't depend on ASP.NET.

**Comment by benaadams** [comment]
@Metamorphus add an extension method for your product that people call in ConfigureServices.
```csharp
public static class MyProductServiceCollectionExtensions
{
    public static void AddMyProduct(this IServiceCollection services)
    {
        services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
    }
}
```

**Comment by davidfowl** [comment]
@dotnetjunkie it's not really registered by default. It depends on what template you use... 😄

**Comment by dotnetjunkie** [comment]
@davidfowl Can you give more information about this? What do you mean by template?

**Comment by davidfowl** [comment]
Its likely application insights adding it for their own usage. There's a new feature in the WebHost that lets various hosting environments inject application logic. Visual Studio injects the application insights logic in debug only and that's likely what you're seeing.

**Comment by dotnetjunkie** [comment]
I can confirm that when ran outside of Visual Studio, the `IHttpContextAccessor` registration is missing, while when running from Visual Studio, it actually _is_ registered.

Could you be more specific and describe _what_ exactly is adding the `IHttpContextAccessor` registration?

I do think that it is a pretty bad idea to have such central abstraction registered conditionally. This can easily lead developers dazzled, since the application runs on their machine, but breaks once deployed.

**Comment by khellang** [comment]
A GitHub "stack trace"... 😂

- https://github.com/aspnet/AzureIntegration/blob/9b9bb4dde7e9fa1bcfb31019ba9453882e1a318f/src/Microsoft.AspNetCore.ApplicationInsights.HostingStartup/ApplicationInsightsStartupLoader.cs#L32
- https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/f696dd44f55055fad1774154219acf6c1e32c99b/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsWebHostBuilderExtensions.cs#L22
- https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/c7e34ea2484f90a542e000c7a98656bf45ccf436/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs#L130

`ApplicationInsightsHostingStartup` will be injected, discovered (notice [the assembly-level `HostingStartup` attribute](https://github.com/aspnet/AzureIntegration/blob/9b9bb4dde7e9fa1bcfb31019ba9453882e1a318f/src/Microsoft.AspNetCore.ApplicationInsights.HostingStartup/ApplicationInsightsStartupLoader.cs#L12)) and run from Visual Studio, Azure App Service etc., without you calling anything. Pretty scary, right? 😝
