### ISSUE TITLE
Wrong ip address via proxy?

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/HttpAbstractions#730]
```
 httpContext.Connection.RemoteIpAddress
```

That's the code which I use to get the ip address

When I connect from home, I get "good" ip address,
When I connect via company internet (which use proxy,etc2)
I get 

127.0.0.1

**Comment by khellang** [comment]
Are you using `Microsoft.AspNetCore.HttpOverrides` to set `RemoteIpAddress` using the `X-Forwarded-For` header? What proxy are you using? Is it even sending a `X-Forwarded-For` header?

**Comment by andrew-vandenbrink** [comment]
No, I'm not using HttpOverrides

Not sure what the proxy is, how do I check?

I don't see the header X-Forwarded-For,
![image](https://cloud.githubusercontent.com/assets/12871379/19592133/a9f23d86-977a-11e6-9764-7eef9301c089.png)

**Comment by khellang** [comment]
That's the request sent from your browser. The proxy will add the header before passing the request to your server. You need to check the headers on your server, not the client :smile: Or you could just try to add the HttpOverrides middleware and see if that helps :wink:

**Comment by andrew-vandenbrink** [comment]
Ah ok I get it, but

Can we not add those checking (if x-forwarded-for header exists bla2) just like on this link when we call  httpContext.Connection.RemoteIpAddress ?

http://stackoverflow.com/questions/735350/how-to-get-a-users-client-ip-address-in-asp-net

**Comment by khellang** [comment]
> Can we not add those checking (if x-forwarded-for header exists bla2) just like on this link when we call httpContext.Connection.RemoteIpAddress ?

That's kinda against the "pay-to-play" mantra of ASP.NET Core. It comes with almost nothing out-of-the-box and you add whatever you need. Some people might not need to check the `X-Forwarded-*` headers.

If you add `Microsoft.AspNetCore.HttpOverrides` and call `app.UseForwardedHeaders()`, this is exactly what you'll get. You can just call `httpContext.Connection.RemoteIpAddress` and get the "proper" IP address.

**Comment by andrew-vandenbrink** [comment]
Not sure if I can agree with "pay-to-play" in this context, because in this case "Remote" returning "localhost" ip address...

**Comment by khellang** [comment]
"Pay-to-play" in this context means that if you don't want/need to bother with `X-Forwarded-*` headers, you shouldn't have to :smile:

> in this case "Remote" returning "localhost" ip address...

If you're making a request from localhost, that's the correct IP-address :smile:

**Comment by Tratcher** [comment]
If you're running the site behind IIS then the localhost address refers to IIS. UseForwardedHeaders is included by default by UseIISIntegration, but proxies can mess up the x-forwarded-* headers so they won't get process by the default configuration.

**Comment by Tratcher** [comment]
Dump out the request headers as received in your app, there are probably unexpected values in the x-forwarded-* headers.

**Comment by andrew-vandenbrink** [comment]
I'll get back tomorrow...

**Comment by andrew-vandenbrink** [comment]
Dump looks ok

![image](https://cloud.githubusercontent.com/assets/12871379/19673949/c14a4cc8-9a84-11e6-9434-6cd5a9a7feb9.png)

**Comment by Tratcher** [comment]
Any other x- headers? Its also expecting Proto from IIS. You'll probably need to set ForwardedHeaderOptions. RequireHeaderSymmetry = false. 
https://github.com/aspnet/IISIntegration/blob/dev/samples/IISSample/Startup.cs

**Comment by andrew-vandenbrink** [comment]
![image](https://cloud.githubusercontent.com/assets/12871379/19674930/a60580d4-9a8b-11e6-9a58-47e0fa475ddd.png)

There is proto

**Comment by Tratcher** [comment]
Yeah, see https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.HttpOverrides/ForwardedHeadersOptions.cs#L70-L74

**Comment by andrew-vandenbrink** [comment]
I can't change setting just because this proxy, what about other proxy which behave differently...

**Comment by Tratcher** [comment]
Changing the setting to be less strict should work with most kinds of proxies.

**Comment by andrew-vandenbrink** [comment]
New discussion here

https://github.com/aspnet/HttpAbstractions/issues/730
