### ISSUE TITLE
Should we white list the set of charset on MediaTypeHeaderValue

### ISSUE THREAD

**Issue by javiercn** [aspnet/HttpAbstractions#731]
See 
https://github.com/aspnet/Mvc/pull/5415 and
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/MediaTypeHeaderValue.cs#L88 for details

**Comment by Tratcher** [comment]
MediaTypeHeaderValue is just a parser/representation. It is not it's place to have policy opinions.

**Comment by Eilon** [comment]
This is pending a discussion with the .NET team, so no action to take just yet.

**Comment by dougbu** [comment]
Discussion concluded. No action needed here.
