### ISSUE TITLE
`NameValueHeaderValue` and `MediaTypeHeaderValue` mishandle quoted parameter values

### ISSUE THREAD

**Issue by dougbu** [aspnet/HttpAbstractions#732]
Parsing `text/json; version="23"` using `MediaTypeHeaderValue` creates a `NameValueHeaderValue` for `version` with `Value=="\"23\""`. This is incorrect because `text/json; version=23` and `text/json; version="23"` should be 💯% semantically identical.

See aspnet/Mvc#5349 for a similar issue we recently fixed in MVC.

**Comment by dougbu** [comment]
FYI @Tratcher @Eilon

**Comment by Eilon** [comment]
Do you mean it creates Value = `"23"`? It's not clear to me from your formatting what the problem is.

**Comment by dougbu** [comment]
I mean the `Value` includes the surrounding quotes for a quoted parameter value in a media type string. These quotation marks should be ignored when creating the `Value`.

Put another way, the `NameValueHeaderValue` for a media type containing `version=23` will have no quotes in the `Value` while one for a media type containing `version="23"` will. The two `Value`s should be the same.

**Comment by Eilon** [comment]
Got it.

**Comment by Tratcher** [comment]
@jkotalik update: it's ok for NameValueHeaderValue to remove the quotes from Value. But however you do it, you also need to make sure quotes get added to the final wire read ToString output when required. The simplest out for this is to strip the quotes only from the .Value getter. The parser and setter will make sure any values that require quotes will have them (though it won't add them for you, maybe it should to make the round trip scenario easier).

**Comment by jkotalik** [comment]
@Tratcher @dougbu @Eilon I believe this would be a breaking change for 2.1. People may only be checking for the Value that contains quotes. Maybe consider for 3.0?

**Comment by jkotalik** [comment]
I've got a WIP on https://github.com/aspnet/HttpAbstractions/commits/jkotalik/MTHV

I do want to mention that this would be a breaking change, @davidfowl @Eilon @muratg may want to confirm that we want to do this change.

**Comment by Eilon** [comment]
@jkotalik can you describe exactly what the breaking change is w/ an example?

**Comment by jkotalik** [comment]
With the changes I made, every time we access the getter of Value, the returned value would not include any quotes around it. One small problem is that if a customer were to use the properties of NameValueHeaderValue instead of ToString(), like:
```
var nameValue = new NameValueHeaderValue("name", "\"value\"");
var str = nameValue.Name + "=" + nameValue.Value;
```
Before this would return the quoted value, while with this change it would return the unquoted Value. I'm not sure how many people are even using NameValues directly, however it is something to consider.

**Comment by Eilon** [comment]
This sounds a little odd to me. I think it's one thing if we're *parsing* an HTTP header and do some stripping of quotes (presumably, per some RFC), but it's another thing entirely to strip off quotes from explicit names/values.

Pseudo-code:

```c#
// CASE 1: Parsing an entire header with weird stuff
var headerValue = "text/json; version=\"23\"";
var parsedHeader = HeaderParserThingy.Parse(headerValue);
var newValue = parsedHeader["version"].Value;
// I assume the fix here is that we used to return newValue = "\"23\"", and with the fix we'd return newValue = "23".

// CASE 2: Parsing an entire header with simple stuff
var headerValue = "text/json; version=23";
var parsedHeader = HeaderParserThingy.Parse(headerValue);
var newValue = parsedHeader["version"].Value;
// I assume that this would always return newValue = "23" (with and without the fix)

// CASE 3: Constructing a new header with weird stuff
var nameValue = new NameValueHeaderValue("value", "\"23\"");
var newValue = nameValue.Value;
// I feel that this should *always* return newValue = "\"23\"", and never return newValue = "23".

// CASE 4: Constructing a new header with simple stuff
var nameValue = new NameValueHeaderValue("value", "23");
var newValue = nameValue.Value;
// I think we all agree that this should *always* return newValue = "23".
```

Thoughts on these?

**Comment by dougbu** [comment]
What are some non-test scenarios in which `NameValueHeaderValue` instances are created (not parsed)? I thought the constructors existed primarily for use when parsing received headers and dev-specified media type strings.

Put another way, am I forgetting a bunch 'o public API using `NameValueHeaderValue` instances instead of `string`s?

**Comment by jkotalik** [comment]
I do believe that most of the `NameValueHeaderValue` uses cases are internal, so it shouldn't be a big deal to change this. I did a build of 

@Eilon when I implemented this, I made both case 1 and case 3 return the unquoted string as I wanted both the constructor and the parser to be consistent. There are issues though when we have a value that requires quotes.
Pseudo-code 

```c#
var headerValue = "text/json; someField=\"quoted string\"";
var parsedHeader = HeaderParserThingy.Parse(headerValue);
var newValue = parsedHeader["version"].Value;
// newValue = "quoted string"
```
Maybe we can just remove the quotes if the token doesn't need to be quoted?

**Comment by dougbu** [comment]
> Maybe we can just remove the quotes if the token doesn't need to be quoted?

That'll work. But, it's also important to
1. expose what's between the quotes for further processing
``` c#
var headerValue = "text/json; someField=\"quoted;string\"";
var parsedHeader = HeaderParserThingy.Parse(headerValue);
parsedHeader["version"].Value;
// "quoted;string"
```
  or, more realistically
``` c#
var headerValue = "text/json; someField=\"23\"";
var parsedHeader = HeaderParserThingy.Parse(headerValue);
parsedHeader["version"].Value;
// "23"
int.TryParse(parsedHeader["version"].Value;, out var fred)
// true
fred
// 23
```
2. ensure quoting doesn't change the value, just allows additional characters
``` c#
var headerValue1 = "text/json; someField=\"string\"";
var parsedHeader1 = HeaderParserThingy.Parse(headerValue);
var headerValue2 = "text/json; someField=string";
var parsedHeader2 = HeaderParserThingy.Parse(headerValue);
parsedHeader1.Equals(parsedHeader2)
// true
parsedHeader1.IsSubsetOf(parsedHeader2)
// true
```
3. ensure round trip doesn't lose quotes and quoted pairs when they're needed
``` c#
var headerValue = "text/json; someField=\"quoted ; \\" string\"";
var parsedHeader = HeaderParserThingy.Parse(headerValue);
parsedHeader.ToString()
// "text/json; someField=\"quoted ; \\" string\""
// "text/json; someField=\"quoted \\; \\" string\"" would also be fine
```

**Comment by jkotalik** [comment]
Per offline discussion with @Eilon  and @Tratcher , we are going to add two methods to NameValueHeaderValue called GetEncodedValue() and SetValueAndEncode() (pending name change) that will remove quotes from the Value if they exist.
