### ISSUE TITLE
`DefaultHttpResponse` does not account for other redirect status codes

### ISSUE THREAD

**Issue by smarts** [aspnet/HttpAbstractions#735]
[Status codes 303, 307, & 308](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection) are valid redirect codes and should be incorporated into `DefaultHttpResponse`. My guess is that 303 probably isn't a big deal, but the other 2 should definitely be handled.

**Comment by Tratcher** [comment]
You mean the `public override void Redirect(string location, bool permanent)` API?
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/Internal/DefaultHttpResponse.cs#L125

Is this theoretical or do you really want to send 307/308 in your app?

**Comment by smarts** [comment]
Yup, that's the API. And no, it's not theoretical.

**Comment by smarts** [comment]
What do you think about adding `bool preserveMethod` as an optional parameter to the Redirect() method?

**Comment by muratg** [comment]
Putting this in Discussions now. Let's see if we get more feedback on these newer status codes.

In the meantime, @smarts, you could write your own extension methods to get this functionality.

**Comment by smarts** [comment]
True, but what I can't do is change the existing `RedirectToRouteResult` to add a `PreserveMethod` property so that I can take advantage of this in the built-in `RedirectToRoute()` and `RedirectToRoutePermanent()` controller methods.

**Comment by Tratcher** [comment]
So even if we added this here you'd also want changes to MVC.

**Comment by smarts** [comment]
Yes, @Tratcher. The `RedirectToRouteResult` (and the other redirect result classes) would presumably need to add a `PreserveMethod` property so that `RedirectToRouteResultExecutor` can propagate it down to the `HttpResponse.Redirect()` call.

**Comment by Tratcher** [comment]
Please file another bug on MVC. That can be implemented independent of this one.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
