### ISSUE TITLE
IHeaderDictionary should be IRequestHeaderDictionary and IResponseHeaderDictionary

### ISSUE THREAD

**Issue by danroth27** [aspnet/HttpAbstractions#740]
As reported by @nathan-alden in https://github.com/aspnet/Mvc/issues/5532:

IHeaderDictionary should be IRequestHeaderDictionary and IResponseHeaderDictionary, each with properties defined for each standard HTTP header, the way it was with Web API 2's HttpRequestHeaders and HttpResponseHeaders classes. Why remove this very useful abstraction? I can't extend IHeaderDictionary because then those extensions would improperly apply to both request and response headers and the members would have to be methods instead of properties. As a result, we're back to accessing headers using Dictionary with magic strings for keys.

**Comment by davidfowl** [comment]
http headers are fundamentally loosely typed dictionaries, the lower level abstraction represents that. Typed headers are a layer on top that can be accessed via the `GetTypedHeaders()` extension method.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/HeaderDictionaryTypeExtensions.cs
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/RequestHeaders.cs
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/ResponseHeaders.cs

**Comment by nathan-alden** [comment]
Cool! That's exactly what I was looking for. Thank you!
