### ISSUE TITLE
IResponseCookies.Delete fails to work in Chrome but works in Edge and Firefox

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#743]
_From @dodyg on December 13, 2016 8:0_

This is the code to replicate this behavior [source](https://github.com/dodyg/practical-aspnetcore/blob/master/hello-world-with-cookies-2/src/Program.cs)

This is another person that replicate the problem [source](https://www.reddit.com/r/dotnet/comments/5hznok/how_do_you_delete_a_cookie_in_aspnet_core/db4syx4/)

`dotnet -version` is `1.0.0-preview2-1-003177`

_Copied from original issue: aspnet/Home#1877_

**Comment by xenolightning** [comment]
Cookies are correctly removed from the response using the source example.

Chrome requests "favicon.ico" in a subsequent request, which in this case, is causing the cookie to be served back to the browser.

Suggest closing.
