### ISSUE TITLE
Getting the Request.Form value causes InvalidOperationException

### ISSUE THREAD

**Issue by jchannon** [aspnet/HttpAbstractions#744]
I had some owin middleware which basically looped over the dictionary to log the key and value of the request/response objects.

```                      
foreach (var item in env)
{                                                
    tracer.Trace(requestId, item.Key, item.Value);
}
```

I tried moving my middleware to ASPNet Core and decided that having to use reflection was the only way.  However as I loop over the request, even on a GET request when it gets to the Form property it results in an exception

```
var reqProps = context.Request.GetType().GetTypeInfo().GetProperties();
foreach (var prop in reqProps)
{
       this.tracer.Trace(requestId, prop.Name, prop.GetValue(context.Request)); /*** BOOM ***/
}
```

I think its being thrown here https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http/Features/FormFeature.cs#L97 however I'm not sure how its even got to that `ReadForm` method by just trying to read the value of the Form which is basically a `IEnumerable`

**Comment by Tratcher** [comment]
By-design. The Form property will try to read the request body if it has not been read yet. This will fail if the request did not have the proper content-type. See https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http/Internal/DefaultHttpRequest.cs#L138-L147

**Comment by jchannon** [comment]
Thanks

Do you know of any safe middleware that logs request, connection, user, response information?

**Comment by Tratcher** [comment]
Have you tried https://github.com/aspnet/Diagnostics/tree/dev/src/Microsoft.AspNetCore.Diagnostics.Elm?

You can log everything yourself but blind reflection isn't the best way to do it. Just directly log the properties you care about, and check HasFormContentType before checking Form.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
