### ISSUE TITLE
Add support for IMiddlewareFactory and IMiddleware

### ISSUE THREAD

**Issue by halter73** [aspnet/HttpAbstractions#754]
The `IMiddlewareFactory` is a new extensibility point for middleware activation that would be registered with the application's  container. The default `IMiddlewareFactory` should be registered as a scoped service, and (maybe) only resolve `middlewareType`s that are already registered in the container.

Hosting will probably need to add the default `IMiddlewareFactory` to the container, but the implementation can stay in HttpAbstractions.

```c#
namespace Microsoft.AspNetCore.Http
{
    /// <summary>
    /// Provides methods to create middlware.
    /// </summary>
    public interface IMiddlewareFactory
    {
        /// <summary>
        /// Creates a middleware instance for each request.
        /// </summary>
        /// <param name="middlewareType">The concrete <see cref="Type"/> of the <see cref="IMiddleware"/>.</param>
        /// <returns>The <see cref="IMiddleware"/> instance.</returns>
        IMiddleware Create(Type middlewareType);

        /// <summary>
        /// Releases a <see cref="IMiddleware"/> instance at the end of each request.
        /// </summary>
        /// <param name="middleware">The <see cref="IMiddleware"/> instance to release.</param>
        void Release(IMiddleware middleware);
    }

    /// <summary>
    /// Defines middleware that can be added to the application's request pipeline.
    /// </summary>
    public interface IMiddleware
    {
        /// <summary>
        /// Request handling method.
        /// </summary>
        /// <param name="context">The <see cref="HttpContext"/> for the current request.</param>
        /// <param name="next">The delegate representing the remaining middleware in the request pipeline.</param>
        /// <returns>A <see cref="Task"/> that represents the execution of this middleware.</returns>
        Task Invoke(HttpContext context, RequestDelegate next);
    }
}
```

The typed `UseMiddleware` extension methods would check if the registered type implements the new `IMiddleware` interface. If it does, it will automatically decide to use the `IMiddlewareFactory` to resolve the `IMiddleware` instead of using the existing middleware activation logic. This will likely be implemented by registering a `Func<RequestDelegate, RequestDelegate>` that resolves the `IMiddlewareFactory` from `HttpContext.RequestServices`.

The existing middleware activation logic will remain for convention-based middleware to preserve backwards compatibility.

**Comment by Tratcher** [comment]
Curious, what problem is this addressing? You want to get rid of the weird Invoke injection pattern? Is anybody actually using that?

How do you anticipate Release being used?

**Comment by benaadams** [comment]
Not sure on use case; but strong type it?
```csharp
    public interface IMiddlewareFactory<TMiddleware> where TMiddleware : IMiddleware
    {
        TMiddleware Create();
        void Release(TMiddleware middleware);
    }
```

**Comment by davidfowl** [comment]
> Curious, what problem is this addressing? You want to get rid of the weird Invoke injection pattern? Is anybody actually using that?

It's to give non conforming containers the ability to use a container to activate middleware.

> How do you anticipate Release being used?

To dispose stuff if the implementation doesn't use a container and the middleware is disposable.

**Comment by Tratcher** [comment]
VS making IMiddleware Disposable?

**Comment by davidfowl** [comment]
@Tratcher the caller needs to dispose the middleware. When using a container, the container is responsible for disposing.

**Comment by Tratcher** [comment]
@davidfowl That doesn't explain why the Release method is on the factory vs the IMiddleware.

**Comment by davidfowl** [comment]
@Tratcher it does. The thing that creates the object is responsible for releasing it.

**Comment by davidfowl** [comment]
The other things this breaks is passing regular objects to the Middleware constructor (say a bool or any other object).

```C#
public static IApplicationBuilder UseMyMiddleware(this IApplicationBuilder app, bool option)
{
    return app.UseMiddleware<MyMiddleware>(option);
}
```

**Comment by halter73** [comment]
@davidfowl Good point. Should we throw in the UseMiddleware extension methods if the middleware type implements the new IMiddleware interface and the params list is not empty?

**Comment by davidfowl** [comment]
@halter73 that might mean our API sucks. I'll play around with it.

**Comment by davidfowl** [comment]
If we find the limitation of not being able to pass raw arguments to the middleware too limiting then we can change the signature to the following:

```C#
/// <summary>
    /// Defines middleware that can be added to the application's request pipeline.
    /// </summary>
    public interface IMiddleware
    {
        /// <summary>
        /// Request handling method.
        /// </summary>
        /// <param name="context">The <see cref="HttpContext"/> for the current request.</param>
        /// <param name="next">The delegate representing the remaining middleware in the request pipeline.</param>
        /// <returns>A <see cref="Task"/> that represents the execution of this middleware.</returns>
        Task Invoke(HttpContext context, RequestDelegate next, object[] args);
    }
```

**Comment by Mystere** [comment]
So, to be clear, the existing conforming container implementation will continue to be supported (and probably most commonly used)?  This is only for non-conforming containers, or simply if someone wants to use a strongly typed implementation?

I guess my question is really, can you assure us that there is no intention of ever deprecating the dynamically dispatched version?

**Comment by davidfowl** [comment]
The convention based approach will not be deprecated. We're using it for all of our own middleware. The benefits of using the interface are:

- You have a strong type
- You get activation per request, so you can inject scoped services
- If you have a non conforming container, you can get middleware activation in a first class way if you replace the `IMiddlewareFactory`.
