### ISSUE TITLE
Reduce allocations by using StringSegment in parsers

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/HttpAbstractions#758]
We can potentially reduce the amount of allocations if we expose some of the parsed types and intermediate tokens as StringSegment instead of strings by removing the need to call Substring everywhere.

**Comment by Tratcher** [comment]
This could be done either as an internal optimization to the existing parsers (to limited effect) or by creating a new version that directly exposes StringSegment on the resulting object model. Thus far we have not exposed StringSegment in public APIs.

**Comment by JunTaoLuo** [comment]
@BrennanConroy also suggest looking into using spans if available and possible. Could also see if that applies to StringSegment in Common as well.

**Comment by Tratcher** [comment]
Note MVC has already done something like this. They cloned the existing parsers and reworked them in their own private library to be more efficient. We should try to reclaim those.

**Comment by JunTaoLuo** [comment]
proposal: consolidate our custom header parsing. We should look at Mvc, Localization, HeaderUtilties, and StaticFiles.

**Comment by Tratcher** [comment]
Localization just uses the TypedHeaders: https://github.com/aspnet/Localization/blob/861ae52de51f174e14701d6cdbb88e6543638b03/src/Microsoft.AspNetCore.Localization/AcceptLanguageHeaderRequestCultureProvider.cs#L33

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Mvc/blob/d19150ed227ed81f28680f1235339f77c9f0df86/src/Microsoft.AspNetCore.Mvc.Core/Formatters/MediaType.cs

**Comment by Tratcher** [comment]
https://github.com/aspnet/Common/issues/213

**Comment by Eilon** [comment]
@muratg please file a new bug for the consolidation work.

**Comment by muratg** [comment]
Consolidation work: https://github.com/aspnet/HttpAbstractions/issues/825
