### ISSUE TITLE
Use default value of null for optional services

### ISSUE THREAD

**Issue by lodejard** [aspnet/HttpAbstractions#761]
The `HttpContextFactory` has two constructors, which isn't the recommended way to implement optional services like `IHttpContextAccessor `. 

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/HttpContextFactory.cs#L16

The preferred way to implement optional dependencies is with an `IEnumerable<IHttpContextAccessor>` parameter and call `FirstOrDefault` - or to take a single parameter but give it a default value of null like `IHttpContextAccessor accessor = null`

**Comment by muratg** [comment]
cc @davidfowl

**Comment by davidfowl** [comment]
We discussed this offline and we'll leave what we have until we find problems with DI containers that don't support our ctor selection. Right now what we have seems to be the most robust.
