### ISSUE TITLE
ParsingHelper duplications

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/HttpAbstractions#762]
For example:

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/Internal/ParsingHelpers.cs#L14-L361

and 

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/Internal/HeaderSegment.cs
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/Internal/HeaderSegmentCollection.cs

There are only minor differences but we may be able to remove one and use the other. The reason we don't do it now is because both types are internal to their own assembly. There looks to be other duplications as well.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Common/issues/213
