### ISSUE TITLE
Should the `IHeaderDictionary` has a indexer with HttpRequestHeader

### ISSUE THREAD

**Issue by PMExtra** [aspnet/HttpAbstractions#770]
I think the `IHeaderDictionary` is very usually used like this case:

```
public IActionResult AMvcAction() {
    var ua = Request.Headers[HttpRequestHeader.UserAgent];
    // ...
}
```

But in fact, we can only use `var ua = Request.Header["User-Agent"];`

The typed string `"User-Agent"` is like a magic number in this code, and it could be spelled wrong.

To say the least, I can't understand that why the extend method `GetName` for `HttpRequestHeader` is be internal. I think it may could be public to prevent we use the "magic string".

**Comment by Tratcher** [comment]
See https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/HeaderNames.cs#L8

**Comment by PMExtra** [comment]
@Tratcher Thanks, It's helpful.
