### ISSUE TITLE
Parsing of HTTP headers is not case-insensitive

### ISSUE THREAD

**Issue by flaub** [aspnet/HttpAbstractions#774]
It appears that Amazon's ELB will in some cases transform header names to lower-case:
http://stackoverflow.com/questions/39871250/aws-application-load-balancer-transforms-all-headers-to-lower-case#39875978

RFC 2616 (and RFC 7230) specifies that HTTP Headers are case-insensitive:
http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive#5259004

I have an ASP.NET Core application running behind an Amazon ELB. My symptom is that the Antiforgery cookie validation fails because the lower-case `cookie` header, as supplied by ELB, is failing to be parsed into the Cookies collection on the request.

Note that I'm not using the standard ASP.NET Core servers (Kestrel, etc) since my application must run on Linux and must use Mono (due to some dependencies not being available on dotnet core yet). It's possible that the server that I'm using (https://github.com/flaub/Microsoft.AspNetCore.Server.SocketHttpListener) isn't matching the assumptions made by HttpAbstractions. 

Should HttpAbstractions always use case-insensitive string comparisons when dealing with header names? 
Should the `FeatureContext` of a server try to make header names canonical before letting HttpAbstractions parse them?

Where should the responsibility lie for dealing with headers in a case-insensitive manner?

**Comment by davidfowl** [comment]
HttpAbstractions adds as little overhead as possible to what the server does, so no canonicalization won't happen at it would add unnecessary overhead for servers that did the right thing. SocketHttpListener should be treating headers as case sensitive. File an issue or send a PR to that repository and get it fixed!

**Comment by flaub** [comment]
It's possible that my glue code is at fault.

https://github.com/flaub/Microsoft.AspNetCore.Server.SocketHttpListener/blob/master/Microsoft.AspNetCore.Server.SocketHttpListener/HeaderDictionary.cs

Or that is, I could try to make the adapter deal with lookups in a case-insensitive manner. I guess I just didn't know that HttpAbstractions made that assumption. But it makes sense. Thanks!!
