### ISSUE TITLE
SetObject<T> and GetObject Extensions to Microsoft.AspNetCore.Http.Extensions.SessionExtensions.cs

### ISSUE THREAD

**Issue by ryanelian** [aspnet/HttpAbstractions#778]
One of the good things about the ancient ASP.NET Session is the fact that you can store object without fuss.

Unfortunately, https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/SessionExtensions.cs only has `GetString`  and `GetInt32` to retrieve (and set) non-byte[] objects.

I would like to propose additional methods that allows storing random type objects into the session:

```c#
public static class SessionExtensions
{
    public static T GetObject<T>(this ISession session, string key)
    {
        var json = session.GetString(key);
        if (string.IsNullOrEmpty(json)) return default(T);

        return JsonConvert.DeserializeObject<T>(json);
    }

    public static void SetObject<T>(this ISession session, string key, T value)
    {
        var json = JsonConvert.SerializeObject(value);
        session.SetString(key, json);
    }
}
```

Also, `DistributedCacheExtensions` could use similar methods.

Serialization can be done by using JSON.NET that is included by Core MVC by default too.

**Comment by davidfowl** [comment]
We don't want to bake this into the core http abstractions primitives. This has come up before in different forms (e.g. https://github.com/aspnet/Caching/pull/94) and the advice is currently to write your own extension methods that use whatever serialization format you want (JSON may not be the most efficient).

**Comment by ryanelian** [comment]
Thank you for the fast response.

I have included the said methods to my utility library instead, in case anyone is interested: https://github.com/ryanelian/HttpUtil/blob/master/HttpUtil/SessionExtensions.cs
