### ISSUE TITLE
HttpRequestFeature.Path does not match the request if contains encoded url

### ISSUE THREAD

**Issue by UnoSD** [aspnet/HttpAbstractions#782]
I am sending a simple request with the following URL:

`http://localhost:5000/secrets/http%3A%2F%2Fwww.g`

When I look at the `Path` property of the HttpRequestFeature, it contains:

`/secrets/http:%252F%252Fwww.g`

Instead of the expected value from the original URL. It looks like it has decoded the `:` and re-encoded the `%`.

I tried to track back to the setting of the property on the creation of the request from the context, but I get a bit lost in the feature collection, I am happy to help fixing this if someone could point me in the right direction.

**Comment by Tratcher** [comment]
The un-escaping of `%3A` is happening in the server (Kestrel/WebListener).

The double escaping of `%2F` to `%252F` is happening in `PathString.ToUriComponent()`. We should make this smart enough to recognize `%XX` and avoid double escaping.

**Comment by UnoSD** [comment]
@Tratcher Thanks, I'll have a glance at the Kestrel source.

Just for my understanding, why would you want to avoid the double escaping? From the server perspective %2F is just a literal value.
