### ISSUE TITLE
new ApplicationBuilder(ApplicationBuilder builder) should copy the Properties dictionary

### ISSUE THREAD

**Issue by tuespetre** [aspnet/HttpAbstractions#783]
As I was trying to use `Map` and set a custom service provider `ApplicationServices` within the branch, I found that setting `ApplicationServices` on the branched application was also setting it on the application builder that was branched from, due to both application builders sharing the same properties dictionary. This feels counter-intuitive -- I expected that a new `IApplicationBuilder` in a new branch would have its own properties.

**Comment by muratg** [comment]
@tuespetre Interested in sending a PR?  If you do, please use https://github.com/aspnet/Common/blob/dev/shared/Microsoft.Extensions.CopyOnWriteDictionary.Sources/CopyOnWriteDictionary.cs instead of doing a clone on the constructor.
