### ISSUE TITLE
More granular tests for `TryParseQualityDouble`

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/HttpAbstractions#784]
The utility method `TryParseQualityDouble` was added in https://github.com/aspnet/HttpAbstractions/commit/7440d5d29c3814d94c83cdbbea04ee8179e03e64 and was tested transitively in `StringWithQualityHeaderValueTest.cs`. We should add more granular tests in `HeaderUtilitiesTests` that includes checking for the length output.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2710
