### ISSUE TITLE
UWP Compilation Error

### ISSUE THREAD

**Issue by YZahringer** [aspnet/HttpAbstractions#785]
When you add the Microsoft.AspNetCore.WebUtilities package to a UWP App project, it does a build error:
C:\Users\UserName\\.nuget\packages\Microsoft.AspNetCore.WebUtilities\1.1.1\lib\netstandard1.3\Microsoft.AspNetCore.WebUtilities.dll : error MSB3103: Invalid Resx file. Stream is not a valid resource file.

Steps to reproduce:
- Create a project Blank App Universal Windows
- Add the dependency "Microsoft.AspNetCore.WebUtilities": "1.1.1"
- Build project

Tried with Visual Studio 2015 and 2017, same result.

**Comment by JunTaoLuo** [comment]
This is a bug with how our cli was embedding .resx file from source dependencies and affects WebUtilities and DataProtection.Abstractions. We need to fix this in the next FTS patch. Note that this refactoring was only done in FTS so LTS packages (1.0.x) will work.

There's no real workarounds for this. There is only one string in the .resx file so the easy fix is to just move it out into the .cs file which is what we did in 2.0 anyway. The fix will be in the Common repo.

**Comment by JunTaoLuo** [comment]
Issue has been proposed for a patch in https://github.com/aspnet/Common/issues/203.
