### ISSUE TITLE
Consider looking for InvokeAsync too when configuring middleware through UseMiddleware

### ISSUE THREAD

**Issue by javiercn** [aspnet/HttpAbstractions#786]
UseMiddleware<TMiddleware>() will fail if your middleware has InvokeAsync instead of Invoke (which is a very common pattern) (VS will add Async suffix when you ctrl+. and a lot of people follow that convention)

We probably want to also change IMiddleware to support this in some way.
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/IMiddleware.cs#L23

**Comment by muratg** [comment]
We'll try to do this.  If there's both Invoke and InvokeAsync, we'll throw.
