### ISSUE TITLE
HttpRequest.Params implementation?

### ISSUE THREAD

**Issue by BrandonPotter** [aspnet/HttpAbstractions#792]
Is there any design reason `HttpRequest` does not have a `Params` collection implemented? If not, would a PR be considered?

From older version - https://msdn.microsoft.com/en-us/library/system.web.httprequest.params(v=vs.110).aspx

**Comment by khellang** [comment]
I could think of a couple of reasons...

1. To get the params collection, you have to read the request body and parse both the form and query string. This is a performance killer.
2. People generally like to know where values come from, not just "somewhere in the query string, a form, a cookie, or a combination".
3. Server variables don't exist anymore.

Based on this, I don't think it provides a ton of value and that a lot of people would use it... Oh, and

4. If you _really_ want it, it's straight-forward to write yourself:

```csharp
public static class HttpRequestExtensions
{
    public static NameValueCollection GetParams(this HttpRequest request)
    {
        var @params = new NameValueCollection();

        foreach (var query in request.Query)
        {
            foreach (var value in query.Value)
            {
                @params.Add(query.Key, value);
            }
        }

        if (request.HasFormContentType)
        {
            foreach (var form in request.Form)
            {
                foreach (var value in form.Value)
                {
                    @params.Add(form.Key, value);
                }
            }
        }

        foreach (var cookie in request.Cookies)
        {
            @params.Add(cookie.Key, cookie.Value);
        }

        return @params;
    }
}
```

Note: while the code is super simple, it does a ton of work (reading and parsing) behind the scenes, so use it with care. You could also make an async version that reads the form asynchronously instead.

**Comment by davidfowl** [comment]
@BrandonPotter Why would you ever need Request.Params? It was likely there originally in ASP.NET because of ASP classic compatibility.

> You could also make an async version that reads the form asynchronously instead.

You really should. Request.Form is implemented pretty poorly and should generally be avoided.

> Is there any design reason HttpRequest does not have a Params collection implemented? If not, would a PR be considered?

Nope. For all the reasons @khellang mentioned.

**Comment by BrandonPotter** [comment]
In our use case we have a lot of code that takes the opposite philosophy, that we don't really care if the values are in query string or form (therefore using `Request.Params` was super convenient). It might be easier for clients to hit us with a querystring param from an IoT device and so on.

Current migration workaround is this:

```
       private IQueryCollection RequestParams
        {
            get
            {
                Dictionary<string, StringValues> dict = new Dictionary<string, StringValues>();

                Request.Query.Select(rq => dict[rq.Key] = rq.Value);
                if (Request.HasFormContentType)
                {
                    Request.Form.Select(fv => dict[fv.Key] = fv.Value);
                }

                return new QueryCollection(dict);
            }
        }
```

In any case, thanks for discussion.
