### ISSUE TITLE
Add `StatusDescription` to `HttpResponse` class

### ISSUE THREAD

**Issue by RexLKW** [aspnet/HttpAbstractions#794]
In the old days, it is easy to modify the Http response status code and description, but now on asp.net core, we need to do something like:

`HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase = "It is my description";`

Consider adding `StatusDescription` back into `HttpResponse` class and its impl classes.

**Comment by davidfowl** [comment]
It was left as a second class citizen because it's not a commonly used property.

/cc @Tratcher

**Comment by cesarbs** [comment]
@RexLKW Could you elaborate on why you want this feature? Are you returning non-standard status codes? If not, why do you want to replace the standard reason phrases?

**Comment by JunTaoLuo** [comment]
On a semi-related note, HTTP/2 will not have reason phrases.

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/HttpAbstractions/issues/395
