### ISSUE TITLE
Consider making verbs in `HttpMethods` as `const string` rather than `static readonly string`

### ISSUE THREAD

**Issue by kchanlee** [aspnet/HttpAbstractions#795]
When I am trying to use `AcceptVerbsAttribute`, I don't want to write verbs literally (e.g. `[AcceptVerbs("GET", "POST")]`) so I try to reuse the verbs defined in `HttpMethods` (e.g. `[AcceptVerbs(HttpMethods.Get, HttpMethods.Post)]`). But this is not acceptable by compiler.

How about making verbs in `HttpMethods` as `const string` rather than `static readonly string` so that they can be more widely used?

**Comment by khellang** [comment]
This has been discussed before; https://github.com/aspnet/HttpAbstractions/pull/712#issuecomment-250192311

**Comment by kchanlee** [comment]
@khellang Thanks for pointing it out. Let me close this issue.
