### ISSUE TITLE
ITlsConnectionFeature should include client certificate chain elements

### ISSUE THREAD

**Issue by alextolp** [aspnet/HttpAbstractions#808]
It should be possible to access the client certificate and any chain elements that were presented by the client when the TLS connection was established. Currently the feature only exposes the client certificate, without any intermediate certificates, making it very difficult to work with the chain elements in the mvc layer.

**Comment by Tratcher** [comment]
Is that information available from SslStream or Http.Sys (our current two implementations of this feature)?

**Comment by alextolp** [comment]
It's currently only available through SslStream, but not Http.Sys

**Comment by muratg** [comment]
@blowdart Thoughts?

**Comment by blowdart** [comment]
It'd be good for internal CAs. So yes, v.next

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2708
