### ISSUE TITLE
Consider reverting IFeatureCollection.Get<T>/Set<T> back to extension methods

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#811]
Turns out generic virtual dispatch is the worst of them all and this shows up on profiles now. IIRC we were able to achieve most of the inlining goals as part of the PR that changes `FeatureReferences`.

https://github.com/aspnet/HttpAbstractions/blob/0da88e0dda36d48ae68ac24289c349605cd94828/src/Microsoft.AspNetCore.Http.Features/FeatureReferences.cs#L75

We need to compare the perf hit there with the not calling a generic virtual method. i.e use `IFeatureCollection[typeof(SomeType)]`.

/cc @benaadams

**Comment by davidfowl** [comment]
Some results from Kestrel:

```
                 Method |       Mean |    StdDev |         Op/s | Scaled | Allocated |
----------------------- |----------- |---------- |------------- |------- |---------- |
 GetFirstViaFastFeature |  5.7434 ns | 0.0642 ns | 174113914.78 |   1.00 |       0 B |
        GetFirstViaType |  7.2421 ns | 0.0549 ns | 138081472.44 |   1.26 |       0 B |
   GetFirstViaExtension |  8.8473 ns | 0.2046 ns | 113028985.80 |   1.54 |       0 B |
     GetFirstViaGeneric | 12.7234 ns | 0.1493 ns |  78595386.17 |   2.22 |       0 B |
  GetLastViaFastFeature | 12.7502 ns | 0.1002 ns |  78430044.58 |   2.22 |       0 B |
         GetLastViaType | 14.3296 ns | 0.4810 ns |  69785859.00 |   2.50 |       0 B |
    GetLastViaExtension | 15.5168 ns | 0.1387 ns |  64446150.84 |   2.70 |       0 B |
      GetLastViaGeneric | 18.9250 ns | 0.2723 ns |  52840253.99 |   3.30 |       0 B |
```

**Comment by benaadams** [comment]
Need a fast way to do a instanced typed dictionary; in the way you can do at a static level http://stackoverflow.com/questions/14063940/creating-a-non-static-version-of-compiler-based-dictionary-where-keys-are-type

**Comment by muratg** [comment]
@davidfowl do we want to do this in 2.0.0?

cc @Tratcher

**Comment by benaadams** [comment]
Anyway to improve this in coreclr? Or unlikely?
