### ISSUE TITLE
Forward slash '/' character in multipart/form-data boundary breaks header parsing

### ISSUE THREAD

**Issue by drayfar** [aspnet/HttpAbstractions#820]
Hey Team,

We have a project that uploads data from a mobile device to our ASP.NET Core 2.0, MVC 1.1.1 server. We noticed requests seemingly randomly failing, and have narrowed it down to requests that have a forward slash '/' character in the multipart form data boundary. This character is legal in a boundary according to [RFC2046](https://tools.ietf.org/html/rfc2046#page-22). I have been able to repro the issue by changing a unit test in [this PR](https://github.com/drayfar/HttpAbstractions/pull/1). It appears that a token is incorrectly considered invalid in [HttpRuleParser.cs#69](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/HttpRuleParser.cs#L69). I am not familiar with this codebase, so I am not comfortable making this change myself without some direction. Could you please take a look and advise?

Thanks!
Danny Farmer
@drayfar
Software Engineer 2
Bing Experiences
Microsoft

**Comment by Tratcher** [comment]
While some chars are allowed in the boundary value, they may not be allowed as is in the header. See the note about quotes here : https://tools.ietf.org/html/rfc2046#section-5.1.1. Can you capture a full request in a fiddler trace for context?

**Comment by drayfar** [comment]
[Here is a contrived example](https://github.com/drayfar/HttpAbstractions/blob/dev/boundary.saz) I used in testing. I'll work with our client team to get a real one.

**Comment by drayfar** [comment]
I have verified that this same request works on our older traditional ASP.NET server.

**Comment by muratg** [comment]
@mikaelm12 could you attempt a repro?

**Comment by jkotalik** [comment]
@muratg Feel free to pass this to me, I can look into the repro

**Comment by jkotalik** [comment]
According to @Tratcher comment (https://tools.ietf.org/html/rfc2046#section-5.1.1), it is required to have quotes around the boundary header if there is a '/' in it (or characters like ':', '"', etc. I just tried adding the 
'/' character to the header and it passed all tests. Hopefully adding in quotes around the string will fix your issue.

I'm going to add/modify a few tests for regression.

**Comment by jkotalik** [comment]
https://github.com/aspnet/HttpAbstractions/pull/914
