### ISSUE TITLE
Fix the broken scheme-less GetTokenAsync overload

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/HttpAbstractions#823]
The `GetTokenAsync()` overload that doesn't require a `scheme` is convenient... but broken, as it tries to call the other overload with a `null` scheme, which results in an `ArgumentNullException` being thrown at runtime:

![image](https://cloud.githubusercontent.com/assets/6998306/25343341/0e91db9a-290f-11e7-827a-4c5e25866024.png)

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Authentication.Abstractions/TokenExtensions.cs#L135

/cc @HaoK @Tratcher

**Comment by HaoK** [comment]
Yeah, I should add a test for this one :)

**Comment by HaoK** [comment]
3085f016e47bb3e0c90491e2c155a95b151fabda

**Comment by PinpointTownes** [comment]
Thanks! :+1:
