### ISSUE TITLE
Consolidate all header parsing code 

### ISSUE THREAD

**Issue by muratg** [aspnet/HttpAbstractions#825]
Header parsing logic is used in

- MVC
- StaticFiles
- ResponseCaching

We should investigate the usages across the board and consolidate the code here.

**Comment by muratg** [comment]
https://github.com/aspnet/HttpAbstractions/issues/825

**Comment by muratg** [comment]
Tracking issues:

- [ ] HttpAbstractions #758 
- [ ] ...

**Comment by Tratcher** [comment]
@Eilon #758 is complete, next we need to investigate having MVC replace their implementation with this one.

**Comment by muratg** [comment]
@Eilon Moving the rest of the work to preview3.

**Comment by muratg** [comment]
@Eilon could we do this in 2.1?

**Comment by Eilon** [comment]
Yessss... @jkotalik is actually already working on some of this, starting with the toughest of them all: MediaType header value.

**Comment by jkotalik** [comment]
@muratg @Eilon We added structured suffixes and facets to MediaTypeHeaderValue (MTHV) in HttpAbstractions. I was trying to modify MediaType in MVC to wrap MTHV, though it seemed non trivial and wouldn't have much benefit until we either remove MediaType or can deprecate it. What other header logic can be moved from StaticFiles/ResponseCaching to HttpAbstractions?

**Comment by muratg** [comment]
I think we can deprecate MediaType. @Eilon thoughts?

**Comment by rynowak** [comment]
@javiercn did some research on obsoleting `MediaType` and I think his findings were promising. @javiercn do you remember what the conclusions were?

**Comment by rynowak** [comment]
@javiercn just came by to express to me just how excited he is to share his wealth of knowledge and extensive notes in this area; alas, he had to go to an important meeting first.

**Comment by Eilon** [comment]
I would only obsolete `MediaType` if we actually plan to get rid of it, say, in MVC 3.0. Would that be the plan?

**Comment by javiercn** [comment]
We should have a design we are all happy with for 3.0 (one that allows efficient header non allocating iteration as a basic API and a richer strongly typed allocating API for convenience)

**Comment by Eilon** [comment]
I set up a mtg for this for tomorrow. I invited @javiercn @muratg @jkotalik @rynowak @Tratcher .

**Comment by Eilon** [comment]
Plan from the mtg:

* [ ] Change MediaType into a facade that just calls into MediaTypeHeaderValue
* [ ] Mark MediaType as obsolete
* [ ] Find all public exposure of MediaType in MVC, obsolete them, and make sure that there are non-obsolete alternatives
* [ ] Do basic before/after perf tests on MVC scenarios for conneg to assess whether there is a regression, and, if so, how much

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2705
