### ISSUE TITLE
Consider exposing IHttpConnectionFeature.ConnectionId through ConnectionInfo

### ISSUE THREAD

**Issue by khellang** [aspnet/HttpAbstractions#827]
What it says on the tin. Is there a reason this isn't exposed through the `HttpContext` surface?

**Comment by davidfowl** [comment]
It's not very common to care about the underlying connection id when logging. It's especially less relevant with http2 since it's the same connection for all requests. Why does it need to be first class?

**Comment by khellang** [comment]
> It's not very common to care about the underlying connection id when logging.

I use it all the time when working with WebSockets.

> Why does it need to be first class?

It doesn't *need* to be first class, but it would be convenient.
