### ISSUE TITLE
Add a WriteTextAsync extension method for writing plain text to the response

### ISSUE THREAD

**Issue by danroth27** [aspnet/HttpAbstractions#846]
To correctly write text to the response you really need to set the content type header, like this:

```c#
app.Run(context =>
{
    context.Response.Headers.Add("Content-Type", "text/plain");
    return context.Response.WriteAsync("Hello world!");
});
```

If you don't set the content type header then browsers have to guess what the response type is. Chrome guesses plain text, but Edge guesses HTML.

Could we add a `WriteTextAsync` extension method that makes writing plain text to the response a one-liner?

**Comment by davidfowl** [comment]
Do you want it to set the content length too? Is it really that hard to set the content type? There's a first class property for it so you don't need to write it like you have the in issue:

```C#
app.Run(context =>
{
    context.Response.ContentType = "text/plain";
    return context.Response.WriteAsync("Hello world!");
});
```

I don't think we should add it.

**Comment by danroth27** [comment]
@davidfowl It's not "hard", but currently all of the hello world samples we have write to the response with one line, because the whole point of these samples is to show how simple it is to get started with ASP.NET Core. Unfortunately none of these samples render correctly in Edge. 

You wouldn't set the content length because you might choose to write some more.

**Comment by davidfowl** [comment]
I'm still anti this, one down vote from me 😄

**Comment by muratg** [comment]
@danroth27 Closing this as "won't fix".
