### ISSUE TITLE
PathString should have a registered TypeConverter

### ISSUE THREAD

**Issue by MarkPflug** [aspnet/HttpAbstractions#848]
I ran into an issue while attempting to configure the OpenIdConnect provider using the Options/configuration APIs. The issue was around trying to assign a the OpenIdConnect.CallbackPath value which is of type PathString. This failed, with a conversion error trying to convert my string value from the configuration to the PathString property.
The original issue is here: https://github.com/aspnet/Security/issues/1230

This can resolved by reigistering a TypeConverter for PathString. However, it seems like such a TypeConverter would be best defined along side the PathString class itself.

**Comment by HaoK** [comment]
Added for preview 2, but I need to harden the implementation + add a few more tests, so keeping this on my plate for now

**Comment by HaoK** [comment]
12f89f66a687bdb1c1b683b0d7abd2732c05eb1a
