### ISSUE TITLE
preview1-final depends on netcoreapp2.0 rather than netcorestandard2.0

### ISSUE THREAD

**Issue by Mystere** [aspnet/HttpAbstractions#854]
Previous versions of HttpAbstractions had a netcorestandard dependency, while 2.0.0 has a netcoreapp dependency.  This prevents using HttpAbstractions in net standard library.

Is this intentional?

Previous version:
https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/1.1.2

Current version:
https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/2.0.0-preview1-final

This seems like it's because it depends on Http.Features, which also has a netcoreapp2.0 dependency.

**Comment by Tratcher** [comment]
Yes it was, but it has been changed to netstandard2.0 for preview2.

**Comment by Mystere** [comment]
Ahh.. yes, I should have looked in the repo first.  My bad.

**Comment by steamrolla** [comment]
When can we expect preview2?
