### ISSUE TITLE
Add IHttpRequestFeature.HasStartedReadingBody

### ISSUE THREAD

**Issue by halter73** [aspnet/HttpAbstractions#859]
This would be vaguely similar to `IHttpResponseFeature.HasStarted`, but for the request side.

`IHttpRequestFeature.HasStartedReadingBody` would remain false until the first call to `Request.Body.ReadAsync` or similar. It would then switch to true immediately upon that first call even if the client hasn't actually sent any part of the body yet.

@davidfowl suggested alternatively calling this `HasRequestBodyStarted` and clearly documenting that the request body isn't started until it's read from.

**Comment by halter73** [comment]
Context: https://github.com/aspnet/KestrelHttpServer/pull/1877#discussion_r120427236

**Comment by khellang** [comment]
It's already on the request feature interface, so I don't think It's necessary to include 'request' in the property name? :thinking:

**Comment by Tratcher** [comment]
Does this have applications beyond IHttpMaxRequestBodySizeFeature? I haven't seen a need for this elsewhere.

**Comment by halter73** [comment]
@Tratcher Maybe not. I haven't thought about it too much, but it could conceivably be used by buffering middleware to protect it from buffering a partial body.

**Comment by Tratcher** [comment]
I haven't seen any usage models where a middleware would encounter a partially read body. It's all or nothing. And if it has been read then it was either buffered and is now seekable, or you're at the end and it just returns 0.

**Comment by muratg** [comment]
@davidfowl @halter73 What would be the use case for this?

**Comment by halter73** [comment]
This could have been useful if [IHttpMaxRequestBodySizeFeature.IsReadOnly](https://github.com/aspnet/HttpAbstractions/blob/62fdf64cf658f9d5c7403e1218f8ca33231dec0c/src/Microsoft.AspNetCore.Http.Features/IHttpMaxRequestBodySizeFeature.cs#L16) didn't exist. Now that it does, I'm fine with closing the issue. We can reopen if someone comes back with a real use case.

**Comment by muratg** [comment]
Thanks @halter73!
