### ISSUE TITLE
Add IHttpUpgradeFeature.WasUpgraded

### ISSUE THREAD

**Issue by halter73** [aspnet/HttpAbstractions#860]
This should make it easier to know if it's safe to call certain APIs like UpgradeAsync().

**Comment by halter73** [comment]
Context: https://github.com/aspnet/KestrelHttpServer/pull/1877#discussion_r120427236

**Comment by davidfowl** [comment]
@muratg @halter73 this needs to be done in 2.0

**Comment by muratg** [comment]
@cc @Tratcher

**Comment by Tratcher** [comment]
This is interesting but not critical. I haven't seen any customers/scenarios that have trouble keeping track of this information. It's usually implicit in that you immediately transition to treating the request as a WebSocket.
https://github.com/aspnet/WebSockets/blob/98c8899155790911a7f2fff1e7891203fb96cf51/samples/EchoApp/Startup.cs#L40-L41

**Comment by davidfowl** [comment]
API changes should happen as part of the 2.0 wave or we should close this.

**Comment by muratg** [comment]
@DamianEdwards do you want this or prefer to close?

**Comment by halter73** [comment]
@murat This could be closed on the same grounds as https://github.com/aspnet/HttpAbstractions/issues/859.

**Comment by muratg** [comment]
Closing this one as well. @davidfowl, let's chat later if you disagree.
