### ISSUE TITLE
Deprecate IHttpAuthenticationFeature.IAuthenticationHandler

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#861]
We deprecated the property on HttpContext but not on the feature interface

https://github.com/aspnet/HttpAbstractions/blob/c06ed8c29abe606ad7a36915d85d066e59699f27/src/Microsoft.AspNetCore.Http.Features/Authentication/IHttpAuthenticationFeature.cs#L12

/cc @Tratcher @HaoK

**Comment by Tratcher** [comment]
We're still using .User

**Comment by Tratcher** [comment]
Oh, I see. Nobody uses the feature interfaces directly

**Comment by davidfowl** [comment]
So we should just outright delete the property then.

**Comment by Tratcher** [comment]
There was some theory about not killing 1.1 middleware, but I don't know how realistic that is.
