### ISSUE TITLE
Base64Url encoding duplicated with Common repository

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/HttpAbstractions#862]
https://github.com/aspnet/Common/blob/dev/shared/Microsoft.Extensions.WebEncoders.Sources/WebEncoders.cs
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/Base64UrlTextEncoder.cs

Related [aspnet/Common/#237](/aspnet/Common/issues/237)

**Comment by Tratcher** [comment]
@kichalla

**Comment by kichalla** [comment]
Hmm, I didn't know that we had this already in Common repo. I originally looked at Security repo and thought that it was the only place https://github.com/aspnet/Security/commit/e55e3b6f5a9f14e2971769d3a619eaec878c2e89

**Comment by kichalla** [comment]
https://github.com/aspnet/HttpAbstractions/commit/ce68ec23c05739af52f2e59649dd94b66bc30f13
https://github.com/aspnet/Security/commit/bf685de16be9949d67e93cc058ef4393f005756b
https://github.com/aspnet/Mvc/commit/cfc05104e416f253bdfc07603f3e387c77aea975
