### ISSUE TITLE
[Question] - Examining middleware pipeline

### ISSUE THREAD

**Issue by dazinator** [aspnet/HttpAbstractions#867]
I am working with a modular CMS, where modules can add `middleware` to the pipeline. The middleware pipeline is also forked on a per tenant basis, so as you can imagine this can get quite confusing.

I am experiencing some odd errors, and I think it might be to to with the middleware in the pipeline and its order of execution.

Is there a way that I can get access to the middleware pipeline at runtime so I can log the details and order of the middleware components?

Is there some logging I can enable so that I can trace a request through the pipeline to see which middlewares were involved in processing it?

**Comment by Tratcher** [comment]
Check out this component: https://github.com/aspnet/Diagnostics/blob/dev/samples/MiddlewareAnalysisSample/Startup.cs

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2700
