### ISSUE TITLE
why HttpMethods are not constants?

### ISSUE THREAD

**Issue by Bartmax** [aspnet/HttpAbstractions#868]
I was trying to use `HttpMethods` as parameters for an `Attribute` and found out those are not constants but readonly. why aren't const?

```c#
public static readonly string Connect = "CONNECT";
public static readonly string Delete = "DELETE";
public static readonly string Get = "GET";
public static readonly string Head = "HEAD";
public static readonly string Options = "OPTIONS";
public static readonly string Patch = "PATCH";
public static readonly string Post = "POST";
public static readonly string Put = "PUT";
public static readonly string Trace = "TRACE";
```

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/HttpMethods.cs#L10-L18

**Comment by PinpointTownes** [comment]
Because @davidfowl said no, for obscure reasons: https://github.com/aspnet/HttpAbstractions/pull/712 :trollface:

**Comment by Bartmax** [comment]
oh ok. well, if it was intentional I can live with it. not able to use them as attribute params was a bummer tho.
