### ISSUE TITLE
Default behavior for ChallengeAsync and ForbidAsync

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#874]
Instead of throwing, ChallengeAsync should set a 401 and ForbidAsync should set a 403 as the status code on the HttpResponse object. Today it throws for discoverability but that was also because we had a concept for active and passive middleware and we wanted people to know if there was no active configured. I think the default behavior should just use the default http status codes for the verbs these methods represent.

/cc @HaoK @Tratcher @blowdart

**Comment by HaoK** [comment]
So just to be clear, this is only for the no scheme specified scenario, so Challenge/Forbid() can have special default behavior in the IAuthenticationService which will do 401/403.  If they specify a scheme that doesn't exist, that should always throw...

**Comment by Tratcher** [comment]
Disagree. People fail to register or properly configure their auth components all the time. Just returning a 401 does not tell them what they did wrong and does not make it work.

**Comment by HaoK** [comment]
Well this would let you use Challenge/Forbid with no schemes no?

**Comment by HaoK** [comment]
My take is that's what this behavior is targeting...

**Comment by davidfowl** [comment]
@HaoK Even better would be, if you challenge with an up-mapped scheme, we should put that in the `WWW-Authenticate` header on the response and return a 401.

**Comment by HaoK** [comment]
@davidfowl Eh, that extra behavior probably deserves a flag like `AuthenticationOptions.AllowUnknownChallenges` or similar

**Comment by davidfowl** [comment]
Sure `AuthenticationOptions.AllowUnknownChallenges` might be reasonable, and then we can discuss what the default behavior should be (I think it should be true). See https://github.com/aspnet/HttpAbstractions/pull/875. 

What I'm trying to do here is treat this system less like something special but have the default implementation do the right "http thing".
