### ISSUE TITLE
Returning a null AuthenticateResult causes a NullReferenceException in AuthenticationService.AuthenticateAsync()

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/HttpAbstractions#886]
Discovered when porting the aspnet-contrib validation/introspection middleware to the new stack.

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationService.cs#L69

/cc @HaoK @Tratcher

**Comment by Tratcher** [comment]
There's no defined semantic for a null result though, right? Isn't that what AuthenticationResult.NoResult() is for?

**Comment by PinpointTownes** [comment]
Right. FWIW, I reported a similar bug in `AuthenticationHandler` for 1.x a while ago: https://github.com/aspnet/Security/issues/760. You might want to adopt the same fix.

Alternatively, making `AuthenticateResult` a struct would prevent returning `null` and save an allocation everywhere we use it :sweat_smile:

**Comment by HaoK** [comment]
I think our results are slightly too big to be a good value type/struct, with the 4 fields: Exception (8 bytes) + Ticket (8 bytes) + 2 bools (2 bytes) = 18 bytes.  

We can just fix it

**Comment by Tratcher** [comment]
What does size have to do with it? The most significant qualification I see is that it needs to be immutable, which it is.

**Comment by HaoK** [comment]
It will be copied instead of passed by reference everywhere https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct

**Comment by PinpointTownes** [comment]
@HaoK I totally agree that we have to be careful when opting for structs but AFAICT, there are only 3 backing fields in `AuthenticateResult` (corresponding to the `Failure`, `Ticket` and `None` properties).

The last one is basically useless, as the property could be replaced by something like

```csharp
public bool None => Ticket == null && Failure == null;
```

So we'd only have `Failure` + `Ticket` (8 x 2 = 16 bytes on x64 platforms).

**Comment by PinpointTownes** [comment]
Actually, the only problematic thing is that `HandleRequestResult` currently inherits from `AuthenticateResult`, which wouldn't be possible with a struct.
