### ISSUE TITLE
HttpResponseStreamWriter nulls out fields in Dispose

### ISSUE THREAD

**Issue by jkotalik** [aspnet/HttpAbstractions#900]
Relating to #540  it seems that we null fields out for _stream, _bytePool, and _charPool. Though we do call FlushInternal to clear out the buffer, we shouldn't null out those fields and use a Boolean flag instead like in #898 .

**Comment by Tratcher** [comment]
You can add this to your existing PR.

**Comment by jkotalik** [comment]
#898
