### ISSUE TITLE
Characters out of BMP are encoded

### ISSUE THREAD

**Issue by miloush** [aspnet/HttpAbstractions#902]
Using

```C#
services.Configure<WebEncoderOptions>(options =>
     options.TextEncoderSettings = new TextEncoderSettings(UnicodeRanges.All));
```

does not help, 𐌰 is still output as `&#x10330;` in 2.0.0-preview2-final

**Comment by muratg** [comment]
@miloush Where is the content coming from?  Is it a Razor view? 

@rynowak Is this something you've seen before?

**Comment by miloush** [comment]
@muratg Yes, coming from Razor view.

**Comment by muratg** [comment]
@Eilon Have you seen this problem before?

**Comment by Eilon** [comment]
I don't think so. @GrabYourPitchforks - any idea on this?

**Comment by GrabYourPitchforks** [comment]
This has been the behavior since v1 and is by design (for now). The reason is that there simply hasn't been enough demand for the "allow adding non-BMP characters to the whitelist" feature to justify its development cost.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2697
