### ISSUE TITLE
Move various parsers/formatters into HttpAbstractions

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#916]
In our continued effort to provide generally useful abstractions for the greater ecosystem, we should move the low level parsers and formatters into Microsoft.AspNetCore.WebUtilities.

HTTP Parser from Kestrel - https://github.com/aspnet/KestrelHttpServer/blob/59b77bb357f50946ecea310feb8db53473e0e165/src/Kestrel.Core/Internal/Http/HttpParser.cs

The chunked encoding parser from Kestrel - https://github.com/aspnet/KestrelHttpServer/blob/59b77bb357f50946ecea310feb8db53473e0e165/src/Kestrel.Core/Internal/Http/MessageBody.cs#L475

HPackEncoder and HpackDecoder - https://github.com/aspnet/KestrelHttpServer/blob/59b77bb357f50946ecea310feb8db53473e0e165/src/Kestrel.Core/Internal/Http2/HPack/HPackDecoder.cs
https://github.com/aspnet/KestrelHttpServer/blob/59b77bb357f50946ecea310feb8db53473e0e165/src/Kestrel.Core/Internal/Http2/HPack/HPackEncoder.cs

**Comment by muratg** [comment]
@davidfowl putting this into the next milestone.

Was Managed HttpClient a potential user of this in your mind?  Any other users?

**Comment by litichevskiydv** [comment]
Will it be possible to use output and input formatters such as JSON output formatters in the middlewares?

**Comment by khellang** [comment]
It might be soon; https://github.com/aspnet/Mvc/pull/6822#issuecomment-329484272, https://github.com/aspnet/Diagnostics/issues/346 and https://github.com/aspnet/Mvc/pull/6998

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2324
