### ISSUE TITLE
ForbidAsync uses challenge schemes instead of forbid schemes

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#917]
While looking through the code I noticed that nothing uses the configured forbid schemes by default (GetDefaultForbidSchemeAsync).

https://github.com/aspnet/HttpAbstractions/blob/d894584254ccc5a2eb5671530b2ec9880fb097c0/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationService.cs#L112-L122

Seems like ForbidAsync *should* use the specificed ForbidScheme (if any). 

/cc @HaoK

**Comment by jkotalik** [comment]
See https://github.com/aspnet/Security/issues/1376

**Comment by jkotalik** [comment]
@Eilon @muratg This is probably a 2.0.1 candidate.

**Comment by Eilon** [comment]
Do we feel this is a common case? How bad is the workaround?

**Comment by davidfowl** [comment]
@Eilon yes it's very common. The work around isn't that bad but it's non obvious. The application crashes (Stackoverflow) as a result of the recommended configuration.

**Comment by davidfowl** [comment]
@Eilon this alone doesn't actually fix the issue though. This issue https://github.com/aspnet/Security/issues/1376 requires that this be fixed https://github.com/aspnet/Security/issues/1378 as well.

**Comment by Eilon** [comment]
Got it, this does sound patch-worthy.

**Comment by Eilon** [comment]
@jkotalik it looks like you fixed this for 2.1.0 (dev) already. If that's correct, please mark as done and close. Thanks!
