### ISSUE TITLE
IHeaderDictionary.GetCommaSeparatedValues returns IList<string> instead of a read-only collection

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/HttpAbstractions#92]
`IHeaderDictionary.GetCommaSeparatedValues` returns `IList<string>` instead of `IEnumberable<string>`, `IReadableStringCollection` or any other read-only collection. Is there any particular reason for this?

**Comment by Tratcher** [comment]
The result is a copy, not a view into the original collection, so you are free to manipulate it.

**Comment by muratg** [comment]
Like @Tratcher mentions, you might want to manipulate the copy (which is a lightly parsed version). So closing.
