### ISSUE TITLE
MediaTypeHeaderValue accepts a list of strings instead of a list of StringSegments

### ISSUE THREAD

**Issue by jkotalik** [aspnet/HttpAbstractions#920]
With our efforts to remove usages of strings in favor of string segments, it seems incomplete that [MediaTypeHeaderValue.ParseList](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/MediaTypeHeaderValue.cs#L377-L395) only accepts a list of strings rather than a list of StringSegment. We should consider adding an overload to accept a list of StringSegment too.

**Comment by jkotalik** [comment]
Relates to the ongoing effort of #718 and merging MediaType with MediaTypeHeaderValue.

**Comment by Tratcher** [comment]
Do you have a usage? This was left for compatibility with headers as StringValues which is a list of strings.

**Comment by jkotalik** [comment]
The only list method which is actually used in HttpAbstractions is TryParseList (in HeaderDictionaryTypeExtensions). I understand why this is method is here, however it seems backwards to have TryParse accept a StringSegment and TryParseList accept a List<string>.

**Comment by Tratcher** [comment]
StringValues has implicit converters to and from `string` and `string[]`, but not `StringSegment` or `StringSegment[]`. As parse is performance sensitive we didn't want to add implicit converters that would hide SubString calls.

**Comment by jkotalik** [comment]
Should we consider adding an implicit converter between StringSegment and StringValue? And it wouldn't be much work to add overloads for StringSegment if we would like to. Though we not have a usage scenario, the method is public.

**Comment by Tratcher** [comment]
We don't want the implicit converter from StringSegment to StringValue, it may be required to call SubString.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2695
