### ISSUE TITLE
HttpRuleParser GetExpressionLength allows invalid characters.

### ISSUE THREAD

**Issue by jkotalik** [aspnet/HttpAbstractions#923]
@Tratcher and I discovered that [GetExpressionLength in HttpRuleParser](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/HttpRuleParser.cs#L257) allows invalid characters (including control characters in expressions. GetExpressionLength mentions [that we don't really care about the content of a quoted string](https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.Net.Http.Headers/HttpRuleParser.cs#L250-L251), however it seems appropriate that if a quoted string has an invalid character, it should throw on parsing here, not in Kestrel (or whatever server). 

This would be a breaking change, as it would introduce a new place where an exception is thrown, however it is probably the right behavior.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2694
