### ISSUE TITLE
FeatureCache is over-checked and over-reset

### ISSUE THREAD

**Issue by benaadams** [aspnet/HttpAbstractions#924]
A simple plantext middleware as below, will check the `Frame` `IFeatureCollection` 7 times and initialize/reset the Context, Resquest and Responses feature caches twice each.
```csharp
public static Task WriteResponse(HttpResponse response)
{
    var payloadLength = _helloWorldPayload.Length;
    response.StatusCode = 200;
    response.ContentType = "text/plain";
    response.ContentLength = payloadLength;
    return response.Body.WriteAsync(_helloWorldPayload, 0, payloadLength);
}
```

![](https://aoa.blob.core.windows.net/aspnet/feature-cache.png)

The extra reset and checks are from initalization; then reinitialization after `RequestServicesFeature` is added to the collection by the host, increasing the `IFeatureCollection`'s version count.

**Comment by muratg** [comment]
@davidfowl thoughts?  (PR is assigned to you too.)

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2693
