### ISSUE TITLE
FormOptions not work

### ISSUE THREAD

**Issue by Eilon** [aspnet/HttpAbstractions#930]
_From @sy-ing on August 29, 2017 11:25_

In  .net core 2.0 
I want to upload a file that size maybe 1G or more 

I  modify the  FormOptions  like

```c#
   services.Configure<FormOptions>(x =>
            {
                x.ValueLengthLimit = int.MaxValue;
                x.MultipartBodyLengthLimit = int.MaxValue;
                x.MultipartHeadersLengthLimit = int.MaxValue;
            });
```

But it is invalid

I still can't upload files over 10M in size

_Copied from original issue: dotnet/core#908_

**Comment by Eilon** [comment]
_From @Petermarcu on August 30, 2017 16:35_

@Eilon

**Comment by Eilon** [comment]
Moved to correct repo. BTW there's some info here on request limits: https://github.com/aspnet/Announcements/issues/267

**Comment by Tratcher** [comment]
Are you sure it's not https://github.com/aspnet/Announcements/issues/267?

**Comment by muratg** [comment]
@sy-ing 

Were you able to resolve your issue with the information on the announcement Eilon shared?

**Comment by sy-ing** [comment]
I repair the issue by modify the cofig of the nginx and remove the tag of async
