### ISSUE TITLE
RFC 8187 - Character Encoding for Headers

### ISSUE THREAD

**Issue by benaadams** [aspnet/HttpAbstractions#940]
From https://github.com/aspnet/KestrelHttpServer/issues/2063

Hot off the presses (September 2017) https://tools.ietf.org/html/rfc8187

Indicating Character Encoding and Language for HTTP Header Field Parameters

> @Tratcher  Hmm, interesting choices. It only applies to key value pairs within headers, and is ASCII compatible, so I don't foresee making any changes to Kestrel. Microsoft.Net.Http.Headers in HttpAbstractions looks like the most obvious consumer/producer of such values. ContentDispositionHeaderValue already supports this because it was designed for use in multipart MIME bodies: https://github.com/aspnet/HttpAbstractions/blob/5128efe0e88eaa176d4231ff62d754de59bb0edd/src/Microsoft.Net.Http.Headers/ContentDispositionHeaderValue.cs#L347
>
> Move to HttpAbstractions?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2688
