### ISSUE TITLE
Add a marker in built-in terminal middleware to distinguish between "soft" and "hard" 404

### ISSUE THREAD

**Issue by khellang** [aspnet/HttpAbstractions#945]
I've come across a scenario where I'd like to determine if a 404 response coming up the pipeline was the result of hitting the built-in terminal middleware ("hard" 404) or if someone actually handled the request, but returned 404 anyway ("soft" 404). This can be solved easily by adding a marker in `HttpContext.Items` for middleware to check. Would you accept a PR for something like that?

**Comment by Tratcher** [comment]
What would it do if it detected a soft 404?

**Comment by khellang** [comment]
So, the scenario is that I have an API that also serves a SPA using StaticFiles. Right before StaticFiles, I have a MW that runs the pipeline and then checks if a 404 comes back. When a 404 comes back, I "fall back" to `/index.html` and re-executing the pipeline. This results in client-side routes (which doesn't get handled on the server) getting served index.html, and the client-side JS routing can take over. The only problem is if the API actually sends a soft 404. In that case, I don't want to fall back to index.html, but send a `application/problem+json` response.

**Comment by khalidabuhakmeh** [comment]
Wouldn’t it be better to react to the requested content type instead? If the client asks for HTML respond with that. If it wants JSON, respond with that. Just saying :)

**Comment by rynowak** [comment]
We're working on some changes over in the routing repo that will solve this if you want to opt in to the new model in 2.1.0

Basically we want to decide fairly early what endpoint is going to match, and then let middleware see that. When you get to the end of the chain, only then will it call into the actual endpoint.  (usually you will have routing at the end today).

**Comment by khellang** [comment]
> Wouldn’t it be better to react to the requested content type instead? If the client asks for HTML respond with that. If it wants JSON, respond with that. Just saying :)

That's not what this is about. If I have a client-side route, `https://my-app.com/customer-info`, and share that with a friend. When she goes to that URL, there's nothing on the server that can handle that URL. In that case, I want to serve index.html (which includes JavaScript for client-side routing). I basically want a catch-all route that uses StaticFiles and doesn't respond to soft 404s 😄

**Comment by Tratcher** [comment]
I've seen people tackle this SPA problem from the other end, rewriting requests as they come in rather than reacting to 404s.

**Comment by khellang** [comment]
> I've seen people tackle this SPA problem from the other end, rewriting requests as they come in rather than reacting to 404s.

How do you know which request to rewrite up-front though? It could be handled by all kinds of different MW. The point of this MW is that it should be independent from any routing or other MW 😄

**Comment by khellang** [comment]
I want the same as [`MapSpaFallbackRoute ` in `Microsoft.AspNetCore.SpaServices`](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#routing-helper-mapspafallbackroute), but something a bit more robust and not coupled to MVC's routing.

**Comment by Tratcher** [comment]
Feel free to build a sample and we can see if it's general purpose enough to fit in the stack somewhere. Otherwise aspnet-contrib may be a good place for it.

**Comment by khellang** [comment]
> We're working on some changes over in the routing repo that will solve this if you want to opt in to the new model in 2.1.0

> Feel free to build a sample and we can see if it's general purpose enough to fit in the stack somewhere. Otherwise aspnet-contrib may be a good place for it.

@Tratcher @rynowak Does that mean adding a marker in the current MW is out of the question?

**Comment by khellang** [comment]
Here's what I ended up with: https://gist.github.com/khellang/47e8fac5b1bad2df74cb8c145d32f98e.

It's used either like this:

```csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace SpaFallback
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSpaFallback(); // <-- Would love to remove this...
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseStaticFiles();
            app.UseMvc();
        }
    }
}
```

Or like this:

```csharp
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace SpaFallback
{
    public class Startup
    {
        public void Configure(IApplicationBuilder app)
        {
            app.UseSpaFallback();
            app.UseStaticFiles();
            app.UseMvc();
            app.UseSpaFallbackMarker(); // <-- Would love to remove this...
        }
    }
}
```

As you can see, if the built-in terminal MW added a marker, it would substantially simplify the code. Mostly in the implementation, but also slightly from a user's POV.

**Comment by Tratcher** [comment]
That's not terribly complex code to begin with...

**Comment by khellang** [comment]
@SteveSandersonMS Maybe you'd be interested in pulling something like https://github.com/aspnet/HttpAbstractions/issues/945#issuecomment-333538268 into JavaScriptServices?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2687
