### ISSUE TITLE
Fields in HttpMethods cannot be used in switch

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/HttpAbstractions#953]
The fields are declared as `public static readonly string` hence cant be used in a switch statement.

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/HttpMethods.cs

Why aren't these declared as constants instead of static readonly?

**Comment by benaadams** [comment]
Can't do the very fast `ReferenceEquals` on a constant

**Comment by khellang** [comment]
> Can't do the very fast `ReferenceEquals` on a constant

Is this true? I thought string constants are interned?

**Comment by benaadams** [comment]
Not across assembly boundaries

**Comment by khellang** [comment]
Anyway, this has been discussed time and time again, and is definitely a duplicate; https://github.com/aspnet/HttpAbstractions/issues/795

**Comment by khellang** [comment]
> Not across assembly boundaries

@halter73 says otherwise... https://github.com/aspnet/HttpAbstractions/pull/712#issuecomment-250248509 :wink:

**Comment by benaadams** [comment]
https://github.com/dotnet/coreclr/issues/14208#issuecomment-332586251

> FYI, literal strings are OFTEN interned, but are not guaranteed to be interned.

**Comment by khellang** [comment]
It's hard to argue with Vance 😂

**Comment by benaadams** [comment]
As a guess you could use a pattern matching switch to use a switch anyway?

**Comment by muratg** [comment]
Dup of a few bugs as @khellang correctly points out :)
