### ISSUE TITLE
Print all registered scheme names in exception message for invalid scheme

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#955]
To help with issues like this https://github.com/aspnet/Security/issues/1219#issuecomment-337314228.

/cc @HaoK @Tratcher

**Comment by Tratcher** [comment]
Here: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationService.cs
