### ISSUE TITLE
IFeatureCollection implementation questions

### ISSUE THREAD

**Issue by SinxHe** [aspnet/HttpAbstractions#957]
I have read the source code of IFeatureCollection and FeatureCollection, I notice IFeatureCollection has method `object this[Type key]` and notice the implementation of FeatureCollection use two dic to hold the values. now i am questing about why just merge the two dic and makes IFeatureCollection just inherit IDictionary<Type, object>,  thanks for some guys who can help me! #

**Comment by Tratcher** [comment]
IDictionary has a much larger API surface than we need our want, and the indexer behaves differently for missing values.

The reason there are two collections is for layering. One collection can temporarily wrap another to augment functionality without copying the whole collection.

**Comment by SinxHe** [comment]
@Tratcher Thanks for your time. I got it.
