### ISSUE TITLE
PathString.FromUriComponent(string) should not decode %2F to forward slash

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpAbstractions#959]
%2F, an escaped `/` is one of the only characters that should not be un-escaped by FromUriComponent. All other characters can correctly be round tripped by ToUriComponent, but %2F creates ambiguity if unescaped.
https://github.com/aspnet/HttpAbstractions/blob/c0f937239a0a099b73c67c96ab9e1c875952f67f/src/Microsoft.AspNetCore.Http.Abstractions/PathString.cs#L175

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2686
