### ISSUE TITLE
Encoding plus sign makes no difference

### ISSUE THREAD

**Issue by PawelTroka** [aspnet/HttpAbstractions#964]
Basically this issue is kind of similar to #912, except it's about plus sign ('+') and this time it does not only affects TestHost but shows up also when hosted.

It does not work correctly on TestHost or when hosted and invoked through web browser or any web client for that matter.

It is failing my integration tests where I am using Microsoft.AspNetCore.TestHost v2.0.0 and Microsoft.AspNetCore.WebUtilities v2.0.0. Please notice that my WebApi and WebApi.IntegrationTests are AspNetCore 2.0 but are targeting net461 (due to some of my libraries not yet ported).

Repro:
Unit test:
https://github.com/PawelTroka/Computator.NET/blob/97b666341bf8a9b21fb9dc59f94528ccf830a931/Computator.NET.WebApi.IntegrationTests/CalculateApiTests.cs#L42
Goes through route:
real/{equation}/{x} from method:
https://github.com/PawelTroka/Computator.NET/blob/97b666341bf8a9b21fb9dc59f94528ccf830a931/Computator.NET.WebApi/Controllers/CalculateController.cs#L34
But because encoding plus sign makes no difference we have equation with unencoded plus sign

In images:

When run through browser:
We type encoded url
![image](https://user-images.githubusercontent.com/11928766/32699217-7b4c0f0c-c7b2-11e7-9b36-7d7ca01301e8.png)
What reaches our controller however is already decoded
![image](https://user-images.githubusercontent.com/11928766/32699234-a015fe06-c7b2-11e7-9137-ddbfc5b51e04.png)
So when we are decoding it in another overload of Get(..) we will attempt to decode already decoded expression, which will make us replace plus sign ('+') with space (' ').

The same happens in test:
![image](https://user-images.githubusercontent.com/11928766/32699290-401aa10e-c7b3-11e7-90ab-153860557475.png)
![image](https://user-images.githubusercontent.com/11928766/32699286-33a223a2-c7b3-11e7-8d55-1fc63a5673a6.png)

Also note that this exists at least from AspNetCore v1.1

**Comment by Tratcher** [comment]
This is intentional, everything in the path is unescaped so you can operate on it. Forward slash is the only character that can't be unescaped without changing the meaning of the path. Why are you converting plus to space? That's not an expected form of un-escaping for request paths. That only applies to form urlencoded content.

**Comment by PawelTroka** [comment]
It being intentional indeed solves plus sign issues, however then why I'm getting spaces encoded as pluses when not decoding it myself.

test:
![image](https://user-images.githubusercontent.com/11928766/32746259-51eb982c-c8b5-11e7-82b0-4b833f4e9008.png)

debug:
https://github.com/PawelTroka/Computator.NET/blob/6a5e9976a32cca3084f35d09ebfbcbb0a7a16e58/Computator.NET.WebApi.IntegrationTests/CalculateApiTests.cs#L116
https://github.com/PawelTroka/Computator.NET/blob/6a5e9976a32cca3084f35d09ebfbcbb0a7a16e58/Computator.NET.WebApi/Controllers/CalculateController.cs#L32
![image](https://user-images.githubusercontent.com/11928766/32746220-37e300fa-c8b5-11e7-985e-d1f6f8dd22fd.png)

**Comment by Tratcher** [comment]
Try Uri.EscapeDataString instead.

**Comment by PawelTroka** [comment]
Yes! It works now! Why is it so different than WebUtility.UrlEncode ?

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2683
