### ISSUE TITLE
Need the equivalent of HttpContext.IsDebuggingEnabled

### ISSUE THREAD

**Issue by davidfowl** [aspnet/HttpAbstractions#97]
http://msdn.microsoft.com/en-us/library/system.web.httpcontext.isdebuggingenabled(v=vs.110).aspx

We used to have this in katana with the "host.AppMode" key in the environment dictionary. The default implementation in PipelineCore might map to the environment name "development" in https://github.com/aspnet/Hosting/blob/63f643e0c1d9be3485300a297a74b13c8ed8299e/src/Microsoft.AspNet.Hosting/HostingContext.cs#L34.

/cc @lodejard and @Tratcher  for comments

**Comment by muratg** [comment]
Will https://github.com/aspnet/Hosting/issues/100 solve this?

**Comment by davidfowl** [comment]
Closing this out

**Comment by imranbaloch** [comment]
@davidfowl The `env.IsEnvironment("Development")` returns true whether I select Debug or Release mode from VS. Is it not good to change the environment variable value if I select different configuration?
