### ISSUE TITLE
Where is Base64UrlEncode ?

### ISSUE THREAD

**Issue by panost** [aspnet/HttpAbstractions#972]
I tried to see how Base64UrlEncode and Base64UrlDecode are implemented.

It's supposed to be member of a class named "WebEncoders", but I can't find it

I have read a comment that is been migrated to corefx [System.Text.Encodings.Web](https://github.com/dotnet/corefx/tree/master/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web) but isn't there also

**Comment by Tratcher** [comment]
Looking for this? https://github.com/aspnet/Common/blob/5c3ee37fb773db04a1aea6b67e49395e84fda223/shared/Microsoft.Extensions.WebEncoders.Sources/WebEncoders.cs#L197

**Comment by panost** [comment]
Yes, thank you @Tratcher 

This is the version that currently used in Microsoft.AspNetCore.WebUtilities.dll ?

Anyway,
If it is, I was disappointed a bit, it's just a wrapper around Convert.Base64xxx methods
