### ISSUE TITLE
HeaderDictionary.Add(string key, StringValues value) initializes without StringComparer.OrdinalIgnoreCase

### ISSUE THREAD

**Issue by lundog** [aspnet/HttpAbstractions#978]
In the other three places where Store is initialized, it is case-insensitive:

`new Dictionary<string, StringValues>(1, StringComparer.OrdinalIgnoreCase)`

but in the Add(string key, StringValues value) method Store appears to be initialized as case-sensitive:

`new Dictionary<string, StringValues>(1)`

Shouldn't this match the other three places where Store is initialized? Could this lead to unexpected cases where the HeaderDictionary will be case-sensitive?

**Comment by Tratcher** [comment]
Link: https://github.com/aspnet/HttpAbstractions/blob/4fdeeb31311bb8cca8b62ed9ea4407c10b30518c/src/Microsoft.AspNetCore.Http/HeaderDictionary.cs#L198

Agreed, this is a bug.

That said, be careful calling Add, it has the IDictionary.Add semantic of throwing if the header already exists. The indexer or Append methods are preferred.
