### ISSUE TITLE
RequestCookieCollection inconsistent case sensitivity

### ISSUE THREAD

**Issue by lundog** [aspnet/HttpAbstractions#980]
When RequestCookieCollection is instantiated with a capacity it initializes its inner Store dictionary with StringComparer.OrdinalIgnoreCase:
https://github.com/aspnet/HttpAbstractions/blob/2ce2d8b6c5c4d3111f5bbfe642c478f229bd955f/src/Microsoft.AspNetCore.Http/Internal/RequestCookieCollection.cs#L33

However, when instantiated via the static Parse method it initializes its inner Store dictionary without the OrdinalIgnoreCase option:
https://github.com/aspnet/HttpAbstractions/blob/2ce2d8b6c5c4d3111f5bbfe642c478f229bd955f/src/Microsoft.AspNetCore.Http/Internal/RequestCookieCollection.cs#L74

Similar to #978 
It seems as if the Parse method should initialize Store with OrdinalIgnoreCase to be consistent.

**Comment by Tratcher** [comment]
Agreed.
