### ISSUE TITLE
IHttpBufferingFeature.DisableRequestBuffering is named incorrectly

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/HttpAbstractions#99]
This method currently actually disables dynamic compression on the response when on IIS. It has nothing to do with buffering the request. In fact, if you're desire is to stop buffering of outgoing streaming responses, you *need* to call this API when on IIS.

It should probably be called `DisableResponseCompression` (because that's what it actually does and is intended to do) but that might look odd on the `IHttpBufferingFeature` interface (why are there compression methods on the buffering feature?).

Perhaps the better approach is simply remove this method altogether and reduce the interface to just have `DisableResponseBuffering` and in IIS have it disable both the IIS response buffers *and* the dynamic compression module. After all, that's what you need to do to truly turn of response buffering on IIS anyway.

/cc @davidfowl @lodejard @Tratcher @GrabYourPitchforks

**Comment by muratg** [comment]
What's the decision on this one?

/cc: @glennc

**Comment by davidfowl** [comment]
We need to make sure we revisit this entire area. We started and took tons of notes:

- https://github.com/aspnet/HttpAbstractions/wiki/Rolling-Notes
- https://github.com/aspnet/HttpAbstractions/wiki/Rolling-Notes---Response-Styles
- https://github.com/aspnet/HttpAbstractions/wiki/Rolling-Notes-Response-Stream-Contract

But we haven't finished it. We need to finish it and implement something. 

/cc @lodejard @DamianEdwards @GrabYourPitchforks @Tratcher

**Comment by muratg** [comment]
@glennc Can we get this discussed in the next design meeting?

**Comment by muratg** [comment]
@davidfowl Do we need another API review for HttpAbstractions?

**Comment by anurse** [comment]
This will be covered by aspnet/Hosting#299 (according to @davidfowl)
